---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Keystone Performance-Service-Level 
---
= Service-Leveln
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone bietet Storage-Kapazität auf Basis von vorab definierten Performance-Service-Leveln (Service-Levels) auf Abonnementbasis. Jedem von Keystone Services gemanagten Volume ist ein Service Level zugewiesen.

Die einzelnen Service-Levels werden durch ihre I/O-Dichte definiert, die IOPS/tib/Volume entspricht. Das Verhältnis zwischen Performance (IOPS/Ausgabeoperationen pro Sekunde) und zugewiesener Storage-Kapazität (tib) ist IOPS/tib bei durchschnittlicher Latenz pro Volume.

Die I/O-Dichte für ein Volume wird in einem stündlichen Intervall berechnet, um die I/O-Spitzendichte zu erfassen. Berichte zur I/O-Dichte für Volumes werden monatlich generiert.

Die Service-Level für File-, Block- und Objekt-Storage-Typen sind hier aufgelistet.



== Service-Level für File-Storage

* Unterstützte Protokolle*: NFS, CIFS, iSCSI und FC

|===


| *Service Level* | *Extreme* | *Premium* | *Standard* | *Wert* 


| * Workload-Typ* | Analysen, Datenbanken | VDI, Virtualisierungsapplikationen, Software-Entwicklung | Dateifreigaben, Webserver | Backup 


| *Maximale zugewiesene IOPS/logische tib pro Volume* | 12,288 | 4,096 | 512 | K. A. 


| *Ziel-IOPS/zugewiesener logischer tib pro Volume* | 6,144 | 2,048 | 128 | K. A. 


| *Maximale MB/s/logische tib je Volume* | 384 | 128 | 16 | K. A. 


| * Durchschnittliche Latenz* | <1 ms | <2 ms | <17 ms | K. A. 


| *Blockgröße* 4+| 32K 
|===


=== Mehr auf Service-Leveln für File-Storage

Die Service-Level-Kennzahlen hängen von den folgenden Bedingungen ab:

* Die Service-Level für File- und Block-Storage unterstützen ONTAP 9.7 und höher.
* IOPS/tib/Volume, MB/s/tib/Volume und Latenzwerte für Service-Level basieren auf der Menge der im Volume gespeicherten logischen Daten, der Blockgröße von 32 KB sowie einer zufälligen Kombination von 70-%-Lese- und 30-%-Schreib-I/O-Vorgängen.
* Der tatsächliche IOPS-/tib-/Volume-Wert und MB/s-/tib-Volume können basierend auf der tatsächlichen oder angenommenen Blockgröße, der Parallelität des System-Workloads oder Input/Output-Operationen variieren.
* Die Latenz umfasst nicht Folgendes:
+
** Applikations- oder Host-Latenz erzielt
** Netzwerklatenz des Kunden zu bzw. von den Controller-Ports
** Gemeinkosten für die Datenübertragung an den Objektspeicher bei FabricPool
** Automatische Anwendung der Latenz durch QoS, um den I/O-Wert innerhalb der maximalen Service-Level zu halten


* Latenzwerte gelten nicht für MetroCluster-Schreibvorgänge. Diese Schreibvorgänge sind von der Entfernung von Remote-Systemen abhängig.
* Wenn einem oder mehreren Volumes auf einem Storage-System keine AQoS-Richtlinie zugewiesen ist, werden diese Volumes als nicht konforme Volumes betrachtet und für diese Systeme gelten keine Service-Ziellevel.
* _Expected IOPS_ wird nur für FabricPool angestrebt, wenn die Tiering-Richtlinie auf „keine“ gesetzt ist und sich keine Blöcke in der Cloud befinden. _Expected IOPS_ ist für Volumes bestimmt, die sich nicht in einer synchronen SnapMirror-Beziehung befinden.
* Workload-I/O-Vorgänge müssen gemäß der Keystone Reihenfolge über alle implementierten Controller hinweg ausgeglichen werden.




== Service-Level für Block-Storage

* Unterstützte Protokolle*: FC und iSCSI

|===


| *Service Level* | *Extreme* | *Premium* | *Standard* 


| * Workload-Typ* | HPC | Videoüberwachung | Backup 


| *Ziel-IOPS/tib* 3+| K. A. 


| *max. IOPS/tib* | 5,500 | 4,000 | K. A. 


| *maximaler Durchsatz MB/s (32 KB/IOP)* | 43 | 31 | K. A. 


| * Durchschnittliche Latenz* | <0.5 ms | <0.5 ms | K. A. 


| *Blockgröße* 3+| 32K 
|===


== Service-Level für Objekt-Storage

*unterstütztes Protokoll*: S3

|===


| *Service Level* | Objekt 


| * Workload-Typ* | Medien-Repository, Archivierung 


| *Ziel-IOPS/tib* | K. A. 


| *max. IOPS/tib* | K. A. 


| *maximaler Durchsatz MB/s (32 KB/IOP)* | K. A. 


| * Durchschnittliche Latenz* | K. A. 
|===