---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: Übersicht über NetApp Keystone 
---
= NetApp Keystone FAQ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden Fragen geben Antworten auf Ihre häufigen Fragen zu NetApp Keystone.



=== Was ist NetApp Keystone?

NetApp Keystone ist ein Portfolio an Alternativen für Investitionskosten vor Ort, das aus NetApp Keystone Flex Pay (Flex Pay) und NetApp Keystone Flex Subscription (Flex Subscription) besteht.

* *Flex Pay:* EIN Portfolio von Zahlungslösungen, einschließlich traditioneller Finanzierung, Leasing und fixen/variablen Optionen, um den Cashflow-Anforderungen Ihres Kunden gerecht zu werden.
* *Flex Subscription:* wachstumsorientierte, abonnementbasierter Service mit Cloud-ähnlicher On-Premises-Nutzung mit ergebnisobasierter Serviceoption (von NetApp betrieben). Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone/index.html["Hier"].




=== Welche Vorteile bietet NetApp Keystone meinen Kunden?

NetApp Keystone verbindet die Säulen unserer Investitions- und Hybrid-Cloud-Strategie – mit Agilität, finanzieller Flexibilität und einem reduzierten finanziellen Risiko, das Kunden bei der Erfüllung ihres Cash Flows und ihrer Geschäftsanforderungen unterstützt.

Die Marke NetApp Keystone bietet ein Portfolio flexibler Zahlungslösungen, zu denen klassische Finanzierung, Leasing und feste/variable Optionen für kostenbewusste Kunden sowie FlexSubscription gehören.

* *Flex Pay (finanzielle Flexibilität, Zahlungslösungen):*
+
** Es wird bevorzugt, den Titel der Ressource zu besitzen, aber Zahlung/finanzielle Flexibilität benötigen (Mietmodell, Leasing, Darlehen, Raten).
** Hohe Sicherheitsanforderungen, da keine externen Optionen für Datenverbindungen zur Aktivierung des Abonnements erforderlich sind
** Workloads weisen ein planbares Kapazitätswachstum auf und können auf die Investitionskosten ausgerichtet werden
** Gut gemanagte Infrastruktur mit hoher Asset-Auslastung
** Bevorzugen die Beschaffung von Storage nach Rohkapazität und Beibehaltung der Effizienzvorteile


* *Flex Subscription (OPEX, Cloud-ähnliche Erfahrung):*
+
** Bevorzugen Sie 100% Betriebskosten, so dass Assets nicht auf der Bilanz Ihrer Kunden enden
** Interne/externe Service-Provider, die Kosten an Nutzung/Umsatz ausrichten möchten
** Workloads mit nicht vorhersehbarem Kapazitätswachstum
** Neuzuweisung VON IT-Ressourcen von typischen Storage-Aufgaben (Migrationen, Technologieaktualisierung, Upgrades usw.)
** Kurzfristige Lösung vor der Migration von Workloads in die Cloud
** Zurückführen von Workloads aus der Cloud in On-Premises-Systeme






=== Was ist das Flex-Abonnement?

Flex Subscription ist ein neues, flexibles, on-Premises-abonnementbasiertes Beschaffungsmodell. Kunden profitieren von einer schnelleren Amortisierung, da Hürden beim Management der Ressourcen und einem längeren Beschaffungszyklus beseitigt werden. Mit Flex Subscription können Kunden die Wirtschaftlichkeit auf ihre Geschäftsprioritäten abstimmen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["Hier"].



=== Was bedeutet On-Premises?

Der lokale Standort wird als Datacenter des Kunden oder als eigener Platz in einem externen Rechenzentrum definiert. Der Kunde ist für den Platz-, Strom- und Kühlungsbedarf verantwortlich.



=== Was sind die Vorteile der Flex Subscription Services?

Zu den Vorteilen der Flex Subscription Services gehören:

* IT-Mitarbeiter werden entlastet und können sich auf das Applikationsmanagement konzentrieren
* Reduziert die Vorabinvestitionen
* Kunden können ihre Anforderungen ohne Überprovisionierung erfüllen
* Passt die Storage-Kosten an geschäftliche Anforderungen/Aktivitäten an
* Vereinfacht die Infrastrukturbereitstellung durch Umgehung komplexer Beschaffungsprozesse im Unternehmen
* Sichert Daten vor Ort
* Korrekte Kontrolle über Compliance, Performance und Sicherheit Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["Hier"].

