---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, flex subscription billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: Keystone Flex Abonnement-Abrechnung 
---
= Flex Abonnement Abrechnung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flex Subscription (Flex Subscription) ermöglicht planbare und vorab einplanbare Preise für Ihr Storage-Abonnement.

Wenn Sie Betriebskosten (OPEX) Verbrauchsmodell für Investitionskosten (CAPEX) oder Leasing bevorzugen, können Sie sich für das flexible und skalierbare Nutzungsmodell „Flex Subscription Pay-as-you-grow“-Modell entscheiden.

Flex Subscription bietet Ihnen die folgenden Abrechnungsmöglichkeiten:

* Die Bezahlung basiert auf der Festlegung von IOPS und der Latenz-Kapazität, um verschiedene Workload-Anforderungen zu erfüllen. Mit den verschiedenen Performance-Service-Tiers – Extreme, Premium, Standard und Value – können Sie Ihren Storage basierend auf dem von Ihnen erworbenen Service Level für Ihr Flex Abonnement verwalten.
* Sie bietet planbare Abrechnung für die verplante Kapazität und „Pay-per-use“-Funktion für die variable (Burst) Kapazitätsauslastung.
* Sie können einen Paketpreis für Hardware, Betriebssystem und Support für ein US-Dollar/tib-Preis auswählen. Sie verfügen über eine einzelne Rechnung für jeden Storage-Typ, jeden File-, Block-, Objekt- oder Cloud-Storage-Service.
* Wählen Sie einen flexiblen Begriff für die Services und die Zahlung aus: Sie können 12 Monate, 100 tib oder mehr pro Standort auswählen. Danach können Sie die automatische Verlängerung 12 Monate lang oder monatlich durchführen.


Die Abrechnung für das Flex-Abonnement basiert auf der vorgegebenen Kapazität und dem variablen Burst-Verbrauch.

Informationen zur Verwendung der zugesagt- und Burst-Kapazität finden Sie unter link:nkfsosm_keystone_service_capacity_definitions.html["Kapazitätsdefinitionen für Flex Subscription Service"].

Informationen zum Anzeigen von Rechnungsdetails finden Sie unter link:sewebiug_billing.html["Rechnung anzeigen"].



== Abrechnung basiert auf der verplante Kapazität

Engagierte Kapazität bezieht sich auf die Kapazitäten verschiedener Services in einem einzigen Abonnement, das von den involvierten Parteien (NetApp/Partner und Kunde) vereinbart wurde. Diese Kapazität wird in jeder Flex Subscription -Bestellung angegeben und wird unabhängig vom tatsächlichen Verbrauch in Rechnung gestellt.

Im Rahmen der Flex Subscription Service-Implementierung überwacht NetApp fortlaufend die Nutzung des Service und misst diesen. Alle fünf Minuten wird vom System ein Verbrauchsdatensatz generiert, in dem die aktuelle verbrauchte Kapazität für das Abonnement detailliert beschrieben wird. Diese Daten werden über den Abrechnungszeitraum hinweg aggregiert, um Rechnungen und Nutzungsberichte zu erstellen.



== Abrechnung auf Basis von Burst-Nutzung

Wenn die verbrauchte Kapazität größer ist als die für ein bestimmtes Performance-Service-Level verplante Kapazität, wird der Burst-Verbrauch erfasst und dementsprechend werden Gebühren angewendet. Dieser Prozess erfolgt für jeden generierten Verbrauchsdatensatz. Der Burst-Verbrauch spiegelt daher sowohl die Höhe als auch die Dauer Ihrer zu verbrauchten Kapazitäten zusätzlich zu Ihren engagierten Kapazitäten wider.



== Abrechnungszeitpläne

Flex Subscription Services werden monatlich und jährlich abgerechnet.

Rechnungen werden monatlich versendet. Für den Monat, in dem die Dienstleistungen verfügbar sind, wird im nächsten Monat eine Rechnung verschickt. So wird beispielsweise die Rechnung für die im Januar verwendeten Dienste Anfang Februar zugestellt. Diese Rechnung beinhaltet die Gebühren für die verplante Kapazität und, falls zutreffend, eventuelle Burst-Nutzung.

Eine Rechnung wird zu Beginn jedes Abonnementjahres für die Mindestzahlung der verplanten Kapazität erstellt. Sie wird am Startdatum des Abonnements generiert. Am Ende eines Abonnementquartals wird eine andere Rechnung gesendet, in der die anwendbaren Gebühren für jegliche Burst-Nutzung in diesem Quartal zusammengefasst werden. Wenn die zugesandte Kapazität während eines Abonnements geändert wird, wird eine Rechnung am selben Tag versendet, an dem die Änderung der zugesandten Kapazität wirksam ist, für die anteiligen Mindestzahlungen für den Rest des Abonnementjahres.



== Verschiedene Szenarien für die Flex Subscription-Abrechnung

Es gibt verschiedene Szenarien für die Flex Subscription-Abrechnung, und Sie sollten mit diesen Szenarien vertraut sein.



=== Abrechnung für geklonte Volumes

Wenn Volumes in ONTAP geklont werden und Sie sie zum Backup und zur Wiederherstellung Ihrer Daten verwenden, können Sie die Klone ohne zusätzliche Zahlungen weiterhin verwenden. Geklonte Volumes, die für andere Zwecke in Ihrem Unternehmen für einen hohen Zeitraum genutzt werden, werden jedoch in Rechnung gestellt.

Beachten Sie Folgendes:

* Der Verbrauch der geklonten Volumes wird während der ersten 24 Stunden nach der Klonerstellung nicht berücksichtigt. Während dieser Zeit fallen für diese Zeit keine Gebühren an.
* Geklonte Volumes mit Standard- und Value-Performance-Service-Leveln werden nicht als Verbrauch betrachtet, wenn keine neuen Daten auf das Volume geschrieben werden. So werden beispielsweise in einem Anwendungsfall für Backup oder Wiederherstellung die Daten eines geklonten Volume gesichert oder wiederhergestellt. Die Daten werden im geklonten Volume selbst nicht verändert – und sie werden nicht als Verbrauch betrachtet.




=== Abrechnung für MetroCluster

Die erweiterte Datensicherung verwendet NetApp MetroCluster für die Spiegelung von Daten zwischen zwei physisch getrennten Clustern. In MetroCluster gespiegelten Aggregaten werden die Daten zweimal pro Cluster geschrieben. Die Servicegebühren für Flex Subscription für den Verbrauch auf jeder Seite werden unabhängig voneinander berechnet, was zu zwei identischen Verbrauchsdatensätzen führt. Wenn Sie Ihre Cluster über ONTAP System Manager (System Manager) oder Active IQ Unified Manager (Unified Manager) überwachen, kann es zu Abweichungen zwischen dem Verbrauch über diese Tools und dem flexiblen Abonnement kommen. System Manager und Unified Manager melden keine Volumes im gespiegelten (Remote-) Cluster und melden dabei die Hälfte der Verbrauchsmetriken, die der Flex Subscription Service meldet.

Beispiel: Standort A und Standort B werden in einer MetroCluster-Konfiguration eingerichtet. Wenn ein Benutzer ein Volume von 10 TB in Standort A erstellt, wird in Standort B ein identisches Volume mit 10 TB erstellt Flex Subscription unterscheidet sowohl die Volumes als auch zeichnet eine zusätzliche Verbrauchsmenge von 10 TB an jedem Standort auf. Das ergibt eine Gesamtsteigerung von 20 TB. System Manager und Unified Manager berichten über ein 10-TB-Volume, das in Standort A erstellt wurde



=== Abrechnung für temporäre Volumes

Gelegentlich werden durch ONTAP temporäre Volumes (TMP) beim Verschieben von Volumes erstellt. Diese temporären Volumen sind kurzlebig, und der Verbrauch auf diesen Volumen wird nicht für die Abrechnung gemessen.



=== Abrechnung und anpassungsfähige QoS-Richtlinien

Flex Subscription misst die Nutzung basierend auf Performance-Service-Leveln. Jedes Performance-Service-Level ist mit einer spezifischen QoS-Richtlinie (Quality of Service) verknüpft. Während der Bereitstellung werden Sie über die Details der einzelnen QoS-Richtlinien für Ihre abonnierten Flex Subscription Services informiert. Stellen Sie während des Storage-Managements sicher, dass Ihren Volumes über die entsprechenden QoS-Richtlinien verfügen, die Ihren abonnierten Performance-Service-Leveln zugewiesen werden, um eine unerwartete Abrechnung zu vermeiden. Weitere Informationen zu QoS-Richtlinien in ONTAP finden Sie unter link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Durchsatz garantieren mit QoS-Übersicht"].



=== Abrechnung für SnapMirror Ziele

Die Preise für das SnapMirror Ziel-Volume unterliegen der QoS-Richtlinie für das auf dem Quell-Volume zugewiesene Performance Service Level (Service Level). Wenn der Quelle jedoch keine zugewiesene QoS-Richtlinie vorliegt, wird das Ziel basierend auf dem niedrigsten verfügbaren Service-Level in Rechnung gestellt.



=== Abrechnung für FlexGroups

FlexGroups werden basierend auf der adaptiven QoS-Richtlinie des FlexGroup abgerechnet. Die QoS-Richtlinien ihrer Komponenten werden nicht berücksichtigt.



=== Abrechnung für LUNs

Bei LUNs wird in der Regel dasselbe Abrechnungsmuster wie bei den Volumes befolgt, die durch QoS-Richtlinien unterliegen. Wenn separate QoS-Richtlinien auf LUNs festgelegt sind, dann:

* Die LUN-Größe wird gemäß dem zugehörigen Service-Level der LUN für den Verbrauch gezählt.
* Der restliche Speicherplatz im Volume wird, falls vorhanden, gemäß der QoS-Richtlinie des Service-Levels, die auf dem Volume festgelegt sind, berechnet.




=== System- und Root-Volumes

System- und Root-Volumes werden als Teil der Gesamtüberwachung des Flex Subscription-Dienstes überwacht, werden aber nicht gezählt oder in Rechnung gestellt. Der Verbrauch auf diesen Mengen ist für die Abrechnung ausgenommen.
