---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: NetApp Service Engine/Self-Service Access Portal 
---
= NetApp Service Engine/Self-Service-Zugriffsportal
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden FAQ gelten für die NetApp Service Engine.

*Was ist NetApp Service Engine?*

NetApp Service Engine ist ein Self-Service-Portal, das über das von NetApp betriebene Modell zur Anmeldung und Storage-Bereitstellung basierend auf Ihrem NetApp Keystone Flex-Abonnementservice verfügbar ist. Das Tool erstellt außerdem Berichte über die Nutzungsniveaus für das Abonnement und leitet alle Serviceanfragen oder Abonnementänderungen ein.

*NetApp Service Engine erforderlich im kundenbetriebenen Modell?*

In einem vom Kunden betriebenen Modell ist die NetApp Service Engine gefragt. Sie enthält grundlegende Berichte zu den Verbrauchsangaben und ist erforderlich, um die Rechnungsinformationen zu sammeln und zu melden.

*Wo ist die NetApp Service Engine installiert?*

In einem von NetApp betriebenen Modell wird die NetApp Service Engine lokal auf den von NetApp bereitgestellten Computing-Ressourcen installiert. In einem vom Kunden betriebenen Modell wird die NetApp Service Engine auf den vom Kunden bereitgestellten Computing-Ressourcen installiert.

*Wer kann sich bei der NetApp Service Engine anmelden?*

Benutzer können gegen NetApp SSO bzw. lokale Benutzer authentifiziert werden, die in der NetApp Service Engine konfiguriert sind.

*Wie wird der Zugriff gesteuert?*

Die NetApp Service Engine bietet eine rollenbasierte Zugriffssteuerung (RBAC) und jeder Benutzer kann einer Rolle zugewiesen werden, welche Aktionen er ausführen kann. Die RBAC-Zuweisung wird vom Kunden mithilfe der NetApp Service Engine ausgeführt.

*Welche Zugriffskontrollen stehen zur Verfügung?*

Die folgenden Zugriffssteuerungen sind verfügbar:

* *Partner Admin.* ein Administrator der Partnerseite, der über die Rechte verfügt, Mandanten zu erstellen und zu verwalten, Abonnements für Mandanten zu verwalten, Nutzungsberichte anzuzeigen und technische Aspekte des Storage zu managen.
* *Kunde/Mieter Admin.* eine administrative Person aus Kundenseite, die über die Rechte verfügt, Änderungen an Abonnements anzufordern, neue Benutzer und Untermandanten zu erstellen und anzuzeigen sowie Dateifreigaben, Laufwerke und Buckets zu erstellen und anzuzeigen.
* *NetApp Admin (gelesen).* EIN NetApp Administrator, der Zugriff auf alle Komponenten des Webportals hat und alle Details anzeigen kann, wie z.B. alle NetApp Keystone Flex Subscription, Partner und Mandanten Abonnements und Storage. Dieser Benutzer hat jedoch keine Berechtigung zum Erstellen, Bearbeiten oder Löschen.
* *NetApp Admin.* dieser Benutzer hat vollen Zugriff und Berechtigungen zur Durchführung aller Funktionen im NetApp Service Engine Webportal für das NetApp Keystone Flex Abonnement und aller Aktivitäten für Partner- und Mandantenadministration.


*Wo kann ich die Abrechnung gegen meine Nutzung sehen?*

Sie können die aggregierten monatlichen Gebühren für Ihre Abonnements für die letzten drei Monate im Widget *Monatliche Gebühren* auf dem Dashboard anzeigen. Sie können detaillierte Rechnungsinformationen anzeigen, indem Sie durch das Widget klicken oder zu *VERWALTUNG* > *Abrechnung* navigieren.
