---
sidebar: sidebar 
permalink: nkfsfaq_operating_models.html 
keywords: netapp, keystone, operating, models, 
summary: Betriebsmodelle 
---
= Betriebsmodelle und Verantwortlichkeiten
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es gibt drei Betriebsmodelle in flexiblen Abonnements. Diese FAQs beziehen sich auf die Betriebsmodelle.



=== Welche Betriebsmodelle gibt es und wer ist verantwortlich für die wichtigsten Aktivitäten?

Das folgende Diagramm zeigt die drei Betriebsmodelle auf, die ein Kunde auswählen kann: NetApp betrieben, Partner betrieben und vom Kunden betrieben.

* *NetApp-betriebene Modell*: NetApp führt das End-to-End Management von Installation, Implementierung, Betrieb, Monitoring, Optimierung und Support durch.
* *Partner-Operated Model*: Der Anteil von Rollen und Verantwortlichkeiten hängt vom SLA zwischen Ihnen und dem Dienstleister oder Partner ab. Weitere Informationen erhalten Sie von Ihrem Dienstanbieter.
* *vom Kunden betriebenes Modell*: Die folgende Tabelle fasst das gesamte Service Lifecycle Modell und die damit verbundenen Rollen und Verantwortlichkeiten in einer kundengesteuerten Umgebung zusammen.


|===
| Aufgabe | NetApp | Kunde 


| Installation und zugehörige Aufgaben * Installieren * Konfigurieren * Bereitstellen * integriert | Symbol:prüfen[] | Keine 


| Administration and Monitoring * Monitor * Report * Durchführen von Verwaltungsaufgaben * Warnung | Keine | Symbol:prüfen[] 


| Betrieb und Optimierung * Kapazitätsmanagement * Performance managen * SLA managen | Keine | Symbol:prüfen[] 


| Support * Support-Kunde * Hardware-Reparatur * Software-Support * Upgrades und Patches | Symbol:prüfen[] | Keine 
|===


=== Was ist ein NetApp-operated Modell?

Bei diesem Betriebsmodell kann der Kunde die angebotenen Services gemäß den ausgewählten Performance Tiers und Storage-Service-Typen abonnieren und die von NetApp betriebene Option gegen Aufpreis auswählen. NetApp definiert die Architektur und die Produkte, wird beim Kunden installiert und NetApp managt die täglichen Infrastrukturmanagement-Vorgänge mithilfe unserer Storage- und IT-Ressourcen. Verfügbare Storage-Servicetypen sind File, Block (iSCSI) und Objekt. Cloud Volumes Service für GCP und AWS werden ebenfalls unterstützt.

NetApp erstellt und managt zudem Partner, Mandanten, falls zutreffend, und das Abonnement.



=== Was ist ein partnerbetriebenes Modell?

Das Betriebsmodell für den Partner oder Dienstleister ist dem von NetApp betriebenen Modell ähnlich, wobei der Partner den Service für seinen Endkunden aufführt. In diesem Modell wird der Partner als Vertragspartei referenziert. Mandanten sind Kunden der Service Provider und haben keine Abrechnungsbeziehung zu NetApp. Sie managen ihre Mandantenfähigkeit und ihre Kunden. Die Support-Anfragen für Mandanten werden zuerst vom Service-Provider bearbeitet, bevor sie an NetApp weitergeleitet werden.



=== Was ist ein kundengetriebenes Modell?

Mit diesem Betriebsmodell kann der Kunde einen angebotenen Service gemäß den ausgewählten Performance Tiers und Storage-Servicetypen abonnieren. NetApp definiert die Architektur und die Produkte und wird beim Kunden vor Ort installiert und ermöglicht Kunden das Management der Infrastruktur mithilfe ihrer Storage- und IT-Ressourcen. Verfügbare Storage-Servicetypen sind File, Block (iSCSI) und Objekt. In diesem Modell hat der Kunde auf den unter Vertrag genommenen Hersteller Bezug genommen, und dies kann ein Endbenutzer oder Partner sein.



=== Wer besitzt die Ausrüstung?

Bei allen drei Betriebsmodellen ist NetApp für die gesamte Hardware und Software verantwortlich, die beim Kunden vor Ort installiert ist.
