---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, Keystone billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: Keystone Abrechnung 
---
= Keystone Abrechnung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone ermöglicht planbare und Vorauspreise für Ihr Storage-Abonnement.

Wenn Sie Betriebskosten (OPEX) Verbrauchsmodell für Investitionskosten (CAPEX) oder Leasing vorziehen, können Sie sich für das Keystone Pay-as-you-grow-Modell für Ihr flexibles und skalierbares Nutzungsmodell entscheiden.

Keystone bietet Ihnen folgende Abrechnungsmöglichkeiten:

* Die Bezahlung basiert auf der Festlegung von IOPS und der Latenz-Kapazität, um verschiedene Workload-Anforderungen zu erfüllen. Mit den verschiedenen Performance-Service-Tiers Extreme, Premium, Standard und Value können Sie Ihren Storage auf der Basis des von Ihnen erworbenen Service Levels für Keystone Services managen.
* Sie bietet planbare Abrechnung für die verplante Kapazität und „Pay-per-use“-Funktion für die variable (Burst) Kapazitätsauslastung.
* Sie können einen Paketpreis für Hardware, Betriebssystem und Support für ein US-Dollar/tib-Preis auswählen. Sie verfügen über eine einzelne Rechnung für jeden Storage-Typ, jeden File-, Block-, Objekt- oder Cloud-Storage-Service.
* Wählen Sie einen flexiblen Begriff für die Services und die Zahlung aus: Sie können 12 Monate, 100 tib oder mehr pro Standort auswählen. Danach können Sie die automatische Verlängerung 12 Monate lang oder monatlich durchführen.


Die Keystone-Abrechnung basiert auf engagierter Kapazität und variabler Burst-Nutzung.

Informationen zur Verwendung der zugesagt- und Burst-Kapazität finden Sie unter link:nkfsosm_keystone_service_capacity_definitions.html["Keystone Service-Kapazitätsdefinitionen"].



== Abrechnung basiert auf der verplante Kapazität

Engagierte Kapazität bezieht sich auf die Kapazitäten verschiedener Services in einem einzigen Abonnement, das von den involvierten Parteien (NetApp/Partner und Kunde) vereinbart wurde. Diese Kapazität wird in jeder Keystone-Bestellung angegeben und wird unabhängig vom tatsächlichen Verbrauch abgerechnet.

.Messung der verbrauchten Kapazität
Im Rahmen der Keystone-Serviceimplementierung überwacht und misst NetApp fortlaufend die Nutzung des Service. Mindestens einmal in fünf Minuten wird vom System ein Verbrauchsdatensatz erstellt, in dem die aktuell verbrauchte Kapazität für das Abonnement detailliert aufgeführt wird. Diese Daten werden über den Abrechnungszeitraum hinweg aggregiert, um Rechnungen und Nutzungsberichte zu erstellen.



== Abrechnung auf Basis von Burst-Nutzung

Wenn die verbrauchte Kapazität größer ist als die für ein bestimmtes Service-Level verplante Kapazität, wird der Burst-Verbrauch erfasst und dementsprechend werden Gebühren angewendet. Dieser Prozess erfolgt für jeden generierten Verbrauchsdatensatz. Der Burst-Verbrauch spiegelt daher sowohl die Höhe als auch die Dauer Ihrer zu verbrauchten Kapazitäten zusätzlich zu Ihren engagierten Kapazitäten wider.



== Abrechnungszeitpläne

Keystone Services werden monatlich und jährlich in Rechnung gestellt.

.Monatliche Abrechnung
Rechnungen werden monatlich versendet. Für den Monat, in dem die Dienstleistungen verfügbar sind, wird im nächsten Monat eine Rechnung verschickt. So wird beispielsweise die Rechnung für die im Januar verwendeten Dienste Anfang Februar zugestellt. Diese Rechnung beinhaltet die Gebühren für die verplante Kapazität und, falls zutreffend, eventuelle Burst-Nutzung.

.Jährliche Abrechnung
Eine Rechnung wird zu Beginn jedes Abonnementjahres für die Mindestzahlung der verplanten Kapazität erstellt. Sie wird am Startdatum des Abonnements generiert. Am Ende eines Abonnementquartals wird eine andere Rechnung gesendet, in der die anwendbaren Gebühren für jegliche Burst-Nutzung in diesem Quartal zusammengefasst werden. Wenn die zugesandte Kapazität während eines Abonnements geändert wird, wird eine Rechnung am selben Tag versendet, an dem die Änderung der zugesandten Kapazität wirksam ist, für die anteiligen Mindestzahlungen für den Rest des Abonnementjahres.

.Kulanzzeit bei Burst-Rechnungen
Während der ersten 60 Tage nach der Aktivierung eines Abonnements wird jeder zusätzliche Burst-Verbrauch, der Ihnen angefallen ist, auf der Rechnung des Keystone Service aufgezeichnet. Diese Kulanzzeit gibt Ihnen die Zeit, Ihren Speicher mit den entsprechenden AQoS-Einstellungen (Adaptive Quality of Service) zu konfigurieren, damit er ordnungsgemäß überwacht und abgerechnet werden kann. Bei der richtigen Konfiguration des Storage können Sie unerwartete Burst-Gebühren vermeiden. Jegliche Burst-Nutzung, die nach der anfänglichen Kulanzzeit von 60 Tagen angesammelt wurde, wird auf Ihrer nächsten Rechnung in Rechnung gestellt. Diese Kulanzzeit hat keine Auswirkungen auf Änderungen oder Verlängerungen Ihrer bestehenden Abonnements.



== Verschiedene Szenarien für Keystone Abrechnung

Es gibt verschiedene Szenarien für die Keystone Abrechnung. Sie sollten mit diesen Szenarien vertraut sein.



=== Abrechnung für geklonte Volumes

Wenn Volumes in ONTAP geklont werden und Sie sie zum Backup und zur Wiederherstellung Ihrer Daten verwenden, können Sie die Klone ohne zusätzliche Zahlungen weiterhin verwenden. Geklonte Volumes, die für andere Zwecke in Ihrem Unternehmen für einen hohen Zeitraum genutzt werden, werden jedoch in Rechnung gestellt.

Beachten Sie Folgendes:

* Klon-Volumes berechnen keine Kosten, solange ihre Größe weniger als 10 % des übergeordneten Volume beträgt (die physische Kapazität, die im Klon-Volume im Vergleich mit der im übergeordneten Volume genutzten physischen Kapazität verwendet wird).
* Für geklonte Volumes gibt es keine 24-Stunden-Frist, es wird nur die Größe des Klons berücksichtigt.
* Sobald das Klon-Volume 10 % der physischen Größe des übergeordneten Volume überschreitet, wird der Klon als Standard-Volume abgerechnet (genutzte logische Kapazität).




=== Abrechnung für MetroCluster

Die erweiterte Datensicherung verwendet NetApp MetroCluster für die Spiegelung von Daten zwischen zwei physisch getrennten Clustern. In MetroCluster gespiegelten Aggregaten werden die Daten zweimal pro Cluster geschrieben. Keystone Servicegebühren für unabhängige Nutzung auf beiden Seiten, was zwei identische Verbrauchsaufzeichnungen zur Folge hat. Wenn Sie Ihre Cluster über ONTAP System Manager (System Manager) oder Active IQ Unified Manager (Unified Manager) überwachen, wird möglicherweise zwischen dem in diesen Tools gemeldeten Verbrauch und den Keystone Services Diskrepanzen festgestellt. System Manager und Unified Manager melden keine Volumes auf dem gespiegelten (Remote-) Cluster und melden so die Hälfte der Verbrauchsmetriken, die der Keystone-Service meldet.

Beispiel: Standort A und Standort B werden in einer MetroCluster-Konfiguration eingerichtet. Wenn ein Benutzer ein Volume von 10 TB in Standort A erstellt, wird in Standort B ein identisches Volume mit 10 TB erstellt Keystone unterscheidet sowohl die Volumes als auch zeichnet an jedem Standort eine zusätzliche Verbrauchsmenge von 10 TB auf, sodass sich die Gesamtmenge um 20 TB erhöht. System Manager und Unified Manager berichten über ein 10-TB-Volume, das in Standort A erstellt wurde



=== Abrechnung für temporäre Volumes

Gelegentlich werden durch ONTAP temporäre Volumes (TMP) beim Verschieben von Volumes erstellt. Diese temporären Volumen sind kurzlebig, und der Verbrauch auf diesen Volumen wird nicht für die Abrechnung gemessen.



=== Abrechnung und anpassungsfähige QoS-Richtlinien

Keystone misst den Verbrauch anhand von Service-Leveln. Jedes Service-Level ist mit einer bestimmten QoS-Richtlinie (Quality of Service) verknüpft. Während der Bereitstellung werden Sie über die Details der einzelnen QoS-Richtlinien für Ihre abonnierten Keystone Services informiert. Stellen Sie während des Storage-Managements sicher, dass Ihren Volumes über die entsprechenden QoS-Richtlinien verfügen, die Ihren abonnierten Service Leveln zugewiesen werden, um eine unerwartete Abrechnung zu vermeiden. Weitere Informationen zu QoS-Richtlinien in ONTAP finden Sie unter link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Durchsatz garantieren mit QoS-Übersicht"].



=== Abrechnung für SnapMirror Ziele

Die Preise für das SnapMirror Ziel-Volume unterliegen der QoS-Richtlinie für das Service-Level, das auf dem Quell-Volume zugewiesen ist. Wenn der Quelle jedoch keine zugewiesene QoS-Richtlinie vorliegt, wird das Ziel basierend auf dem niedrigsten verfügbaren Service-Level in Rechnung gestellt.



=== Abrechnung für FlexGroups

FlexGroups werden basierend auf der adaptiven QoS-Richtlinie des FlexGroup abgerechnet. Die QoS-Richtlinien ihrer Komponenten werden nicht berücksichtigt.



=== Abrechnung für LUNs

Bei LUNs wird in der Regel dasselbe Abrechnungsmuster wie bei den Volumes befolgt, die durch QoS-Richtlinien unterliegen. Wenn separate QoS-Richtlinien auf LUNs festgelegt sind, dann:

* Die LUN-Größe wird gemäß dem zugehörigen Service-Level der LUN für den Verbrauch gezählt.
* Der restliche Speicherplatz im Volume wird, falls vorhanden, gemäß der QoS-Richtlinie des Service-Levels, die auf dem Volume festgelegt sind, berechnet.




=== Abrechnung für FabricPool-Nutzung

Wenn Daten von einem Keystone System zu ONTAP Simple Storage Service (S3) Objekt-Storage oder NetApp StorageGRID verschoben werden, wird die verbrauchte Kapazität auf dem Hot Tier (Keystone System) um die Menge der Daten reduziert, die abgestuft wurden. Dies wirkt sich auf die dafür bezahlen. Dabei spielt es keine Rolle, ob der ONTAP S3-Storage oder das StorageGRID-System durch das Keystone Abonnement abgedeckt wird.

Informationen zum Tiering von Daten auf beliebigen Objekt-Storage von Drittanbietern erhalten Sie von Ihrem Keystone Success Manager.

Informationen zur Verwendung der FabricPool Technologie für Ihre Keystone-Abonnements finden Sie unter link:nkfsosm_tiering.html["Tiering"].



=== Abrechnung für System- und Root-Volumes

System- und Root-Volumes werden als Teil der Gesamtüberwachung des Keystone Service überwacht, jedoch nicht gezählt oder abgerechnet. Der Verbrauch auf diesen Mengen ist für die Abrechnung ausgenommen.
