---
sidebar: sidebar 
permalink: nkfsosm_nrd.html 
keywords: netapp, keystone, NRD, Non-returnable disk 
summary: Keystone und Equinix 
---
= Non-Returnable Disk Angebot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Im Rahmen von NetApp Keystone Services erweitert NetApp das Angebot an Non-Returnable Disk (NRD).

Wenn Sie das NRD-Angebot für Keystone erwerben, stellt NetApp nicht die während der gesamten Servicezeit verwendeten physischen Storage-Medien aufgrund von Support- und Wartungsarbeiten wieder her oder bei der Service-Beendigung, wenn NetApp anderweitig alle physischen Ressourcen wiederherstellt, die bei der Bereitstellung des Service verwendet werden.

Wenn Sie diesen Service erworben haben, beachten Sie Folgendes:

* Selbst beim Kauf dieses Service können Sie für NetApp die Wiederherstellung der physischen Storage-Medien entscheiden.
* Falls NetApp nicht für die Wiederherstellung der Medien verantwortlich ist, sind Sie berechtigt, die bei der Bereitstellung des Keystone Service verwendeten Storage-Medien oder Festplatten am Ende der Serviceerbringung zu vernichten.
* Sie können das NRD-Angebot während der Verlängerung des Abonnements hinzufügen, ändern oder beenden, und nicht während der Laufzeit.
* Die mit dem NRD-Angebot verbundenen Kosten ändern sich basierend auf der zugewiesenen Kapazität des Abonnements. Wenn Sie sich also für eine Erhöhung Ihrer zugesagt Kapazität zur Mitte des Abonnementzeitraums entscheiden, werden die NRD-Kosten ebenfalls überarbeitet. Der Anstieg wird proportional zu der Zunahme der Kapazität.
* Sie können nur die in Ihrem Service verwendeten physischen Storage-Medien aufbewahren. Controller, Shelfs, Kabel, Switches, Netzwerkkarten, Sowie jegliche andere Systeme von NetApp werden von NetApp wiederhergestellt.

