---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: Details zum Serviceangebot 
---
= Keystone Serviceangebote
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden Fragen beantworten Ihre häufig gestellten Fragen zum NetApp Keystone Keystone Serviceangebot.

*Was ist die minimale engagierte Kapazität?*

Die zugesicherte Mindestkapazität für einen NetApp Keystone Abonnement-Service beträgt 100 tib pro Standort über eine oder mehrere Service-Tiers.

*Wie lange ist die typische Laufzeit eines Keystone Servicevertrags?*

Keystone Services bieten Laufzeiten von 12, 24 und 36 Monaten.

*Wie kann ich auf den Speicher zugreifen?*

In einem von NetApp betriebenen (Standard) Modell sind die Storage Controller (ONTAP System Manager oder administrativer Zugriff auf die Systeme) Eigentum und werden von NetApp gemanagt. Storage-Überwachung ist nur über die digitale Active IQ Benutzeroberfläche möglich.
In einer vom Kunden gemanagten (oder Lite) Implementierung, bei der die Active IQ Digital Advisor UI hauptsächlich für Abrechnungsfunktionen verwendet wird, können Sie auf die Storage-Controller wie beispielsweise Active IQ Unified Manager und ONTAP System Manager zugreifen und direkt auf ONTAP-Cluster zugreifen.

*Wie kann ich den Service verwalten?*

Sie können Support-Tickets für jede Anforderung sammeln.

*Wie kann ich die engagierte Kapazität in einem Abonnement erhöhen?*

Über Ihren NetApp Keystone Success Manager zur Verfügung stellen.

*Verlängert die Erhöhung der Kapazität den Begriff?*

Alle Ergänzungen gelten für die bestehende Laufzeit, außer wenn der Antrag in den letzten 90 Tagen nach dem Abonnement erfolgt, wobei die Laufzeit für mindestens 12 Monate verlängert werden muss.

*Können Abonnements miteinander in Verbindung stehen?*

Nein, die Abonnementzeiträume sind unabhängig voneinander.

*Kann ich Backup-Speicher zu einem bestehenden Abonnement hinzufügen?*

Für einen Backup-Anwendungsfall können Sie einem vorhandenen oder neuen Service-Level, einschließlich Standard- oder Value-Service, Kapazität zu einem vorhandenen Abonnement hinzufügen. Die Laufzeit des bestehenden Abonnements wird dadurch nicht geändert. Es gibt jedoch eine Einschränkung: Wenn Sie die Kapazität innerhalb der letzten 90 Tage nach dem Abonnementzeitraum (d. h. die letzten 90 Tage vor Ablauf Ihres Abonnements) erweitern möchten, müssen Sie das Abonnement um mindestens ein Jahr verlängern.

*Hat ein neues Abonnement Flexibilität, mit einer neuen Jahreslaufzeit zu kommen?*

Ja, neue Abonnements können unabhängig von vorhandenen Abonnements neue Bedingungen haben.

*Können Mietabonnementbedingungen über die Abonnementdauer des Partners hinaus gehen?*

Mandanten-Abonnements können über die aktuelle Laufzeit des Partners für Keystone Services hinausgehen. Beim Erstellen von Abonnements und auch in Nutzungsberichten wird eine Warnung angezeigt.

*Kann ich mehrere Abonnements auf demselben ONTAP Cluster mischen?*

Nein, jedes Cluster ist einem bestimmten Abonnement zugewiesen.

*Wer macht die Überwachung und den Betrieb?*

NetApp ist für den NetApp-Service verantwortlich, die Infrastruktur Remote zu überwachen, sodass der Service gemäß den vereinbarten Erwartungen erbracht wird.

Für den vom Partner durchgeführten Service ist der Partner für die Fernüberwachung der Infrastruktur verantwortlich, so dass der Service entsprechend den vereinbarten Erwartungen erbracht wird.

Für den kundengesteuerten Service ist der Kunde verantwortlich für das Monitoring der Infrastruktur und bei etwaiger Probleme an NetApp.

*Was passiert, wenn ich den Dienst früh absage?*

Die Mindestleistung beträgt 12 Monate. Wenn Sie den Service frühzeitig stornieren, muss der Restwert im Voraus bezahlt werden.

*Gibt es die Möglichkeit, nach Abschluss der ursprünglichen Laufzeit in einen Kauf umzuwandeln?* Nein Das Angebot enthält keine Option zum Umwandeln in einen Kauf. Zudem liegen bereits erworbene NetApp Produkte nicht im Umfang dieses Programms vor.

*Kann ich eine bestimmte Software-Version anfordern?*

Nein NetApp Keystone hat die Softwareversion für den gesamten Kundenstamm standardisiert.

*Werde ich über Software-Upgrades informiert?*

Ja. Alle Wartungs-/Upgrade-Aktivitäten werden mit dem NetApp Keystone Success Manager kommuniziert und zu einem Zeitpunkt geplant, mit dem sich beide Seiten vereinbaren lassen.
