---
sidebar: sidebar 
permalink: nkfsosm_uscs.html 
keywords: netapp, keystone, US citizen support, USCS GSSC, Keystone Success Manager, USCS support 
summary: 'US Citizen Support (USCS)' 
---
= USA Citizen Support (USCS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
USA Citizen Support (USCS) ist ein Add-on-Angebot für NetApp Keystone-Abonnements. Sie erhalten Anspruch auf Lieferung und Support von laufenden Keystone-Services von den USA US-Bürger Bereitgestellt.

Lesen Sie die folgenden Abschnitte, um zu erfahren, welche Elemente Ihrer Abonnements von diesem Add-on-Service gebunden sind und die unter den Bedingungen der NetApp Keystone-Vereinbarung bereitgestellt werden.Fußnote:haftungsausschluss1[die hier beschriebenen Services und Angebote unterliegen einer vollständig ausgeführten Keystone-Vereinbarung und unterliegen diesen Einschränkungen.]



== Monitoring des NetApp Global Services Support Center

Das NetApp Global Services and Support Center (GSSC) überwacht den Zustand Ihrer Produkte und abonnierten Services, bietet Remote-Support und arbeitet mit Ihrem Keystone Success Manager zusammen. Alle Mitarbeiter, die die Produkte im Zusammenhang mit den entsprechenden Keystone Abonnement-Bestellungen überwachen, sind US-Bürger, die in den USA tätig sind Bereitgestellt.



== Keystone Success Manager

Der Keystone Success Manager ist ein U.S. US-Bürger ist tätig Bereitgestellt. Deren Verantwortlichkeiten werden in Ihrer NetApp Keystone-Vereinbarung festgelegt.



== Implementierungsaktivitäten

Sofern verfügbar, werden die Implementierungs- und Installationsaktivitäten vor Ort oder per Remote-Zugriff von US-amerikanischen Unternehmen durchgeführt US-Bürger Bereitgestellt. Fußnote:Haftungsausschluss[die Verfügbarkeit eines geeigneten Personals für Aktivitäten vor Ort ist von dem geografischen Standort abhängig, an dem die Keystone Systeme eingesetzt werden.]



== Unterstützung

Sofern verfügbar, werden die notwendigen Fehlerbehebungs- und Support-Aktivitäten vor Ort von US-amerikanischen durchgeführt US-Bürger Bereitgestellt. Fußnote:Haftungsausschluss[]
