---
sidebar: sidebar 
permalink: nkfsosm_service_terms_and_description_overview.html 
keywords: netapp, keystone, service, terms, description, overview, 
summary: Keystone Serviceinterms und Beschreibungs-Überblick 
---
= Bedingungen und Beschreibungen des Flex Subscription Service
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


* NetApp Keystone Flex-Abonnement (Flex-Abonnement) ist für mindestens ein Jahr und bis zu drei Jahre verfügbar. Nach der Anfangslaufzeit wird der Service jährlich nachgebessbar. Die Kapazität kann in Schritten von nur 1 tib erhöht werden.
* Die Mindestkapazität ist 100 tib pro Standort. Jeder Standort kann über ein oder mehrere Cluster verfügen, um die Mindestkapazitätsanforderungen zu erfüllen. Bei einem vom Partner betriebenen Modell werden für den Kunden, pro Standort und über alle Service-Level Abonnements mit flexiblen Mindeststandards erstellt.
* Die Kapazität von 100 tib kann ein einzelnes Performance-Level oder eine Kombination aus Ebenen sein.
* Mandanten-Abonnements sind auf Service-Level beschränkt, die Partner abonniert haben.
* 20 % der Burst-Kapazität ist an jedem Standort verfügbar. Die Burst-Nutzung wird nur für diesen Abrechnungszeitraum berechnet. Falls Sie zusätzliche Burst-Anforderungen benötigen, die mehr als 20 % betragen, wenden Sie sich an den Support.
* Die zugewandelten Kapazitäten oder Leistungsstufen können während einer Vertragslaufzeit nicht geändert werden.
* Es ist erlaubt, Kapazität zu erhöhen oder langfristig auf ein höheres Performance-Niveau zu wechseln. Es ist jedoch nicht zulässig, von einem höheren Performance-Niveau auf ein niedrigeres Niveau zu wechseln.
* Bei allen Änderungsanforderungen in den letzten 90 Tagen der Laufzeit muss der Kunde den Service mindestens ein Jahr verlängern.

