---
sidebar: sidebar 
permalink: nkfsosm_keystone_service_capacity_definitions.html 
keywords: netapp, keystone, service, capacity, definitions, burst, committed capacity, consumed capacity, billed capacity 
summary: Keystone Service-Kapazitätsdefinitionen 
---
= Keystone Service-Kapazitätsdefinitionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Keystone Service-Kapazitäten umfassen:



== Logische Kapazität

Das sind die Daten, die ein Kunde in die Keystone Infrastruktur setzt. Alle Keystone Kapazitäten beziehen sich auf eine logische Kapazität. Wenn beispielsweise eine 1 tib Datei auf der Keystone Infrastruktur gespeichert ist, muss mindestens 1 tib Kapazität erworben werden.



== Engagierte Kapazität

Die minimale logische Kapazität, die jeden Monat für die Dauer der Laufzeit in Rechnung gestellt wird:

* Jedem Service Level ist die Kapazität zugeordnet.
* Die zugewiesene Kapazität kann während der Laufzeit nicht verringert werden.
* Verplante Kapazität und zusätzliche Service Level können während der Laufzeit hinzugefügt werden.




=== Änderungen der zugesagt Kapazität

Während der Laufzeit eines Abonnements können Sie die zugesagt Kapazitäten ändern. Es gibt jedoch bestimmte Voraussetzungen:

* Die zugewiesene Kapazität kann nicht verringert werden
* Die verplante Kapazität kann nicht 90 Tage vor Ablauf Ihres Abonnements verlängert werden, es sei denn, das Abonnement muss für eine zusätzliche Laufzeit von 12 Monaten verlängert werden.
* Sie können über den Keystone Success Manager Änderungen an der gebuchten Kapazität anfordern.




== Burst-Kapazität

Dies ist die logische Kapazität, die die verplante Kapazität überschritten hat. Beachten Sie folgende Punkte:

* Keystone bietet 20 % Kapazität über die engagierte Kapazität.
* Burst-Kapazität kann flexibel genutzt werden und wird auf täglicher Basis des verbrauchten Durchschnitts abgerechnet.
* Burst-Kapazität wird auf bis zu 20 % mit derselben Rate für die engagierte Kapazität berechnet.
* Burst-Kapazität über 20 % der Verpflichtung wird mit einem Premiumsatz berechnet. Wenden Sie sich an den Support für alle zusätzlichen Burst-Anforderungen über 20 %.




== Verbrauchte/bereitgestellte Kapazität

Die verbrauchte Kapazität bezieht sich auf die Kapazität in tib Speicherplatz, die derzeit auf dem Service genutzt wird. Der Keystone Service berücksichtigt die Summe der bereitgestellten Größen (nicht die genutzte logische oder physische Kapazität) aller Volumes auf einem bestimmten Service Level, die als verbrauchte Kapazität für dieses Service Level betrachtet werden sollen. Hierzu zählen folgende Optionen:

* Die Kapazität, die Bereitstellung über die Erstellung, Änderung, Löschung oder ein potenzielles automatische Wachstum von Volumes erfolgt.
* Die Snapshot Kopien und Klone.
+

NOTE: Die Menge der im Rahmen der bereitgestellten Kapazität gespeicherten Daten oder die tatsächlich auf Festplatte geschriebene Datenmenge werden nicht berücksichtigt.





== Rechnungskapazität

Monatliche Rechnung = (engagierte Kapazität [tib] * engagierte Rate [€/tib]) + (durchschnittliche tägliche bereitgestellte Burst-Kapazität [tib] * Burst-Rate [€/tib]). Die monatliche Abrechnung enthält eine Mindestgebühr, die sich auf die engagierte Kapazität basiert.

Die monatliche Rechnung variiert über die Mindestgebühr basierend auf dem täglichen durchschnittlichen Burst-Kapazitätsverbrauch. Weitere Informationen zur Abrechnung finden Sie unter link:nkfsosm_kfs_billing.html["Keystone Abrechnung"].
