---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: Übersicht über NetApp Keystone 
---
= NetApp Keystone – Häufig gestellte Fragen (FAQs)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden Fragen geben Antworten auf Ihre häufigen Fragen zu NetApp Keystone.

*Was ist NetApp Keystone?*

NetApp Keystone ist ein Portfolio mit alternativen Lösungen für On-Premises-Investitionskosten (CapEx).
Weitere Informationen finden Sie unter https://www.netapp.com/services/keystone/["NetApp Keystone"^].

*Wie profitiert NetApp Keystone meinen Kunden?*

NetApp Keystone ist die Brücke, die die Säulen unserer CapEx- und Hybrid Cloud-Strategie miteinander verbindet und Agilität, finanzielle Flexibilität und ein geringeres finanzielles Risiko bietet, damit Kunden ihre Anforderungen an Cashflow und Geschäft erfüllen können.

Die NetApp Keystone Marke bietet ein Portfolio flexibler Zahlungslösungen, das neben Keystone Services auch klassische Finanzierung, Leasing und feste/variable Optionen für finanzbewusste Kunden umfasst.

*Keystone Services (Betriebskosten, Cloud-ähnliche Nutzung):*
* Vorziehen 100% Betriebskosten, so dass Vermögenswerte nicht in der Bilanz Ihres Kunden enden
* Interne/externe Dienstleister, die Kosten mit Nutzung/Umsatz in Einklang bringen wollen
* Workloads mit unvorhersehbarem Kapazitätswachstum
* Neuzuweisung von IT-Ressourcen aus typischen Storage-Aufgaben (Migrationen, Tech Refresh, Upgrades usw.)
* Kurzfristige Lösung vor der Migration von Workloads in die Cloud
* Zurückführung von Workloads aus der Cloud in lokale Umgebungen

*Was ist NetApp Keystone?*

NetApp Keystone ist ein neues, flexibles On-Premises-Beschaffungsmodell mit Abonnement auf Basis von On-Premises-Systemen. Kunden profitieren von einer schnelleren Amortisierung, da Hürden beim Management der Ressourcen und einem längeren Beschaffungszyklus beseitigt werden. Mit Keystone Services können Kunden die Wirtschaftlichkeit auf ihre geschäftlichen Prioritäten abstimmen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["Hier"].

*Was bedeutet On-Premise?*

Der lokale Standort wird als Datacenter des Kunden oder als eigener Platz in einem externen Rechenzentrum definiert. Der Kunde ist für den Platz-, Strom- und Kühlungsbedarf verantwortlich.

*Welche Vorteile bietet der Keystone Service?*

Keystone Services bieten folgende Vorteile:

* IT-Mitarbeiter werden entlastet und können sich auf das Applikationsmanagement konzentrieren
* Reduziert die Vorabinvestitionen
* Kunden können ihre Anforderungen ohne Überprovisionierung erfüllen
* Passt die Storage-Kosten an geschäftliche Anforderungen/Aktivitäten an
* Vereinfacht die Infrastrukturbereitstellung durch Umgehung komplexer Beschaffungsprozesse im Unternehmen
* Sichert Daten vor Ort
* Korrekte Kontrolle über Compliance, Performance und Sicherheit Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["Hier"].

