---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,fr-fr
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,fr-fr
sidebar:
  entries:
  - title: NetApp Keystone Flex-Abonnement
    url: "/index.html"
    entries:
    - title: Service Bedingungen und Beschreibung
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Definition der Service-Kapazität
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Performance Service Level oder Service Level
        url: "/nkfsosm_performance.html"
      - title: Service Level-Kennzahlen und -Definitionen
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Abrechnung
        url: "/nkfsosm_kfs_billing.html"
      - title: Datensicherung
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Non-Returnable Disk
        url: "/nkfsosm_nrd.html"
      - title: US Citizen Support
        url: "/nkfsosm_uscs.html"
      - title: Flex Abonnement und Equinix
        url: "/nkfsosm_equinix.html"
    - title: Betriebsmodell und Verantwortlichkeiten
      url: "/nkfsosm_overview.html"
    - title: Und Mandantenfähigkeit
      url: "/nkfsosm_tenancy_overview.html"
    - title: Flex Subscription-Infrastruktur
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Standortanforderungen
      url: "/nkfsosm_site_requirements.html"
    - title: Betrieb
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Flex Abonnement und Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/rn_whats_new.html"
    - title: Probleme wurden behoben
      url: "/rn_fixed_issues.html"
    - title: Bekannte Probleme
      url: "/rn_known_issues.html"
  - title: FAQ zu Flex Abonnement
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Flex-Abonnement
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Details zum Serviceangebot
      url: "/nkfsfaq_service_offer_details.html"
    - title: Betriebsmodell
      url: "/nkfsfaq_operating_models.html"
    - title: NetApp Service Engine/Self-Service-Zugriffsportal
      url: "/nkfsfaq_netapp_service_engine_self-service_access_portal.html"
  - title: Die Webschnittstelle der NetApp Service Engine
    url: "/sewebiug_overview.html"
    entries:
    - title: Abrechnung von Konten, Abonnements, Services und Performance
      url: "/sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html"
    - title: Los geht's
      entries:
      - title: Überblick
        url: "/sewebiug_getting_started_overview.html"
      - title: Melden Sie sich an
        url: "/sewebiug_log_in_to_the_netapp_service_engine_web_interface.html"
      - title: Rollen und Betriebsabläufe von Service-Providern und Kunden
        url: "/sewebiug_partner_service_provider.html"
      - title: Wählen Sie einen Mandanten aus
        url: "/sewebiug_select_tenant.html"
      - title: Zeigen Sie die Webschnittstelle der NetApp Service Engine an
        url: "/sewebiug_netapp_service_engine_web_interface_overview.html"
    - title: Zeigen Sie Das Flex Subscription Dashboard An
      url: "/sewebiug_dashboard.html"
    - title: Rechnung anzeigen
      url: "/sewebiug_billing.html"
    - title: Arbeiten Sie mit Fileservices
      url: "/sewebiug_working_with_file_services_overview.html"
      entries:
      - title: View Server
        url: "/sewebiug_view_servers.html"
      - title: Erstellen Sie einen Dateiserver
        url: "/sewebiug_create_a_file_server.html"
      - title: Dateiserver ändern
        url: "/sewebiug_modify_file_server.html"
      - title: Dateiserver löschen
        url: "/sewebiug_delete_file_server.html"
      - title: Freigaben anzeigen
        url: "/sewebiug_view_shares.html"
      - title: Erstellen Sie eine Dateifreigabe
        url: "/sewebiug_create_a_new_file_share.html"
      - title: Erstellen Sie eine Dateifreigabe aus dem Snapshot
        url: "/sewebiug_create_file_share_from_snapshot.html"
      - title: Ändern Sie eine Dateifreigabe
        url: "/sewebiug_modify_a_file_share.html"
      - title: Löschen Sie eine Dateifreigabe
        url: "/sewebiug_delete_a_file_share.html"
      - title: Erstellen Sie einen Ad-hoc-Snapshot einer Dateifreigabe
        url: "/sewebiug_create_adhoc_snapshot_of_a_file_share.html"
    - title: Arbeit mit Block-Storage
      url: "/sewebiug_working_with_block_storage_overview.html"
      entries:
      - title: Arbeiten Sie mit Host-Gruppen
        url: "/sewebiug_view_host_groups.html"
      - title: Zeigen Sie Festplatten an
        url: "/sewebiug_view_disks.html"
      - title: Erstellen Sie eine Festplatte
        url: "/sewebiug_create_a_new_disk.html"
      - title: Erstellen Sie eine Festplatte aus einem Snapshot
        url: "/sewebiug_create_a_disk_from_a_snapshot.html"
      - title: Ändern Sie eine Festplatte
        url: "/sewebiug_modify_a_disk.html"
      - title: Löschen Sie eine Festplatte
        url: "/sewebiug_delete_a_disk.html"
      - title: Erstellen Sie einen Ad-hoc-Snapshot einer Festplatte
        url: "/sewebiug_create_an_adhoc_snapshot_of_a_disk.html"
    - title: Arbeiten mit Objekt-Storage
      entries:
      - title: Überblick
        url: "/sewebiug_working_with_object_storage_overview.html"
      - title: Buckets anzeigen
        url: "/sewebiug_view_buckets.html"
      - title: Objektspeicher initialisieren
        url: "/sewebiug_initialize_object_storage.html"
      - title: Buckets erstellen
        url: "/sewebiug_create_buckets.html"
      - title: Zeigen Sie die Objekt-Storage-Gruppe und Benutzer an
        url: "/sewebiug_view_the_object_storage_group_and_users.html"
      - title: Erstellen Sie eine Objekt-Storage-Gruppe
        url: "/sewebiug_create_an_object_storage_group.html"
      - title: Ändern einer Objektspeichergruppe
        url: "/sewebiug_modify_an_object_storage_group.html"
      - title: Löschen einer Objektspeichergruppe
        url: "/sewebiug_delete_an_object_storage_group.html"
      - title: Objektspeicherbenutzer Erstellen
        url: "/sewebiug_create_object_storage_user.html"
      - title: Ändern eines Objektspeicherbenutzers
        url: "/sewebiug_modify_an_object_storage_user.html"
      - title: Erstellen eines S3-Schlüssels für einen Benutzer
        url: "/sewebiug_create_an_s3_key_for_a_user.html"
      - title: Löschen Sie einen S3-Schlüssel für einen Benutzer
        url: "/sewebiug_delete_an_s3_key_for_a_user.html"
    - title: Management von Cloud-Services
      entries:
      - title: Management von Cloud-Services
        entries:
        - title: Überblick
          url: "/sewebiug_managing_subscribed_services_overview.html"
        - title: Zeigen Sie eine Liste der abonnierten Services an
          url: "/sewebiug_view_a_list_of_subscribed_services.html"
        - title: Fügen Sie einen abonnierten Service hinzu
          url: "/sewebiug_add_a_subscribed_service.html"
        - title: Ändern Sie die abonnierten Servicedetails
          url: "/sewebiug_modify_the_subscribed_service_details.html"
        - title: Einen abonnierten Dienst löschen
          url: "/sewebiug_delete_a_subscribed_service.html"
      - title: Managen Sie Azure NetApp Files
        entries:
        - title: Azure NetApp Accounts managen
          url: "/sewebiug_managing_azure_netapp_accounts.html"
        - title: Management von Azure-Kapazitätspools
          url: "/sewebiug_managing_azure_capacity_pools.html"
        - title: Managen Sie Azure Volumes
          url: "/sewebiug_managing_azure_volumes.html"
      - title: Managen Sie Cloud Volumes Service für die Google Cloud Platform
        url: "/sewebiug_managing_gcp_cvs.html"
    - title: Berichte anzeigen
      url: "/sewebiug_working_with_reports.html"
    - title: Sichern Sie Ihre Volumes
      url: "/sewebiug_back_up_file_shares_and_disks.html"
    - title: Abonnements verwalten
      url: "/sewebiug_managing_subscriptions.html"
    - title: Verwaltung von Service-Anfragen
      entries:
      - title: Überblick
        url: "/sewebiug_managing_service_requests_overview.html"
      - title: Eine Serviceanfrage stellen
        url: "/sewebiug_raise_a_service_request.html"
      - title: Verfolgen Sie eine Service-Anfrage
        url: "/sewebiug_track_a_service_request.html"
      - title: Service-Request-Prozess
        url: "/sewebiug_service_request_process.html"
    - title: Ausführung administrativer Aufgaben
      entries:
      - title: Benutzer managen
        entries:
        - title: Zeigen Sie eine Liste der Benutzer an
          url: "/sewebiug_view_a_list_of_users.html"
        - title: Fügen Sie einen Benutzer hinzu
          url: "/sewebiug_add_a_user.html"
        - title: Benutzerdetails ändern
          url: "/sewebiug_modify_user_details.html"
        - title: Löschen Sie einen Benutzer
          url: "/sewebiug_delete_a_user.html"
      - title: Management von Mandanten und Mandanten
        url: "/sewebiug_managing_tenants_and_subtenants.html"
      - title: Anzeigen und Verwalten von Warnmeldungen
        url: "/sewebiug_alerts.html"
    - title: Netzwerke verwalten
      url: "/sewebiug_define_network_configurations.html"
  - title: NetApp Service Engine API-Referenz
    url: "/seapiref_overview_of_netapp_service_engine_apis.html"
    entries:
    - title: Autorisierung und Authentifizierung
      url: "/seapiref_authorization_and_authentication.html"
    - title: Rest-APIs der NetApp Service Engine
      url: "/seapiref_netapp_service_engine_rest_apis.html"
    - title: Consumer-APIs
      entries:
      - title: Überblick
        url: "/seapiref_consumer_apis_overview.html"
      - title: APIs zur Cloud-Orchestrierung
        url: "/seapiref_cloud_orchestration_apis.html"
      - title: Block-Storage-APIs
        url: "/seapiref_block_storage_apis.html"
      - title: Fileservices-APIs
        url: "/seapiref_file_services_apis.html"
      - title: Objekt-Storage-APIs
        url: "/seapiref_object_storage_apis.html"
      - title: Backup-APIs
        url: "/seapiref_backups_apis.html"
      - title: Reporting-APIs
        url: "/seapiref_reporting_apis.html"
      - title: Subnetze mithilfe von APIs erstellen
        url: "/seapiref_subnets_apis.html"
      - title: "(Verbraucher-)Administrations-APIs"
        url: "/seapiref_@consumer@_administration_apis.html"
    - title: Administrator-APIs
      entries:
      - title: Überblick
        url: "/seapiref_administrator_apis_overview.html"
      - title: Mandanten
        url: "/seapiref_tenants.html"
      - title: Untermieter
        url: "/seapiref_subtenants.html"
      - title: Benutzer
        url: "/seapiref_users.html"
      - title: Zonen
        url: "/seapiref_zones.html"
      - title: Regionen
        url: "/seapiref_regions.html"
      - title: ONTAP Cluster
        url: "/seapiref_ontap_clusters.html"
      - title: StorageGRID Instanzen
        url: "/seapiref_storagegrid_instances.html"
      - title: Service-Leveln
        url: "/seapiref_service_levels.html"
      - title: Service-Anfragen
        url: "/seapiref_service_requests.html"
      - title: Jobs
        url: "/seapiref_jobs.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
