---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp Keystone Services
    url: "/index.html"
    entries:
    - title: Service Bedingungen und Beschreibung
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Definition der Service-Kapazit채t
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Service-Level bei Keystone
        url: "/nkfsosm_performance.html"
      - title: Service-Level-Metriken und -Definitionen
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Anpassungsf채hige Quality of Service bei Keystone
        url: "/aqos-kfs.html"
      - title: Abrechnung
        url: "/nkfsosm_kfs_billing.html"
      - title: Datensicherung
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Non-Returnable Disk
        url: "/nkfsosm_nrd.html"
      - title: US Citizen Support
        url: "/nkfsosm_uscs.html"
      - title: Keystone und Equinix
        url: "/nkfsosm_equinix.html"
    - title: Betriebsmodell und Verantwortlichkeiten
      url: "/nkfsosm_overview.html"
    - title: Und Mandantenf채higkeit
      url: "/nkfsosm_tenancy_overview.html"
    - title: Keystone Infrastruktur
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Standortanforderungen
      url: "/nkfsosm_site_requirements.html"
    - title: Betrieb
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone und Active IQ Digital Advisor
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Anzeigen und Generieren von Berichten 체ber Active IQ Digital Advisor
        url: "/aiq-keystone-details.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/rn_whats_new.html"
    - title: Probleme wurden behoben
      url: "/rn_fixed_issues.html"
    - title: Bekannte Probleme
      url: "/rn_known_issues.html"
  - title: FAQ zu Keystone Abonnements
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Keystone Abonnements
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Details zum Serviceangebot
      url: "/nkfsfaq_service_offer_details.html"
    - title: Betriebsmodell
      url: "/nkfsfaq_operating_models.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
