---
sidebar: sidebar 
permalink: rn_whats_new.html 
keywords: netapp, keystone, release notes, new features, what's new, 
summary: Neue Funktionen der NetApp Service Engine 
---
= What&#8217;s neu in dieser Version von NetApp Keystone Flex Subscription Services
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgende Funktion wurde mit der NetApp Service Engine 2.7 eingeführt, um erweiterte Services für das flexible NetApp Keystone Abonnement (Flex Subscription) zu unterstützen:



== Funktionen der NetApp Service Engine 2.7

Diese Version bietet u. a. folgende neue Funktionen:



=== Möglichkeit zur Anzeige Ihrer Cloud Volumes ONTAP-Nutzung und -Abrechnung über Flex Subscription

Wenn Sie NetApp Keystone Flex Subscription-Kunde sind und darüber hinaus über ein Cloud Volumes ONTAP Abonnement verfügen, können Sie die Nutzung und Abrechnung Ihrer Cloud Volumes über Flex Subscription anzeigen. Cloud Manager kann jetzt die Details zu Ihren Flex-Abonnements entdecken und sie in der Cloud Manager-Benutzeroberfläche anzeigen. Wenn Sie auf die Registerkarte *All Services > Digital Wallet > Keystone Flex Subscription* klicken, können Sie die folgenden Aktionen durchführen:

* Zeigen Sie einen Willkommensbildschirm an, in dem Sie Ihren Flex Subscription Administrator bitten können, Ihre Cloud Manager Benutzer-ID mit Ihrer Flex Subscription-Benutzer-ID zu verknüpfen. So erhalten Sie Zugriff auf die Registerkarte *Keystone Flex Subscription*.
* Zeigen Sie die Verbrauchsdaten der zugesagt und konsumierten Services auf Ihren On-Premises-Systemen und Cloud Volumes ONTAP an.
* Zeigen Sie die Flex-Abonnementdetails an, die mit Ihrem Cloud Manager Konto verknüpft sind. Einzelheiten werden angezeigt, beispielsweise die belegte, verbrauchte und Burst-Kapazität.
* Verknüpfen Sie Ihr Cloud Volumes ONTAP Konto mit Ihren Flex-Abonnement-IDs, um das Konto für die Abrechnung und Kapazitätsauslastung zu verknüpfen.
* Anfrage zur Erhöhung oder Reduzierung der für die abonnierten Flex Subscription Services vergebenen Kapazität.
* Die verknüpfte Flex-Abonnement-ID als Abrechnungsmethode für den Cloud Volumes ONTAP-Verbrauch anzeigen und verwenden (nur verknüpfte IDs).


Weitere Informationen finden Sie unter den folgenden Links in den Dokumenten zu Cloud Manager:link:https://docs.netapp.com/us-en/occm/concept_licensing.html#keystone-flex-subscription["Keystone Flex Abonnement"]



NOTE: Die veröffentlichte Version von NetApp Keystone Flex Subscription 2.7 ist die wichtigste Version nach Version 2.2. Die internen Releases zwischen 2.2 und 2.7 haben nur kleinere Korrekturen.

====

====


== Funktionen der NetApp Service Engine 2.2

Zu den neuen Funktionen in dieser Version gehört ein überarbeitetes Dashboard mit neuen Widgets für Abrechnung, Kapazitätsauslastung, Service-Anfragen und Warnmeldungen. Dieses Release enthält auch neue Bildschirme für Rechnungs- und Warnmeldungs-Management sowie die Umbenennung des Menüs „abonnierte Services“ in Cloud Services.



=== Erweiterte Dashboard-Ansicht

Das Dashboard von NetApp Service Engine wurde neu gestaltet und umfasst folgende neue Komponenten:

* *Kapazitätsauslastung* zur Anzeige der genutzten Kapazität für Ihre abonnierten Dienste.
* *Monatliche Gebühren (Abrechnung)* für die Anzeige der aggregierten monatlichen Gebühren für alle Ihre Abonnements.
* *Alerts* zur Anzeige der Zusammenfassung der neuesten Warnungen in Ihrer Umgebung.
* *Service Requests* für die Anzeige der Liste der letzten Serviceanforderungen, die in Ihrer Umgebung erzeugt wurden. Weitere Informationen finden Sie unter link:sewebiug_dashboard.html["Zeigen Sie Das Flex Subscription Dashboard An"].




=== Bildschirm „Neue Abrechnung“

Für die einfache Zugänglichkeit und Berechnung Ihrer historischen Rechnungsdaten wurde ein neuer *Billing*-Bildschirm hinzugefügt. Der Bildschirm bietet eine ganzheitliche Ansicht der monatlichen Gebühren, die mit allen abonnierten Services verbunden sind.

Navigieren Sie zu diesem Bildschirm über das Widget * Monthly Lades* auf dem Dashboard oder von *ADMINISTRATION > Billing*, um eine monatliche Aufschlüsselung der Gebühren für alle abonnierten Dienste anzuzeigen. Die Rechnungsdaten basieren auf Ihrer zugesagt- und Burst-Kapazitätsauslastung und können für Ihre Nutzung in den vorherigen Monaten bereitgestellt werden. Weitere Informationen finden Sie unter link:sewebiug_billing.html["Rechnung anzeigen"].



=== Bildschirm „Neue Warnungen“

In dieser Version wird ein neuer *Alerts*-Bildschirm eingeführt, der alle vom System erzeugten und vom Benutzer generierten Warnmeldungen auflistet. Auf dem Bildschirm können Sie außerdem benutzerdefinierte Warnmeldungen für kritische Ereignisse erstellen, die Ihre Umgebung betreffen, und diese anderen Benutzern vermitteln. Gegebenenfalls können sie die Alarme anzeigen und verwerfen. Weitere Informationen finden Sie unter link:sewebiug_alerts.html["Erstellen und Managen von Warnmeldungen"].



=== Verbesserte Benutzeroberfläche

Die folgenden Verbesserungen wurden auf der Benutzeroberfläche der NetApp Service Engine vorgenommen:

* Das Menü *Dashboard* im linken Navigationsbereich bietet einen intuitiven Navigationspunkt für den Zugriff auf das Dashboard.
* Das Menü *abonnierte Services* im linken Navigationsbereich wurde in *Cloud Services* umbenannt.


====

====


== Funktionen der NetApp Service Engine 2.1

Zu den neuen Funktionen in dieser Version gehören die Unterstützung von Mandantenfähigkeit in einer Flex Subscription Umgebung sowie die Tiering-Funktion, die das Verschieben inaktiver Daten auf eine kostengünstigere lokale oder Cloud-Tier erleichtert.



=== Einführung von Flex Subscription Services für Service Provider

Die NetApp Service Engine unterstützt jetzt das Management einer mandantenfähigen Umgebung durch einen Service-Provider. Sie können Funktionen für Provisionierung, Berichterstellung, Abrechnung und Management von Kunden mit eigenen Abonnements ausführen. Zur Unterstützung dieser Funktion wurden folgende Verbesserungen vorgenommen:

* *Dashboard:* das Dashboard zeigt Informationen zu den Speicherabonnements an, z. B. Service-Tiers, Kapazitätsnutzung für jedes Servicelevel und zusätzliche Datenschutzdienste für eine bestimmte Abonnementnummer. Als Service-Provider können Sie sich die Details zu Ihren NetApp Keystone Flex Abonnement- und Mandantenabonnements ansehen. Als Mandantenadministrator können Sie die Details zu allen Mandantenabonnements für Ihre Mandantenfähigkeit anzeigen.
* *Berichte:* Sie können Kapazitäts- und Performance-Berichte in Bezug auf Ihre NetApp Keystone Flex Subscription Nutzung und auch für Ihre Mandantennutzung erstellen. Als Partner-Administrator können Sie den Kapazitätsbericht für Ihre Flex Subscription-Nutzung über *Reports* > *Keystone Usage* anzeigen. Als Partner-Administrator können Sie die Berichte zur Kapazitätsnutzung für einen bestimmten Mandanten unter *Reports* > *Tenant-Nutzung*/*Kapazitätsnutzung* anzeigen. Als Mandantenadministrator können Sie die Mietberichte von *Reports* > *Tenant Usage* anzeigen.
* *Abonnement:* als Partner-Administrator können Sie Ihre Flex Abonnement- und Mandantenabonnements von *ABONNEMENTS* > *Keystone Abonnements* und *ABONNEMENTS* > *Tenant-Abonnements* ansehen und aktualisieren. Als Mandantenadministrator können Sie Ihre Mandantenabonnements nur anzeigen.
* *Benutzer:* je nach Ihrer Rolle können Sie einem neuen oder bestehenden Benutzer innerhalb einer Mietfähigkeit Berechtigungen zuweisen, die den Anforderungen entsprechend sind. Die Rolle kann ein NetApp Administrator, ein NetApp Administrator mit reinen Lesezugriff, ein Partner-Administrator oder ein Mandantenadministrator sein. Als Partner-Administrator können Sie neuen Benutzern nur Administrator- oder Mandantenadministratorrollen zuweisen. Ein Mandantenadministrator-Benutzer kann anderen Benutzern nur die Administratorrolle des Mandanten zuweisen.
* *Netzwerke Menü:* als Partner Administrator können Sie die für Ihre Mandantenfähigkeit definierten Netzwerke anzeigen. Sie können Subnetze für Ihren Untermieter und die Zone auch aus *NETWORKS* > *Subnets* erstellen. Dies ist bei der Storage-Bereitstellung durch die Endkunden oder Untermandanten erforderlich.
* API-Unterstützung: Die `/Tenant/{Tenant_id}/Zones/{Zone_Name}/Subnets` und `/Tenant/{Tenant_id}/Zones/{Zone_Name}/Subnets/{id}/Tags` APIs werden im Rahmen dieser Version angeboten, um Subnetze für Untermandanten zu erstellen und anzuzeigen.


Weitere Informationen zu dieser Funktion finden Sie unter den folgenden Links:

* link:nkfsosm_overview.html["Betriebsmodell, Rollen und Verantwortlichkeiten"]
* link:nkfsosm_tenancy_overview.html["Mandantenfähigkeit und Mandantenfähigkeit in Flex Subscription"]
* link:sewebiug_dashboard.html["Zeigen Sie Das Flex Subscription Dashboard An"]
* link:sewebiug_working_with_reports.html["Berichte anzeigen"]
* link:sewebiug_managing_subscriptions.html["Verwalten von Abonnements"]
* link:sewebiug_managing_tenants_and_subtenants.html["Management von Mandanten und Mandanten"]
* link:sewebiug_define_network_configurations.html["Netzwerke für Mandanten und Untermandanten definieren"]




=== Tiering

Der NetApp Keystone Flex Subscription Service umfasst jetzt eine Tiering-Funktion, die die NetApp FabricPool Technologie nutzt. Die Lösung identifiziert weniger häufig verwendete Daten und führt diese in einem Cold Storage durch, der sich im Besitz von NetApp befindet, bereitgestellt und lokal gemanagt wird. Sie können sich für Tiering entscheiden, indem Sie das Performance-Level für extreme Tiers oder Premium-Tiering abonnieren.

Die folgenden APIs wurden geändert und umfassen neue Attributwerte für die neuen Tiering Service-Level:

* Fileservices-APIs
* Block-Store-APIs


Weitere Informationen finden Sie unter den folgenden Links:

* link:nkfsosm_tiering.html["Tiering"]
* link:nkfsosm_performance.html["Performance Service Level"]


====

====


== Funktionen der NetApp Service Engine 2.0.1



=== Unterstützung auch für Cloud Volumes Services für die Google Cloud Platform

Die NetApp Service Engine unterstützt jetzt auch Cloud Volumes Services für die Google Cloud Platform (GCP) und bietet zusätzlich die bestehende Unterstützung für Azure NetApp Files. Sie können nun abonnierte Services verwalten sowie Google Cloud Volumes über die NetApp Service Engine bereitstellen und ändern.


NOTE: Abonnements von Cloud Volumes Services werden außerhalb der NetApp Service Engine gemanagt. Die entsprechenden Zugangsdaten werden an die NetApp Service Engine zur Verfügung gestellt, um die Verbindung zu den Cloud-Services zu ermöglichen.



=== Möglichkeit zum Managen von Objekten, die außerhalb der NetApp Service Engine bereitgestellt werden

Die Volumes (Festplatten und Dateifreigaben), die bereits in der Kundenumgebung vorhanden sind und zu den in der NetApp Service Engine konfigurierten Storage VMs gehören, können jetzt als Teil des NetApp Keystone Flex Subscription (Flex Subscription) angezeigt und gemanagt werden. Die außerhalb der NetApp Service Engine bereitgestellten Volumes sind nun auf den Seiten *Shares* und *Festplatten* mit entsprechenden Statuscodes aufgelistet. Der Hintergrund-Prozess wird in regelmäßigen Abständen ausgeführt und importiert die ausländischen Workloads in Ihrer NetApp Service Engine Instanz.

Die importierten Festplatten und File Shares dürfen sich nicht im gleichen Standard wie die vorhandenen Festplatten und File Shares auf der NetApp Service Engine befinden. Nach dem Import werden diese Festplatten und File Shares mit dem Status `Non-Standard` kategorisiert. Eine Serviceanfrage können Sie bei *Support > Serviceanfrage > Neue Serviceanfrage* richten, damit diese über das Portal der NetApp Service Engine standardisiert und gemanagt werden können.



=== Integration von SnapCenter in die NetApp Service Engine

Durch die Integration von SnapCenter in die NetApp Service Engine können Festplatten und Dateifreigaben nun aus den in Ihrer SnapCenter Umgebung erstellten Snapshots außerhalb der NetApp Service Engine Instanz geklont werden. Beim Klonen einer Dateifreigabe oder -Festplatte aus einem vorhandenen Snapshot im NetApp Service Engine Portal werden die Snapshots Ihrer Auswahl aufgelistet. Ein Erfassungsprozess wird in einem regelmäßigen Intervall im Hintergrund ausgeführt, um die Snapshots in Ihrer NetApp Service Engine Instanz zu importieren.



=== Neuer Bildschirm zur Wartung von Backups

Mit dem neuen *Backup*-Bildschirm können Sie die Backups der in Ihrer Umgebung erstellten Festplatten und File Shares anzeigen und verwalten. Sie können die Backup-Richtlinien bearbeiten, die Backup-Beziehung zum Quell-Volume unterbrechen und das Backup-Volume auch mit allen Recovery-Punkten löschen. Mit dieser Funktion können die Backups (als verwaiste Backups) aufbewahrt werden, auch wenn die Quell-Volumes gelöscht werden. Zur Wiederherstellung einer Dateifreigabe oder eines Datenträgers von einem bestimmten Wiederherstellungspunkt aus können Sie eine Serviceanfrage von *Support > Serviceanfrage > Neue Serviceanfrage* anfordern.



=== Bereitstellung zur Einschränkung des Benutzerzugriffs auf CIFS-Freigaben

Sie können nun die Access Control List (ACL) angeben, um den Benutzerzugriff auf eine CIFS (SMB)- oder Multi-Protokoll-Freigabe zu beschränken. Sie können Windows-Benutzer oder -Gruppen auf Basis der Active Directory (AD)-Einstellungen festlegen, die zur ACL hinzugefügt werden sollen.link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps["Weitere Informationen ."].

====

====


== Funktionen der NetApp Service Engine 2.0



=== MetroCluster Support

Die NetApp Service Engine unterstützt Standorte, die mit MetroCluster-Konfigurationen konfiguriert sind. MetroCluster ist eine Funktion für die Datensicherung von ONTAP, die Recovery Point Objectives (RPO) 0 oder Recovery Time Objectives (RTO) 0 mithilfe von synchronem Spiegel zum kontinuierlich verfügbaren Storage bietet. Die Unterstützung von MetroCluster ermöglicht eine synchrone Disaster Recovery-Funktion innerhalb der NetApp Service Engine. Jede Seite einer MetroCluster Instanz ist als separate Zone registriert, die jeweils über ein eigenes Abonnement verfügt und einen Erweiterten Plan für Datensicherung enthält. In einer MetroCluster-fähigen Zone erstellte Freigaben oder Festplatten replizieren synchron in die zweite Zone. Der Verbrauch der replizierten Zone folgt dem Erweiterten Plan für Datensicherung, der sich auf die Zone beziehen, in der Storage bereitgestellt wird.



=== Unterstützung für Cloud Volumes Services

Die NetApp Service Engine unterstützt jetzt Cloud Volumes Services. Es unterstützt jetzt Azure NetApp Files.


NOTE: Abonnements von Cloud Volumes Services werden außerhalb der NetApp Service Engine gemanagt. Die entsprechenden Zugangsdaten werden an die NetApp Service Engine zur Verfügung gestellt, um die Verbindung zu den Cloud-Services zu ermöglichen.

Die NetApp Service Engine unterstützt:

* Bereitstellung oder Änderung von Cloud Volumes Services Volumes (und Erstellung von Snapshots)
* Daten werden in einer Zone der Cloud Volumes Services gesichert
* Anzeigen von Cloud Volumes Services Volumes im NSE-Inventar
* Anzeigen der Nutzung von Cloud Volumes Services




=== Hostgruppen

Die NetApp Service Engine unterstützt die Verwendung von Host-Gruppen. Eine Host-Gruppe ist eine Gruppe von FC-Protokoll-Host weltweit Port-Namen (WWPNs) oder iSCSI-Host-Node-Namen (IQNs). Sie können Host-Gruppen definieren und sie Festplatten zuordnen, um zu steuern, welche Initiatoren Zugriff auf die Festplatten haben. Hostgruppen ersetzen die Notwendigkeit, für jede Festplatte einzelne Initiatoren anzugeben, und ermöglichen Folgendes:

* Eine zusätzliche Festplatte, die denselben Initiatoren präsentiert werden soll
* Der Satz der Initiatoren über mehrere Festplatten hinweg wird aktualisiert




=== Burst-Nutzung und Benachrichtigungen

Bei einigen von der NetApp Service Engine unterstützten Storage-Abonnements können Kunden einen Burst-Speicherplatz für ihre engagierte Kapazität verwenden, der für die abonnierte Kapazität separat berechnet wird und über der abonnierten Kapazität liegt. Die Benutzer müssen verstehen, wann sie gerade arbeiten oder Burst-Kapazität genutzt haben, um die Nutzung ihrer Nutzung und die Kosten zu kontrollieren.



==== Erfolgt eine Benachrichtigung, wenn eine vorgeschlagene Änderung die Nutzung von Burst-Kapazität zur Folge hat

Eine Benachrichtigung zur Anzeige einer Änderung der vorgeschlagenen Bereitstellung, die zu einem Burst-Anstieg eines Abonnements führt. Der Benutzer kann den Vorgang fortsetzen, da er weiß, dass das Abonnement in den Burst-Wert gesetzt wird oder sich entscheidet, nicht mit der Aktion fortzufahren.link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["Weitere Informationen ."].



==== Benachrichtigung, wenn das Abonnement in Burst ist

Ein Benachrichtigungsbanner wird angezeigt, wenn ein Abonnement in einem Burst steht.link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["Weitere Informationen ."].



==== Der Kapazitätsbericht zeigt die Burst-Nutzung an

Der Kapazitätsbericht zeigt die Anzahl der Tage, die das Abonnement in Burst hatte, und die Menge der verwendeten Burst-Kapazität an.link:sewebiug_working_with_reports.html#capacity-usage["Weitere Informationen ."].



=== Performance-Bericht

In einem neuen Performance-Bericht über die Weboberfläche der NetApp Service Engine werden Informationen zur Performance einzelner Festplatten oder Freigaben zu den folgenden Performance-Kennzahlen angezeigt:

* IOPS/tib (Input/Output Operations per Second per Tebibyte): Die Rate, mit der Input- und Output-Vorgänge pro Sekunde (IOPS) auf dem Storage-Gerät stattfinden.
* Durchsatz in MB/s: Datentransferrate an und von den Storage-Medien in Megabyte pro Sekunde
* Latenz (ms): Die durchschnittliche Zeit für Lese- und Schreibvorgänge von der Festplatte oder Anteil in Millisekunden.




=== Abonnementmanagement

Das Abonnementmanagement wurde verbessert. Sie können jetzt:

* Fordern Sie ein Add-on zur Datensicherheit an, oder fordern Sie zusätzliche Kapazität für ein Add-on zur Datensicherheit für ein Abonnement oder einen Service an
* Anzeige der Datensicherungs-Nutzungskapazität




=== Verbesserung der Abrechnung

Die Abrechnung unterstützt jetzt die Möglichkeit, die Snapshot-Nutzung für ONTAP (Datei- und Block-Storage) zu messen und abzurechnen.



=== Versteckte CIFS-Freigaben

NetApp Service Engine unterstützt das Erstellen verborgener CIFS-Freigaben.
