---
sidebar: sidebar 
permalink: seapiref_ontap_clusters.html 
keywords:  
summary:  
---
= ONTAP Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden, um ONTAP Cluster abzurufen, zu erstellen, zu ändern und zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/ontapclusters` | Rufen Sie alle ONTAP Cluster ab. 


| `GET` | `/v2.1/ontapclusters/{id}` | Rufen Sie ein ONTAP-Cluster anhand der ID ab. 


| `POST` | `/v2.1/ontapclusters` | Erstellen Sie einen neuen ONTAP-Cluster. 


| `PUT` | `/v2.1/ontapclusters/{id}` | Aktualisieren der ONTAP-Cluster-Bestandsaufnahme anhand der ID 


| `DELETE` | `/v2.1/ontapclusters/{id}` | Löschen eines ONTAP-Clusters. 
|===


=== Attribute für ONTAP Cluster

In der folgenden Tabelle werden die ONTAP-Cluster-Attribute aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung des ONTAP-Clusters 


| `Name` | Zeichenfolge | Der ONTAP Cluster-Name. 


| `UUID` | Zeichenfolge | Die ONTAP-Cluster-Universal-Unique-ID (UUID). 


| `mManagement_ip` | Zeichenfolge | Die ONTAP-Cluster-Management-IPv4-Adresse. 


| `username` | Zeichenfolge | Der ONTAP Cluster-Name 


| `password` | Zeichenfolge | Das ONTAP-Cluster-Passwort 


| `Provisioning_State` | Zeichenfolge  a| 
Identifiziert, ob ein Cluster für Bereitstellungsvorgänge verfügbar ist Folgende Optionen stehen zur Verfügung:

* Offen
* Geschlossen




| `Data_Network_ip_cidr` | Zeichenfolge | Die CIDR-Notation eines Subnetzes. 


| `Data_Network_default_Gateway` | Zeichenfolge | DIE IPV4-Adresse. 


| `Data_Network_Ports` | –  a| 
Eine Liste der ONTAP Cluster-Datennetzwerkports.

[listing]
----
For example:
[
  {
  "node_name": "dev-ots-per01-01",
  "port_name": "e0c-120",
  "parent_port": "e0c"
  }
]
----


| `intercluster_lifs` | –  a| 
Das ONTAP Cluster Intercluster LIFs.

[listing]
----
For example:
[
  {
  "name": "peer1",
  "node": "aff-01",
  "port": "a0a-103",
  "address": "10.128.113.232",
  "netmask": "255.255.255.0"
  },
{
  "name": "peer2",
  "node": "aff-02",
  "port": "a0a-103",
  "address": "10.128.113.233",
  "netmask": "255.255.255.0"
  }
]
----


| `svm_root_Service_Level` | Zeichenfolge | Der Root-Service-Level-Name der ONTAP Cluster Storage Virtual Machine (SVM) Gültige Werte sind Standard, Extreme oder Premium. Diesem Service-Level werden standardmäßig alle unter dem Cluster erstellten SVMs zugewiesen. Dem Cluster sollte ein zugefasster Aggregat für das erwähnte Service-Level zugeordnet sein. 


| `Zone` | Zeichenfolge | Der Zonenname. 


| `subskription_number` | Zeichenfolge | Das Zuora Abonnement. 


| `services_available` | –  a| 
Liste der verfügbaren Services und ihres Status. Beispiel:

[listing]
----
{
  "fcp": false,
  "iscsi": true,
  "nas": true
  }
----


| `Data_fcp_Ports` | –  a| 
Liste der Nodes und Ports für FCP-fähige ONTAP Cluster Beispiel:

[listing]
----
[  {   "node_name": "aff-01",   "port_name": "0g"  },  {   "node_name": "aff-01",   "port_name": "0h"
  ]
----


| `IS_mcc` | Boolesch | Gibt an, ob das Cluster MetroCluster aktiviert ist oder nicht. Der Standardwert ist falsch. 


| `mcc_Partner_Cluster` | Zeichenfolge | Die Kennung des Partner-Clusters des aktuellen Clusters in einem MetroCluster-Paar. Erforderlich, wenn das Cluster für MetroCluster aktiviert ist. 
|===


=== Rufen Sie alle ONTAP Cluster ab

Verwenden Sie die im Folgenden aufgeführte Methode zum Abrufen aller ONTAP Cluster oder einer Untermenge an ONTAP Clustern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/ontapclusters` | Rufen Sie alle ONTAP Cluster ab. | `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 2,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": []
      },
      {
        "id": "5eaf5249f038943eb46b6608",
        "name": "aff",
        "region": "au-east1",
        "zone": "au-east1-b",
        "uuid": "62d649d2-07a1-11e6-9549-00a0985c0dcb",
        "management_ip": "10.128.113.69",
        "username": "admin",
        "services_available": {
          "fcp": true,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "aff-01",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          },
          {
            "node_name": "aff-02",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          }
        ],
        "data_network_ip_cidr": "10.50.50.0/24",
        "data_network_default_gateway": "10.50.50.1",
        "svm_root_service_level": "premium",
        "intercluster_lifs": [
          {
            "name": "peer1",
            "node": "aff-01",
            "port": "a0a-103",
            "address": "10.128.113.232",
            "netmask": "255.255.255.0"
          },
          {
            "name": "peer2",
            "node": "aff-02",
            "port": "a0a-103",
            "address": "10.128.113.233",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00004635",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [
          {
            "node_name": "aff-01",
            "port_name": "0g"
          },
          {
            "node_name": "aff-01",
            "port_name": "0h"
          },
          {
            "node_name": "aff-02",
            "port_name": "0g"
          },
          {
            "node_name": "aff-02",
            "port_name": "0h"
          }
        ],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== Abrufen von ONTAP Clustern nach ID

Verwenden Sie die im Folgenden aufgeführte Methode, um ONTAP Cluster nach ID abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/ontapclusters/{id}` | Rufen Sie die ONTAP-Cluster ab, die anhand der ID ermittelt wurden. | `id (String)`: Die eindeutige Kennung des ONTAP-Clusters. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== ONTAP Cluster erstellen

Verwenden Sie die API in der folgenden Tabelle, um ein ONTAP-Cluster zu erstellen.

ONTAP-Cluster werden immer erstellt, wenn der iSCSI-Service aktiviert ist. Optional kann der FCP-Service aktiviert werden, wenn die Infrastruktur den Service unterstützt.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/ontapclusters` | Erstellen eines ONTAP Clusters | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `UUID, Management_ip`, `username`, `password`, `Data_Network_ip_cidr`, `data_Network_default_Gateway`, `intercluster_lifs`, `Zone`

Wenn FCP aktiviert ist (mit dem Attribut `services_available` FCP), sind die `data_fcp_Ports `erforderlich.

Wenn `is_mcc` TRUE ist, ist der `mcc_Partner_Cluster` erforderlich.

*Beispiel des Körpers anfordern:*

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "clustername-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "clustername-01-icl01",
      "node": "clustername-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "extreme",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": true
  },
  "data_fcp_ports": [
  ],
  "is_mcc": false,
}
....
*Beispiel des Antwortkörpers:*

....
{
    "status": {
        "user_message": "Okay. New resource created.",
        "verbose_message": "",
        "code": 201
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "clustername-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "extreme",
                "intercluster_lifs": [
                    {
                        "name": "clustername-01-icl01",
                        "node": "clustername-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== ONTAP-Cluster ändern

Verwenden Sie die im Folgenden aufgeführte Methode, um den ONTAP-Cluster zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/ontapclusters/{id}` | Ändern Sie die Details des ONTAP Clusters, der anhand der ID ermittelt wurde. | `id (String)`: Die eindeutige Kennung des ONTAP-Clusters. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "dev-ots-syd01-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "dev-ots-syd01-01-icl01",
      "node": "dev-ots-syd01-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "standard",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": false
  },
  "data_fcp_ports": [
  ]
}
....
*Beispiel des Antwortkörpers:*

....
{
    "status": {
        "user_message": "Okay. Accepted for processing.",
        "verbose_message": "",
        "code": 202
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "dev-ots-syd01-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "standard",
                "intercluster_lifs": [
                    {
                        "name": "dev-ots-syd01-01-icl01",
                        "node": "dev-ots-syd01-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== Löschen eines ONTAP-Clusters

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Löschen eines ONTAP-Clusters.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `DELETE` | `/v2.1/ontapclusters/{id}` | Löschen Sie den ONTAP-Cluster, der anhand der ID identifiziert wurde. | `id (String)`: Die eindeutige Kennung des ONTAP-Clusters. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
No content for succesful delete
....