---
sidebar: sidebar 
permalink: seapiref_subnets_apis.html 
keywords: netapp, keystone, subnets, networks, apis 
summary: Keystone Netzwerk-APIs 
---
= Netzwerkkonfigurationen mit Subnets APIs definieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mithilfe von Subnetzen-APIs können Sie Subnetze für Untermandanten und Zonen anzeigen und erstellen. Sie können sie zur Definition Ihrer Netzwerkkonfiguration verwenden.

[cols="1,1,3,2"]
|===
| HTTP-Verb | Pfad | Beschreibung | Obligatorische Parameter/Anforderungskörper 


 a| 
`GET`
 a| 
`/v2.1/Tenants/{Tenant_id}/` `Zones/{Zone_Name}/Subnets`
| Sie können alle Subnetz-Objekte für einen Mandanten und eine Zone abrufen. Ruft Details des Subnetzes ab, wie VLAN, Submandant, Zone, Routen, Und Tags.  a| 
`Tenant_id`: Die ID des Mandanten. `Zone_Name`: Der Name der Zone. `Offset`: Die Anzahl der zu übersprinenden Elemente, bevor der Ergebnissatz erfasst wird. `Limit`: Die Anzahl der zurückzukehrenden Artikel.



 a| 
`GET`
 a| 
`/v2.1/Tenants/{Tenant_id}/` `Zones/{Zone_Name}/Subnets/` `{id}`
| Sie können die Details zu einem bestimmten Subnetz-Objekt abrufen, das für einen Mandanten und eine Zone erstellt wurde. Ruft Details des Subnetzes ab, wie VLAN, Submandant, Zone, Routen, Und Tags basierend auf der eingegebenen ID.  a| 
`Tenant_id`: Die ID des Mandanten. `Zone_Name`: Der Name der Zone. `id`: Die ID des Subnetzes.



 a| 
`POST`
 a| 
`/v2.1/Tenants/{Tenant_id}/` `Zones/{Zone_Name}/Subnets`
| Sie können ein Subnetz-Objekt für einen bestimmten Mandanten und eine bestimmte Zone erstellen. Fügen Sie die Werte im Anfragetext hinzu, um ein Untermandant-Objekt mit den angegebenen Parametern zu erstellen, z. B. Name, VLAN, CIDR, Untermandant-ID, Routen und Tags.  a| 
`Tenant_id`: Die ID des Mandanten. `Zone_Name`: Der Name der Zone. `` { "Name": "String", "vlan": "1000", "cidr": "10.0.0.0/24", "Subtenant_id": "5d2fb0f4f47df00015274e3", "Routen": [ { "Ziel": "10.0.0.0/24", "10.0 Schlüsselwert": "Keyn", "Schlüsselwert" } } ``": "Schlüsselwert": "1" 0.1." }" 20 {



 a| 
`POST`
 a| 
`/v2.1/Tenants/{Tenant_id}/` `Zones/{Zone_Name}/Subnets/` `{id}/Tags`
| Sie können Tags für ein Subnetz-Objekt für Ihren Mandanten erstellen oder ersetzen. Fügen Sie die ID des Subnet-Objekts und die Werte für die Tags im Format „Key:value Pair“ im Anforderungsobjekt hinzu.  a| 
`Tenant_id`: Die ID des Mandanten. `Zone_Name`: Der Name der Zone. `id`: Die ID des Backup-Objekts. `` { „key1“: „<Tag 1>“, „key2“: „<Tag 2>“, „Schlüssel“: „<Tag N>“ } ``

|===