---
sidebar: sidebar 
permalink: seapiref_backups_apis.html 
keywords: netapp, keystone, backups, apis, 
summary: Keystone Backup-APIs 
---
= Backup-APIs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit Backup-APIs können Snapshots (Backups oder Recovery-Punkte) der Volumes (Dateifreigaben und Festplatten) in der Systemumgebung angezeigt und gemanagt werden.

[cols="1,1,3,2"]
|===
| HTTP-Verb | Pfad | Beschreibung | Obligatorische Parameter/Anforderungskörper 


 a| 
`GET`
 a| 
`/v2.1/Backups`
| Sie können die Details aller Backup-Objekte für alle Volumes abrufen, die unter dem Mandanten erstellt wurden. Abrufen von Details zum Quell-Volume und zum Backup-Objekt, z. B. Backup-Richtlinien, Zone und Tags.  a| 
`Offset`: Die Anzahl der zu übersprinenden Elemente, bevor der Ergebnissatz erfasst wird. `Limit`: Die Anzahl der zurückzukehrenden Artikel.



 a| 
`GET`
 a| 
`/v2.1/Backups/{id}`
| Sie können die Details zu einem bestimmten Backup-Objekt abrufen, das für ein Volume für den Untermandanten unter dem Mandanten erstellt wurde. Abrufen von Details des Quell-Volumes und des Backup-Objekts, z. B. Backup-Richtlinien, Zone und Tags, basierend auf der eingegebenen ID  a| 
`id`: Die ID des Backup-Objekts.



 a| 
`GET`
 a| 
`/v2.1/Backups/{id}/` `recovery_Points`
| Sie können Details zu allen Recovery-Punkten eines bestimmten Backup-Objekts abrufen. Details wie Zeitstempel und Name werden abgerufen.  a| 
`id`: Die ID des Backup-Objekts.



 a| 
`GET`
 a| 
`/v2.1/Backups/{id}/` `recovery_Points/{Name}`
| Sie können Details zu jedem Recovery-Punkt eines bestimmten Backup-Objekts abrufen. Details wie Zeitstempel und Name werden abgerufen.  a| 
`id`: Die ID des Backup-Objekts. `Name`: Der Name des Wiederherstellungspunkts.



 a| 
`POST`
 a| 
`/v2.1/Backups`
| Sie können ein Backup-Objekt für ein bestimmtes Quell-Volume erstellen. Fügen Sie die Werte im Anfraentext hinzu, um ein Backupobjekt mit den angegebenen Parametern zu erstellen, z. B. Backup-Policy, Anzahl der zu behaltenden Backupkopien und Quell-Ressourcen-ID.  a| 
`` { „primary_Resource_type“: „<Resource Type>“, „source_Resource_id“: „<ID>“, „Backup_Zone“: „<Backup Zone>“, „Backup_Policy“: { „Daily_Backups_to_keep“: <Anzahl der täglichen Backups, die beibehalten werden sollen>, „Weekly_Backups_to_keyc“: „ } keyc_keyN“, „ <Tag für <{“, „<-Schlüsselnummer: „<“, „<_keyoc_keyc-Tag“, „-Nummer“, „-Tag“, „-Anzahl der täglichen Backups: „-Tag“, „-Anzahl der täglichen Sicherungen: „-Tag“, „-Nummer“, „-Nummer der täglichen Sicherungen: „-Tag-Nummer „<Tag N>“ } } ``



 a| 
`POST`
 a| 
`/v2.1/Backups/{id}/Tags`
| Sie können Tags für ein Backup-Objekt für den Untermandanten erstellen oder ersetzen. Fügen Sie die ID des Backupobjekts und die Werte für die Tags im Format „Key:value Pair“ im Anforderungskörper hinzu.  a| 
`id`: Die ID des Backup-Objekts. `` { „key1“: „<Tag 1>“, „key2“: „<Tag 2>“, „Schlüssel“: „<Tag N>“ } ``



 a| 
`PATCH`
 a| 
`/v2.1/Backups/{id}`
 a| 
Sie können jedes Backup-Objekt für ein Volume basierend auf seiner ID ändern. Fügen Sie die ID des Backupobjekts und die Werte hinzu, die Sie im Anfraentext ändern möchten, z. B. die Details der Sicherungsrichtlinie, die Anzahl der zu behaltenden Backups und die Quellenressourcen-ID.

[NOTE]
====
Sie können ein Backupobjekt verwaist machen, indem Sie in Ihrer `PATCH`-Anforderung den Wert des Parameters `source_Resource_id` als null festlegen. Dadurch wurde die SnapMirror Beziehung entfernt, doch das Backup-Volume und die darin erstellten Recovery-Punkte bleiben erhalten.

==== a| 
`id`: Die ID des Backup-Objekts. `` { „source_Resource_id“: „<Resource ID>“, „Backup_Policy“: { „Daily_Backups_to_keep“: <Anzahl der täglichen zu bewahrenden Backups>, „Weekly_Backups_to_keep“: <Anzahl der wöchentlichen Backups, die beibehalten werden sollen> <keyoc_Backups_to_keep“: <}<keyoc { Tag: „ 3“, „<Tag 2“, „ } } `` keyoc_Backups> „<“, „ Tag: „“, „> „keyoc_Backup_to_keyoc_to_keyoc_keyoc_keyloc_keep“: „“, „“, „ Tag: „



 a| 
`DELETE`
 a| 
`/v2.1/Backups/{id}`
| Sie können jedes beliebige Backup-Objekt zusammen mit allen Recovery-Punkten für ein Volume löschen.  a| 
`id`: Die ID des Backup-Objekts.



 a| 
`DELETE`
 a| 
`/v2.1/Backups/{id}/` `recovery_Points/{Name}`
| Sie können jeden beliebigen Recovery-Punkt in einem bestimmten Backup-Objekt für ein Volume löschen.  a| 
`id`: Die ID des Backup-Objekts. `Name`: Der Name des Wiederherstellungspunkts.

|===