---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Keystone Service-Anfragen 
---
= Service-Anfragen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden zum Erstellen und Abrufen von Service-Anforderungen.

|===


| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/Tenants/{Tenant_id}/servicerequests` | Abrufen von Service-Anfragen. 


| `GET` | `/v2.1/Tenants/{Tenant_id}/servicerequests/{id}` | Service-Anfrage nach ID abrufen. 


| `POST` | `/v2.1/Tenants/{Tenant_id}/servicerequests/` | Erstellen einer Serviceanfrage. 


| `GET` | `/v2.1/Tenants/{Tenant_id}/servicerequests/categories` | Service-Request-Kategorien abrufen. 
|===


== Attribute für Serviceanfrage

In der folgenden Tabelle sind die Attribute für Serviceanfragen aufgeführt.

|===


| Attribut | Typ | Beschreibung 


| `Id` | Zeichenfolge | Eine Kennung für die Serviceanforderung. Zum Beispiel: `s RRQ0035952014.` 


| `sSubject` | Zeichenfolge | Gegenstand der Serviceanfrage. 


| `comment` | Zeichenfolge | Eine Anmerkung zur Serviceanfrage 


| `category` | Zeichenfolge | Die Kategorie der Anfrage: Backup, Disaster Recovery, Technik, sonstige oder Abonnement. 


| `Priorität` | Zeichenfolge | Die Priorität der Service-Anfrage: Sehr niedrig, niedrig, normal, hoch oder dringend. 


| `sSubskription` | Zeichenfolge | Die Zuora-Abonnementnummer. 


| `Engagement` | –  a| 
Einzelheiten zum Abonnement, darunter:

* Service Level (String): Service-Level: Standard, Premium oder Extreme.
* New_Commitment (integer): Neue Gesamtkapazität erforderlich.




| `Zone` | Zeichenfolge | Der Zonenname. 


| `subTenant_id` | Zeichenfolge | Die Submandant-ID. 


| `storage_object_type` | Zeichenfolge | Storage-Objekttyp: File-Server oder Block-Store 


| `storage_object_id` | Zeichenfolge | Die Kennung des Speicherobjekts. Beispiel: `5d2fb0fb4f47df00015274e3` 


| `sService_type` | Zeichenfolge | Der Servicetyp: File Services, Block-Storage oder Objekt-Storage. 
|===


== Abrufen von Service-Anfragen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen der Service-Request-Kategorien für den angegebenen Mandanten.

|===


| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET`` | `/v2.1/Tenants/{Tenant_id}/servicerequests` | Abrufen von Service-Anfragen. | `Tenant_id`: (Optional) gibt die Serviceanforderungen für den angegebenen Mandanten zurück. `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Service-Anfrage nach ID abrufen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Serviceanfrage nach Service-Request-ID abzurufen.

|===


| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Tenants/{Tenant_id}/servicerequests/{id}` | Service-Anfrage nach ID abrufen.  a| 
* `Tenant_id`: Mandanten-ID
* `id`: Service Request IDFür Beispiel: SRQ0035952014


|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Erstellen einer Serviceanfrage

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Erstellen einer Service-Anforderung.

|===


| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/Tenants/{Tenant_id}/servicerequests/categories` | Erstellen einer Serviceanfrage. | `tenant_id`: Die Mieter-ID. 
|===
Erforderliche Body-Attribute der Anforderung: Die erforderlichen Attribute sind abhängig von der Kategorie der Service-Anforderung. In der folgenden Tabelle sind die Attribute für den Anfraentext aufgeführt.

|===


| Kategorie | Erforderlich 


| Abonnement | `subscription` Und `commitment` 


| Disaster Recovery | `storage_object_type`, `subtenant_id`, und `storage_object_id` 


| Technik | `subtenant_id` Und `service_type`Wenn `service_type` Ist File Services oder Block-Storage, Zone ist erforderlich. 


| Andere | Zone 
|===
*Beispiel des Körpers anfordern:*

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== Service-Request-Kategorien abrufen

In der folgenden Tabelle sind die Kategorien für Service-Anfragen für einen bestimmten Mandanten aufgeführt.

|===


| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Tenants/{Tenant_id}/servicerequests/categories` | Abrufen der Kategorien von Service-Anfragen. | `tenant_id:` (Optional) gibt die Serviceanforderungen für einen bestimmten Mandanten zurück. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....