---
sidebar: sidebar 
permalink: seapiref_tenants.html 
keywords: netapp, keystone, tenants, 
summary: Keystone Mandanten 
---
= Mandanten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nutzen Sie die in der folgenden Tabelle aufgeführten Methoden zum Abrufen, Erstellen, Ändern und Löschen von Mandanten.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/Tenants` | Rufen Sie eine Liste aller Mandanten ab. 


| `GET` | `/v2.1/Tenants/{id}` | Rufen Sie einen Mandanten über die Mandanten-ID ab. 


| `POST` | `/v2.1/Tenants` | Erstellen Sie einen neuen Mandanten. 


| `PUT` | `/v2.1/Tenants/{id}` | Ändern Sie die Details eines Mandanten. 


| `DELETE` | `/v2.1/Tenants/{id}` | Löschen Sie einen Mandanten. 
|===


=== Mandantenattribute

In der folgenden Tabelle werden die Mandantenattribute aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung des Mandanten. 


| `Code` | Zeichenfolge | Ein vom Kunden angegebener (oder standardmäßiger) Code, der den Mandanten darstellt. Dieses Attribut kann Kleinbuchstaben, Zahlen und Unterstriche enthalten. 


| `Name` | Zeichenfolge | Der Mandantenname. 


| `zuora_Account_Name` | Zeichenfolge | Der Name des Rechnungskontos: Der Name des Abonnements in Zuora. 


| `zuora_Account_number` | Zeichenfolge | Die Rechnungsnummer: Die Abonnementnummer in Zuora. 


| `DBeschreibung` | Zeichenfolge | Die Beschreibung des Mieters. 


| `Nutzung` | – | Die Services und Service-Details für den Mandanten. Für jedes Service Level wird mit diesem Attribut Folgendes angezeigt: *Name:* Service Level Name *used_size_gb:* Service Level Name *Role_Name:* Benutzerrolle (Benutzer, Admin, Lesen, Partner oder Root) 
|===


=== Rufen Sie alle Mandanten ab

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen aller Mandanten oder einer Untermenge aller Mandanten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Tenants` | Rufen Sie alle Mandanten ab. | `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 23,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [
      {
        "id": "5e7c3af7aab46c00014ce877",
        "name": "MyTenant",
        "zuora_account_name": "MyAccount",
        "zuora_account_number": "A00000415",
        "description": "",
        "code": "mytenantcode",
        "usage": {
          "A-S00003875": [
            {
              "service_level": "extreme",
              "consumed": 0,
              "committed": 10,
              "burst": 0
            },
            {
              "service_level": "standard",
              "consumed": 1.94,
              "committed": 30,
              "burst": 0
            }
          ],
          "A-S00004566": [
            {
              "service_level": "object",
              "consumed": 3.31,
              "committed": 300,
              "burst": 0
            }
          ]
        }
      },
      {
        "id": "5d914499869caefed0f39eee",
        "name": "MyOrg",
        "zuora_account_name": "MyOrg Inc",
        "zuora_account_number": "A00000415",
        "description": "",
        "code": "myorg",
        "usage": {
          "A-S00003875": [
            {
              "service_level": "standard",
              "consumed": 12.33,
              "committed": 30,
              "burst": 0
            },
            {
              "service_level": "object",
              "consumed": 0,
              "committed": 40,
              "burst": 0
            }
          ],
          "A-S00003969": [
            {
              "service_level": "extreme",
              "consumed": 0,
              "committed": 5,
              "burst": 0
            }
          ]
        }
      }
    ]
  }
}
....


=== Einen Mandanten per ID abrufen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen Mandanten nach ID abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Tenants/{id}` | Rufen Sie den von der ID angegebenen Mandanten ab. | `id (String)`: Die eindeutige Kennung des Mandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

Beispiel für den Anforderungskörper:

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af7aab46c00014ce877",
        "name": "MyTenant",
        "zuora_account_name": "MyAccount",
        "zuora_account_number": "A00000415",
        "description": "",
        "code": "mytenantcode",
        "usage": {
          "A-S00003875": [
            {
              "service_level": "extreme",
              "consumed": 0,
              "committed": 10,
              "burst": 0
            },
            {
              "service_level": "premium",
              "consumed": 2.4,
              "committed": 20,
              "burst": 0
            },
            {
              "service_level": "standard",
              "consumed": 1.94,
              "committed": 30,
              "burst": 0
            },
            {
              "service_level": "object",
              "consumed": 0,
              "committed": 40,
              "burst": 0
            }
          ],
          "A-S00003969": [
            {
              "service_level": "extreme",
              "consumed": 0,
              "committed": 5,
              "burst": 0
            },
            {
              "service_level": "standard",
              "consumed": 0,
              "committed": 30,
              "burst": 0
            }
          ],
          "A-S00004566": [
            {
              "service_level": "object",
              "consumed": 3.31,
              "committed": 300,
              "burst": 0
            }
          ]
        }
      }
    ]
  }
}
....


=== Erstellen eines Mandanten

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Erstellen eines Mandanten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/Tenants` | Erstellen Sie einen neuen Mandanten. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Code`, `Name`, `zuora_Account_Name`, `zuora_Account_number`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyNewTenant",
  "code": "mytenant",
  "zuora_account_name": "string",
  "zuora_account_number": "A00000415",
  "description": "DescriptionOfMyTenant"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5ac802c356a0001a735af",
        "name": "MyNewTenant",
        "zuora_account_name": "string",
        "zuora_account_number": "A00000415",
        "description": "DescriptionOfMyTenant",
        "code": "mytenant",
        "usage": null
      }
    ]
  }
}
....


=== Ändern Sie den Mandanten

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um den Mandanten zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/Tenants/{id}` | Ändern Sie den mit der ID angegebenen Mandanten. Sie können den Namen, die Zuora-Abonnementdetails (Kontoname oder Abonnementnummer) und die Beschreibung des Mieters ändern. | `id (String)`: Die eindeutige Kennung des Mandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `Code`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyNewTenant",
  "code": "mytenant",
  "zuora_account_name": "string",
  "zuora_account_number": "A00000415",
  "description": "New description of my tenant"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5ac802c356a0001a735af",
        "name": "MyNewTenant",
        "zuora_account_name": "string",
        "zuora_account_number": "A00000415",
        "description": "New description of my tenant",
        "code": "mytenant",
        "usage": null
      }
    ]
  }
}
....


=== Löschen Sie den Mandanten

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Löschen des Mandanten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `DELETE` | `/v2.1/Tenants/{id}` | Löschen Sie den mit der ID angegebenen Mandanten. | `id (String)`: Die eindeutige Kennung des Mandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
No content for successful delete
....