---
sidebar: sidebar 
permalink: seapiref_object_storage_apis.html 
keywords: netapp, keystone, object, storage, apis, 
summary: Keystone Objekt-Storage-APIs 
---
= Objekt-Storage-APIs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt werden APIs zum Managen von Objekt-Storage, Objekt-Storage-Benutzern und Objekt-Storage-Gruppen bereitgestellt.

Der Objekt-Storage-Workflow umfasst die folgenden Aufgaben:

* Erstellen eines Objekt-Storage-Kontos
* Erstellen Sie eine Objekt-Storage-Gruppe.
* Erstellen Sie einen Objekt-Storage-Benutzer.
* Erstellen eines S3-Schlüssels für Benutzer




== Objekt-Storage-Gruppen

Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden zum Abrufen, Erstellen oder Ändern von Objekt-Storage-Gruppen.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/objectiam/groups` | Abrufen von Objekt-Storage-Gruppen 


| `GET` | `/v2.1/objectiam/groups/{id}` | Abrufen einer Objekt-Storage-Gruppe nach ID 


| `POST` | `/v2.1/objectiam/groups` | Erstellen Sie eine Objekt-Storage-Identitätszugriffsmanagement-Gruppe. 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Ändern Sie eine anhand der ID identifizierte Objektspeichergruppe. 


| `DELETE` | `/v2.1/objectiam/groups/{id}` | Löschen Sie eine anhand der ID angegebene Objekt-Speichergruppe. 
|===


=== Attribute für Objekt-Storage-Gruppen

In der folgenden Tabelle werden die Attribute des Objekt-Storage aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung für die Objektspeichergruppe. 


| `Name` | Zeichenfolge | Der Name der Objekt-Storage-Gruppe. 


| `subTenant` | Zeichenfolge | Der Name des Untermandanten, zu dem die Gruppe gehört. 


| `subTenant_id` | Zeichenfolge | Die Kennung für den Untermandanten, zu dem die Gruppe gehört. 


| `Mandant` | Zeichenfolge | Der Name des Mandanten, zu dem die Gruppe gehört. 


| `Tenant_id` | Zeichenfolge | Die Kennung für den Mandanten, zu dem die Gruppe gehört. 


| `s 3_Policy` |   a| 
S3-Richtlinie beispielsweise:

[listing]
----
"s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
----
|===


=== Abrufen von Objekt-Storage-Gruppen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen aller Objekt-Storage-Gruppen oder einer Untermenge an Objekt-Storage-Gruppen. Wenn Sie eine `subTenant_id` angeben, werden nur die zu diesem Untermandant gehörenden Objekt-Speichergruppen zurückgegeben.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/groups` | Abrufen aller Objekt-Storage-Gruppen Geben Sie optional eine Untermandant-ID an, um nur die dem Untermandanten zugeordneten Objekt-Storage-Gruppen abzurufen. | `subTenant_id (string)`: Die Submandant-ID, die mit den IAM-Benutzern/Gruppen (Identity and Access Management) verknüpft ist. `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]

....


=== Abrufen einer Objekt-Storage-Gruppe nach ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Objekt-Storage-Gruppe nach ID abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/groups/{id}` | Abrufen einer Objekt-Storage-Gruppe nach ID | `id (String)`: Die eindeutige Kennung der Objekt-Speichergruppe. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


=== Erstellen Sie eine Objekt-Storage-Gruppe

Verwenden Sie die im Folgenden aufgeführte Methode zum Erstellen einer Objekt-Speichergruppe.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/objectiam/groups/` | Erstellen Sie einen neuen Objekt-Storage-Gruppenservice, um Objekt-Storage-Benutzer zu hosten. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `subtenant_id`, `s3Policy`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyNewGroup",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fa312c356a0001a73841",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T07:05:21.130260774Z",
        "updated": "2020-06-02T07:05:21.130260774Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Ändern einer Objektspeichergruppe

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Objekt-Speichergruppe zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Ändern einer Objektspeichergruppe. | `id (String)`: Die eindeutige Kennung der Objekt-Speichergruppe. 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `subtenant_id`, `s3Policy`

*Beispiel des Körpers anfordern:*

....
{
  "s3_policy": {
    "Statement": [
        {
        "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:GetObject",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionTagging"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::*"
        }
    ]
  }
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fe822c356a0001a73859",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:23:46.43550235Z",
        "updated": "2020-06-02T07:23:46.43550235Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Löschen Sie eine Objekt-Storage-Gruppe nach ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Objekt-Storage-Gruppe nach ID zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `Delete` | `/v2.1/objectiam/groups/{id}` | Löschen Sie eine Objekt-Storage-Gruppe nach ID. | `id (String)`: Die eindeutige Kennung der Objekt-Speichergruppe. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


== Objekt-Storage-Benutzer

Führen Sie die folgenden Aufgaben mithilfe der in der folgenden Tabelle aufgeführten Methoden aus:

* Abrufen, Erstellen oder Ändern von Objekt-Storage-Benutzern
* S3-Schlüssel erstellen, S3-Schlüssel für Benutzer abrufen oder Schlüssel nach Schlüssel-ID abrufen


|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/objectiam/users` | Abrufen von Objekt-Storage-Benutzern 


| `GET` | `/v2.1/objectiam/users/{id}` | Abrufen eines Objekt-Storage-Benutzers anhand der ID 


| `POST` | `/v2.1/objectiam/users` | Erstellen Sie einen Objekt-Storage-Benutzer. 


| `PUT` | `/v2.1/objectiam/users/{id}` | Ändern Sie einen anhand der ID angegebenen Objekt-Storage-Benutzer. 


| `DELETE` | `/v2.1/objectiam/users/{id}` | Löschen Sie einen Objekt-Storage-Benutzer anhand der ID. 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Erhalten Sie alle S3-Schlüssel einem Benutzer zugeordnet. 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Erstellung von S3-Schlüsseln 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | S3-Schlüssel per Schlüssel-ID abrufen. 


| `DELETE` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Löschen von S3-Schlüsseln anhand der Schlüssel-ID. 
|===


=== Benutzerattribute für Objekt-Storage

In der folgenden Tabelle werden die Attribute des Objekt-Storage-Benutzers aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung für den Objekt-Storage-Benutzer. 


| `Display_Name` | Zeichenfolge | Der Anzeigename des Benutzers. 


| `subTenant` | Zeichenfolge | Der Name des Submandanten, zu dem der Benutzer gehört. 


| `subTenant_id` | Zeichenfolge | Die Kennung für den Untermandanten, zu dem der Benutzer gehört. 


| `Mandant` | Zeichenfolge | Der Name des Mandanten, zu dem der Benutzer gehört. 


| `Tenant_id` | Zeichenfolge | Die Kennung für den Mandanten, zu dem der Benutzer gehört. 


| `objectiam_user_urn` | Zeichenfolge | Der URN. 


| `sg_Group_Membership` | Zeichenfolge | NetApp StorageGRID-Gruppenmitgliedschaften Zum Beispiel: "sg_Group_Membership": [ "5d2fb0fb4f47df00015274e3" ] 
|===


=== Abrufen von Objekt-Storage-Benutzern

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen aller Benutzer für Objekt-Storage oder einer Untermenge an Objekt-Storage-Benutzern. Wenn Sie eine `subTenant_id` angeben, werden nur die zu diesem Untermandant gehörenden Objekt-Speichergruppen zurückgegeben.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/users` | Rufen Sie alle Objekt-Storage-Benutzer ab. | `subTenant_id (string)`: Die dem IAM-Benutzer/Gruppen zugeordnete Untermandant-ID. `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Abrufen eines Objekt-Storage-Benutzers anhand der ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen anhand der ID verwendeten Objekt-Storage abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/users{id}` | Abrufen eines Objekt-Storage-Benutzers anhand der ID | `id`: Die Objekt-Storage-Konto-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Erstellen Sie einen Objekt-Storage-Benutzer

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Erstellen eines Objekt-Storage-Benutzers.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/objectiam/users` | Erstellen Sie einen neuen Objekt-Storage-Benutzer. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Display_Name`, `subtenant_id`, `sg_Group_Membership`

*Beispiel des Körpers anfordern:*

....
{
  "display_name": "MyUserName",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "sg_group_membership": [
    "5ed5fa312c356a0001a73840"
  ]
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed603712c356a0001a7386c",
        "action": "create",
        "job_summary": "Activate request is successfully submitted",
        "created": "2020-06-02T07:44:49.647815816Z",
        "updated": "2020-06-02T07:44:49.647815816Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Ändern eines Objektspeicherbenutzers

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen Objekt-Storage-Benutzer zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/objectiam/users/{id}` | Ändern Sie einen anhand der ID angegebenen Objekt-Storage-Benutzer. | `id`: Die Objekt-Storage-Benutzer-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `Display_Name`, `subtenant_id`, `sg_Group_Membership`

*Beispiel des Körpers anfordern:*

....
{
  "display_name": "MyModifiedObjectStorageUser",
  "subtenant_id": "5e57a465896bd80001dd4961",
  "sg_group_membership": [
    "5e60754f9b64790001fe937b"
  ]
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed604002c356a0001a73880",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:47:12.205889873Z",
        "updated": "2020-06-02T07:47:12.205889873Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Ordnen Sie alle S3-Schlüssel einem Objekt-Storage-Benutzer zu

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um alle S3-Schlüssel einem Objekt-Storage-Benutzer zuzuordnen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Erstellen eines S3-Schlüssels für einen Objekt-Storage-Benutzer | `user_id (string)`: Die Objekt-Storage-Benutzer-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z"
      }
    ]
....


=== Erstellen eines S3-Schlüssels für einen Objekt-Storage-Benutzer

Verwenden Sie die im Folgenden aufgeführte Methode, um einen S3-Schlüssel für einen Objekt-Storage-Benutzer zu erstellen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Erstellen eines S3-Schlüssels für einen Objekt-Storage-Benutzer | `user_id (string)`: Die Objekt-Storage-Benutzer-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `Expires` (String)


NOTE: Das Ablaufdatum für Schlüssel wird in UTC festgelegt – es muss in der Zukunft festgelegt werden.

*Beispiel des Körpers anfordern:*

....
{
  "expires": "2020-04-07T10:40:52Z"
}
....
*Beispiel des Antwortkörpers:*

....
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z",
        "access_key": "PL86KPEBN6XT4T7UHNDE",
        "secret_key": "FlD/YWAM7JMr9gG8pumU8dzvcTLMzLYtUe2lNzcA"
      }
    ]
  }
}
....


=== S3-Schlüssel für Objekt-Storage-Benutzer anhand von Schlüssel-ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um S3-Schlüssel für einen Objekt-Storage-Benutzer anhand der Schlüssel-ID zu erhalten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | S3-Schlüssel per Schlüssel-ID abrufen.  a| 
* `user_id (string)`: Die Objekt-Storage-Benutzer-ID. Zum Beispiel: 5e66c77809a74c0001b89598
* `Key_id (String)`: S3-Schlüssel z. B. 5e6de2509a74c0001b895e7


|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecc7bb9b5d2730001f798fb",
        "display_name": "****************XCXD",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "objectiam_user_id": "5eb2212d1cbe3b000134762e",
        "objectiam_user": "MyUser",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "expires": "2020-05-27T00:00:00Z"
      }
    ]
  }
}
....


=== Löschen Sie einen S3-Schlüssel anhand der Schlüssel-ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen S3-Schlüssel anhand der Schlüssel-ID zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `Delete` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | S3-Schlüssel anhand der Schlüssel-ID löschen.  a| 
* `user_id (string)`: Die Objekt-Storage-Benutzer-ID. Zum Beispiel: 5e66c77809a74c0001b89598
* `Key_id (String)`: S3-Schlüssel z. B. 5e6de2509a74c0001b895e7


|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
No content to return for succesful execution
....


== Objekt-Storage-Konten

Führen Sie die folgenden Aufgaben mithilfe der in der folgenden Tabelle aufgeführten Methoden aus:

* Abrufen, Aktivieren oder Ändern von Objekt-Storage-Konten
* Erstellung von S3 Buckets:


|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/objectStorage/Accounts` | Abrufen von Objekt-Storage-Konten 


| `GET` | `/v2.1/objectStorage/Accounts/{id}` | Abrufen eines Objekt-Storage-Kontos anhand der ID 


| `POST` | `/v2.1/objectStorage/Accounts` | Erstellen eines Objekt-Storage-Kontos 


| `PUT` | `/v2.1/objectStorage/Accounts/{id}` | Ändern Sie ein anhand der ID identifizierte Objekt-Storage-Konto. 


| `DELETE` | `/v2.1/objectStorage/Accounts/{id}` | Ändern Sie ein anhand der ID identifizierte Objekt-Storage-Konto. 


| `GET` | `/v2.1/objectStorage/Buckets` | S3-Buckets abrufen. 


| `POST` | `/v2.1/objectStorage/Buckets` | Erstellung von S3 Buckets: 
|===


=== Attribute für Objekt-Storage-Konten

In der folgenden Tabelle werden die Attribute des Objekt-Storage-Kontos aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung des Objekt-Storage-Benutzers. 


| `subTenant_id` | Zeichenfolge | Die Kennung der Instanz eines Untermandant-Objekts. 


| `quota_gb` | Ganzzahl | Die Größe des Shares oder Datenträgers. 
|===


=== Rufen Sie alle Objekt-Storage-Konten ab

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen aller Objekt-Storage-Konten oder einer Untermenge an Objekt-Storage-Konten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectStorage/Accounts` | Rufen Sie alle Objekt-Storage-Benutzer ab. | `Offset` und `Limit`– . Siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 19,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtenant",
        "subtenant": " MySubtenant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": "E- MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
}
....


=== Abrufen eines Objekt-Storage-Kontos anhand der ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um ein Objekt-Storage-Konto anhand der ID abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectStorage/Accounts/{id}` | Abrufen eines Objekt-Storage-Kontos anhand der ID | `id`: Die Objekt-Storage-Konto-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtennant",
        "subtenant": " MySubtennant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": " MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
....


=== Aktivieren eines Objekt-Storage-Kontos

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zur Aktivierung eines Objekt-Storage-Kontos.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/objectStorage/Accounts` | Aktivieren eines Objekt-Storage-Service | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `subTenant_id, quota_gb`

*Beispiel des Körpers anfordern:*

....
{
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 20
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed608542c356a0001a73893",
        "action": "create",
        "job_summary": "Activate request for Sub Tenant MyNewSubtenant is successfully submitted",
        "created": "2020-06-02T08:05:40.017362022Z",
        "updated": "2020-06-02T08:05:40.017362022Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Ändern eines Objekt-Storage-Kontos

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Ändern eines Objekt-Storage-Kontos.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/objectStorage/Accounts/{id}` | Ändern Sie einen Objekt-Storage-Service (z. B. Ändern des Kontingents). | `id (String)`: Die Objekt-Storage-Konto-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `subtenant_id`, `quota_gb`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed609162c356a0001a73899",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T08:08:54.841652098Z",
        "updated": "2020-06-02T08:08:54.841652098Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Löschen eines Objekt-Storage-Kontos

Bevor Sie ein Objekt-Storage-Konto löschen können, müssen Sie zuerst alle zugehörigen Gruppen, Benutzer und Buckets löschen. Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Löschen eines Objekt-Storage-Kontos.


NOTE: Löschen Sie Buckets mithilfe Ihres S3-kompatiblen Dienstprogramms. Buckets können nicht von der NetApp Service Engine gelöscht werden.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `Delete` | `/v2.1/objectStorage/Accounts/{id}` | Löschen eines Objekt-Storage-Kontos. | `id (String)`: Die Objekt-Storage-Konto-ID. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "action": "string",
        "object_id": "5d2fb0fb4f47df00015274e3",
        "object_type": "string",
        "status": "string",
        "status_detail": "string",
        "last_error": "string",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "link": "string"
      }
    ]
  }
}
....


== Objekt-Storage-Buckets

Verwenden Sie die APIs in der folgenden Tabelle, um Objekt-Storage-Buckets zu erstellen und abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/objectStorage/Buckets` | Abrufen von Objekt-Storage-Buckets 


| `POST` | `/v2.1/objectStorage/Buckets` | Erstellen eines Objekt-Storage-Buckets 
|===


=== Attribute für Objekt-Storage-Buckets

In der folgenden Tabelle werden die Attribute des Objekt-Storage-Buckets aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung für den Objekt-Storage-Benutzer. 


| `Name` | Zeichenfolge | Der Bucket-Name 


| `subTenant_id` | Zeichenfolge | Der Bezeichner des Untermandanten, zu dem der Bucket gehört. 
|===


=== Abrufen von S3-Buckets

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen von S3-Buckets.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/objectStorage/Buckets` | Abrufen von S3-Buckets | `subTenant_id`: Der Untermieter, der den Bucket besitzt. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "creationTime": "2020-06-02T08:13:25.695Z",
        "name": "mybucket"
      }
    ]
  }
}
....


=== Erstellung von S3 Buckets

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Erstellen eines S3-Buckets.


NOTE: Bevor Sie einen Bucket erstellen können, muss ein Objekt-Storage-Konto für die Untermandanten vorhanden sein.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/objectStorage/Buckets` | Erstellen Sie einen S3-Bucket. | Keine 
|===
Erforderliche Body-Attribute für Anforderung:

* `Name` (Zeichenfolge): S3-Bucket-Name (nur in Kleinbuchstaben oder numerischen Zeichen)
* `subTenant_id` (string): ID des Untermandanten, zu dem der S3-Bucket gehört


*Beispiel des Körpers anfordern:*

....
{
  "name": "mybucket",
  "subtenant_id": "5ecefbbef418b40001f20bd6"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed60a232c356a0001a7389e",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T08:13:23.105015108Z",
        "updated": "2020-06-02T08:13:23.105015108Z",
        "object_id": "5ed60a232c356a0001a7389f",
        "object_type": "sg_buckets",
        "object_name": "mybucket",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....