---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Keystone Service-Level 
---
= Service-Leveln
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden, um Service-Level abzurufen, zu erstellen, zu ändern und zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/Service-Levels` | Rufen Sie alle Service-Level ab. 


| `GET` | `/v2.1/Service-Levels/{id}` | Rufen Sie einen Service-Level anhand der ID ab. 


| `POST` | `/v2.1/Service-Levels` | Erstellen Sie ein neues Service-Level. 


| `PUT` | `/v2.1/Service-Levels/{id}` | Ändern Sie die Service-Level-Details anhand der ID. 


| `DELETE` | `/v2.1/Service-Levels/{id}` | Löschen eines Service-Levels. 
|===


=== Service Level-Attribute

In der folgenden Tabelle werden die Service Level-Attribute aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung für die Servicelevel. 


| `Name` | Zeichenfolge | Der Name des Service-Levels. 


| `DBeschreibung` | Zeichenfolge | Die Beschreibung des Service Levels. 


| `Policy_Name` | Zeichenfolge | Name der Service-Level-Qualität (QoS): Zulässige Werte: nse_Value, nse_Standard, nse_Performance und nse_extreme. 


| `verfügbar` | Boolesch | Gibt an, ob der Service-Level zur Verwendung verfügbar ist. 


| `grandifiert` | Boolesch | Gibt an, ob das Service-Level außer Betrieb genommen wurde. 


| `Peak_iops_pro_tb` | Ganzzahl | Die maximal möglichen IOPS pro tib. 


| `Erwartungsed_iops_pro_tb` | Ganzzahl | Die erwarteten Mindestwerte für IOPS pro tib. 


| `Absolute_min_iops` | Ganzzahl | Das absolute IOPS-Minimum, das als Überschreiben verwendet wird, wenn die erwarteten IOPS kleiner als dieser Wert sind. 


| `Peak_iops_Allokation` | Zeichenfolge | Die maximale IOPS-Zuweisung: Zulässige Werte: Zugewiesener_space und used_space. 


| `io_Block_size_kb` | Ganzzahl | Die I/O-Blockgröße (KiB). 


| `min_size_gb` | Ganzzahl | Die minimale Größe (gib). 


| `max_size_gb` | Ganzzahl | Die maximale Größe (gib). 


| `max_Peak_iops` | Ganzzahl | Der maximale IOPS-Spitzenwert für das Service-Level. 


| `max_erwarteter_iops` | Ganzzahl | Der erwartete IOPS-Maximum 


| `Autogrow_max_percent` | Ganzzahl | Die maximale prozentuale Autogrow-Auslastung. 


| `ontap_Aggregate` | –  a| 
Die Liste der ONTAP-Aggregate Ein ONTAP Aggregat besteht aus:

* `Cluster_UIID: ONTAP-Cluster-UUID`
* `aggr_Name: ONTAP Aggregatname`
* `aggr_UUID: ONTAP Aggregate UUID`
* `Node_Name: ONTAP-Cluster-Node-Name` Beispiel:


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| `primary_Volume_defards` | –  a| 
* snapshot_Auto_delete_target_free_space (Integer): Diese Option gibt den Prozentsatz des freien Speicherplatzes an, mit dem das automatische Löschen von Snapshot Kopien angehalten werden muss.
* auto_size_Mode (String): Der Autosize-Modus für das Volume. Zulässige Werte: Off, Grow, Grow_schrumpfen z.B.:


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


=== Abrufen von Service-Leveln

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um alle Service-Level abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Service-Levels` | Rufen Sie alle Service-Level ab. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== Abrufen von Service-Leveln nach Name

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um Service-Level nach Namen abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Service-Levels/{Name}` | Rufen Sie einen Service-Level nach Namen ab. | `Name (String)`: Der Name des Service-Levels. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== Erstellen Sie einen Service Level

Verwenden Sie zum Erstellen eines Service Levels die in der folgenden Tabelle aufgeführte Methode.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/Service-Levels` | Erstellen Sie einen Service Level. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `Policy_Name`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


=== Ändern Sie einen Service-Level

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Ändern eines Service-Levels.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/Service-Levels/{Name}` | Ändern Sie die Details zu einem Service-Level. | `Name (String)`: Der Name des Service-Levels. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Beispiel des Antwortkörpers:*

....
TBA
....


=== Service-Level nach ID löschen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen Service Level nach ID zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `DELETE` | `/v2.1/Service-Levels/{Name}` | Löschen Sie den Service-Level, der anhand der ID identifiziert wurde. | `Name (String)`: Der Name des Service-Levels. 
|===
*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
No content for succesful delete
....