---
sidebar: sidebar 
permalink: seapiref_zones.html 
keywords: netapp, keystone, zones, 
summary: Keystone Zonen 
---
= Zonen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden zum Erstellen, Ändern und Löschen von Zonen. APIs zum Abrufen von Zonen finden Sie unter (Consumer) Administration APIs.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `POST` | `/v2.1/Zones` | Erstellen Sie eine neue Zone. 


| `PUT` | `/v2.1/Zones/{Name}` | Ändern Sie die Details einer Zone. 


| `DELETE` | `/v2.1/Zones/{Name}` | Löschen Sie eine Zone. 
|===


== Zonenattribute

In der folgenden Tabelle sind die Zonenattribute aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung der Zone. 


| `Name` | Zeichenfolge | Der Zonenname. 


| `DBeschreibung` | Zeichenfolge | Die Beschreibung der Zone. 


| `reRegion_Name` | Zeichenfolge | Der Name der Region, in der sich die Zone befindet. 
|===


== Alle Zonen abrufen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um alle Zonen oder eine Untermenge von Zonen abzurufen. Wenn Sie einen Bereich angeben, werden nur die zu diesem Mandanten gehörenden Blockspeicher zurückgegeben.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Zones` | Zonen abrufen. | (Optional) Bereichsname (String) `Offset` und `Limit` – siehe link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Gemeinsame Paginierung"] 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 2,
    "limit": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
....


== Rufen Sie eine Zone nach Namen ab

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Zone nach dem Zonennamen abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Zones/{Name}` | Rufen Sie eine Zone nach Namen ab. | `Name (Zeichenfolge)`: Zonenname 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
}
....


== Erstellen Sie eine Zone

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Zone zu erstellen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/Zones` | Erstellen Sie eine neue Zone innerhalb einer Region. | Keine 
|===
Erforderliche Body-Attribute der Anforderung: `Name`, `dBeschreibung`, `reRegion_Name`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyZoneName",
  "description": "DescriptionOfMyZone",
  "region_name": "MyRegionName"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "DescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


== Ändern Sie eine Zone

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um eine Zone zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/Zones{Name}` | Ändern Sie eine Zone, die durch den Namen gekennzeichnet ist. | `Name (String)`: Name der Zone. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyZoneName",
  "description": "NewDescriptionOfMyZone"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "NewDescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


== Löschen Sie eine Zone

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Löschen einer Zone.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `DELETE` | `/v2.1/Zones{Name}` | Löschen Sie eine einzelne Zone, die durch den Namen gekennzeichnet ist. Alle Speicherressourcen in einer Zone müssen zuerst gelöscht werden. | `Name (String)`: Name der Zone. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

Kein Inhalt, der beim erfolgreichen Löschen zurückgegeben werden muss.
