---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Keystone Untermandanten 
---
= Untermieter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Methoden zum Abrufen, Erstellen, Ändern und Löschen von Untermandanten.

|===
| HTTP-Methode | Pfad | Beschreibung 


| `GET` | `/v2.1/Untermandanten` | Abrufen von Untermandanten 


| `GET` | `/v2.1/Untermandanten/{id}` | Rufen Sie einen Untermandanten mithilfe der Untermandant-ID ab. 


| `POST` | `/v2.1/Untermandanten`` | Erstellen Sie einen neuen Untermandanten. 


| `PUT` | `/v2.1/Untermandanten/{id}` | Ändern Sie die Details eines Untermandanten. Sie können den Namen des Untermandanten ändern. 


| `DELETE` | `/v2.1/Untermandanten/{id}` | Einen Untermandanten löschen. 
|===


=== Attribute für untergeordnete Mandanten

In der folgenden Tabelle werden die Attribute des Untermandanten aufgeführt.

|===
| Attribut | Typ | Beschreibung 


| `id` | Zeichenfolge | Die eindeutige Kennung des Untermandanten. 


| `Name` | Zeichenfolge | Der Name des Untermandanten. 


| `Code` | Zeichenfolge | Ein vom Kunden angegebener (oder standardmäßiger) Code, der den Untermandanten darstellt. 


| `Tenant_id` | Zeichenfolge | Die Kennung des Mandanten, zu dem der Untermandant gehört. 
|===


=== Alle Untermandanten abrufen

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Abrufen aller Untermandanten oder einer Untermenge aller Untermandanten. Wenn Sie eine `Tenant_id` angeben, werden nur die Untermandanten zurückgegeben, die zu diesem Mandanten gehören.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Untermandanten` | Abrufen von Untermandanten | `Tenant_id`: (Optional) gibt die Untermandanten zurück, die dem angegebenen Mandanten gehören. Offset und Limit – siehe 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== Abrufen eines Submandanten nach ID

Verwenden Sie die im Folgenden aufgeführte Methode, um einen Untermandanten nach ID abzurufen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `GET` | `/v2.1/Untermandanten/{id}` | Rufen Sie den von der ID angegebenen Untermandanten ab. | `id (String)`: Die eindeutige Kennung des Untermandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== Erstellen eines Untermandanten

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode zum Erstellen eines Untermandanten.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `POST` | `/v2.1/Untermandanten` | Erstellen Sie einen neuen Untermandanten. | Keine 
|===
Erforderliche Body-Attribute für Anforderung: `Name`, `Code`, `Tenant_id`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== Ändern Sie einen Untermandanten anhand der ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen Untermandanten nach ID zu ändern.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `PUT` | `/v2.1/Untermandanten/{id}` | Ändern Sie den mit der ID angegebenen Untermandanten. Sie können den Namen des Untermandanten ändern. | `id (String)`: Die eindeutige Kennung des Untermandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `Name`

*Beispiel des Körpers anfordern:*

....
{
  "name": "MyModifiedSubtenant"
}
....
*Beispiel des Antwortkörpers:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== Löschen Sie einen Untermandanten nach ID

Verwenden Sie die in der folgenden Tabelle aufgeführte Methode, um einen Untermandanten nach ID zu löschen.

|===
| HTTP-Methode | Pfad | Beschreibung | Parameter 


| `DELETE` | `/v2.1/Untermandanten/{id}` | Löschen Sie den von der ID angegebenen Untermandanten. | `id (String)`: Die eindeutige Kennung des Untermandanten. 
|===
Erforderliche Body-Attribute für Anforderung: `none`

*Beispiel des Körpers anfordern:*

....
none
....
*Beispiel des Antwortkörpers:*

....
No content for succesful delete
....