---
sidebar: sidebar 
permalink: sewebiug_modify_a_file_share.html 
keywords: netapp, keystone, modify, file, share, 
summary: Keystone Ändern einer Dateifreigabe 
---
= Ändern Sie eine Dateifreigabe
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können den Freigabennamen, den Freigabetyp (CIFS, NFS, Multi-Protocol), Service Level, Kapazität, snapshot-Richtlinie, Exportrichtlinie, Zugriffssteuerungsliste (ACL) und Tags.


NOTE: Mit dieser Methode können Sie Ihre Shares in unterschiedliche Leistungsstufen verschieben, wenn diese verfügbar sind. Sie können den Freigabetyp nur ändern, wenn der Server die entsprechenden Dienste unterstützt.

Die Dateifreigabe muss sich im Betriebszustand befinden. Informationen zum Verständnis der Volume-Status und der Schritte, die für deren Betrieb erforderlich sind, finden Sie unter link:https://docs.netapp.com/us-en/keystone/sewebiug_view_shares.html["Zeigen Sie Festplatten an"] Und 

.Schritte
. Sehen Sie sich die an link:sewebiug_view_shares.html#view-shares["Shares-Liste"].
. Suchen Sie die Freigabe in der Liste, und klicken Sie auf das Symbol Bearbeiten für die Freigabe. (Einzelheiten zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Aktionen zur Listenansicht"]).
. Nehmen Sie ggf. Änderungen vor. Die Feldbeschreibungen finden Sie unter link:sewebiug_create_a_new_file_share.html["Erstellen Sie eine neue Dateifreigabe"].
. Klicken Sie Auf *Fertig*. Dadurch wird ein Job zum Ändern der Freigabe erstellt.


Änderungsfreigabe wird als asynchroner Job ausgeführt. Ihre Vorteile:

* Überprüfen Sie den Status des Jobs in der Jobliste. Informationen zur Verfolgung von Jobs finden Sie unter link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Hier"].
* Überprüfen Sie nach Abschluss des Jobs den Status der Freigabe in der Liste „Shares“.

