---
sidebar: sidebar 
permalink: sewebiug_create_object_storage_user.html 
keywords: netapp, keystone, create, object, storage, user, 
summary: Keystone erstellt Benutzer von Objekt-Storage 
---
= Objektspeicherbenutzer Erstellen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Da ein Objektspeicherbenutzer einer Objektspeichergruppe angehört, muss die Objektspeichergruppe vorhanden sein, bevor Sie den Benutzer erstellen können.

.Schritte
. Navigieren Sie zu *OBJEKT-STORAGE > Benutzerverwaltung > Benutzer*.
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und Sie auf die Registerkarte *Benutzer* geklickt haben.
. Klicken Sie Auf *Benutzer Erstellen*.
. Im Dialogfeld Benutzer erstellen:
+
.. Geben Sie den Benutzernamen ein.
.. Wählen Sie die Gruppe aus, der das Mitglied angehört.


. Klicken Sie Auf *Erstellen*. Dadurch wird ein Job zum Erstellen des Benutzers mit den angegebenen Einstellungen erstellt.


Benutzer erstellen wird als asynchroner Job ausgeführt. Ihre Vorteile:

* Überprüfen Sie den Status des Jobs in der Jobliste. Weitere Informationen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Anzeige von Jobs und Job-Status"].
* Überprüfen Sie nach Abschluss des Jobs den Status der Freigabe in der Benutzerliste.

