---
sidebar: sidebar 
permalink: sewebiug_create_adhoc_snapshot_of_a_file_share.html 
keywords: netapp, keystone, create, adhoc, snapshot, file, share, 
summary: Keystone erstellt Ad-hoc-Snapshot einer Dateifreigabe 
---
= Erstellen Sie einen Ad-hoc-Snapshot einer Dateifreigabe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird beschrieben, wie ein Ad-hoc-Snapshot einer Dateifreigabe erstellt wird.

.Schritte
. Sehen Sie sich die an link:sewebiug_view_shares.html#view-shares["Shares-Liste"].
. Suchen Sie die Freigabe in der Liste, und klicken Sie auf das Snapshot-Symbol für diese Freigabe. (Einzelheiten zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Aktionen zur Listenansicht"].
. Geben Sie im Dialogfeld Snapshot erstellen einen Namen für Ihren Snapshot ein und klicken Sie auf *Erstellen*.


.Nachdem Sie fertig sind
Der Snapshot kann ein paar Minuten dauern, bis er verfügbar ist. Wenn verfügbar, können Sie eine weitere Freigabe erstellen, indem Sie diesen Snapshot klonen. Weitere Informationen finden Sie unter link:sewebiug_create_file_share_from_snapshot.html["Erstellen Sie eine Dateifreigabe aus einem Snapshot"].
