---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone erstellt einen S3-Schlüssel für einen Benutzer 
---
= Erstellen eines S3-Schlüssels für einen Benutzer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um einen S3-Schlüssel für einen Benutzer zu erstellen.

Stellen Sie sicher, dass Sie den Schlüssel sofort nach der Erstellung erfassen. Es gibt keine Möglichkeit, Schlüsseldetails nach der Erstellung abzurufen.

.Schritte
. Zeigen Sie den Objekt-Storage-Benutzer an link:sewebiug_view_the_object_storage_group_and_users.html["Zeigen Sie Objekt-Storage-Gruppen und Benutzer an"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und Sie auf die Registerkarte *Benutzer* geklickt haben.
. Suchen Sie den Benutzer in der Liste, und klicken Sie auf das Schlüsselsymbol für diese Gruppe.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Aktionen zur Listenansicht"].

. Das Dialogfeld *S3-Schlüssel verwalten* zeigt die Liste der Tasten für den Benutzer an. Informationen zu Schlüsseln finden Sie unter https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Legen Sie Berechtigungen in einer Richtlinie fest"].
. Wenn für den Benutzer keine Schlüssel vorhanden sind, klicken Sie auf *S3-Schlüssel erstellen*, um die Felder zum Erstellen eines Schlüssels anzuzeigen.
. Wenn der Schlüssel ablaufen soll, geben Sie das Ablaufdatum und die Ablaufzeit in UTC an. Lassen Sie andernfalls die Standardwerte in diese Felder.
. Klicken Sie zum Erstellen der Taste auf das Häkchen. Das Dialogfeld *S3 Key Details* zeigt den Zugriffstaste und den geheimen Schlüssel an.
. Kopieren Sie den Zugriff und die geheimen Schlüssel in Vorbereitung, um den Benutzer über die Details zu informieren.
+
Stellen Sie sicher, dass Sie die Schlüsseldetails erfassen, bevor Sie das Dialogfeld *S3 Key Details* schließen. Nach dem Schließen werden die Schlüsseldetails verdeckt und Sie können sie nicht mehr abrufen.

. Klicken Sie Auf *Schließen*.
. Klicken Sie erneut auf *Schließen*, um das Dialogfeld S3-Schlüssel verwalten zu schließen.

