---
sidebar: sidebar 
permalink: sewebiug_managing_service_requests_overview.html 
keywords: netapp, keystone, managing, service, requests, overview, 
summary: Keystone Managen von Service-Anfragen – Übersicht 
---
= Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mithilfe von Serviceanfragen können Sie ein Problem mit dem GSSC Team ansprechen, damit diese das Problem lösen und den Status für Sie aktualisieren können.


NOTE: Sie können das Menü *Support > Service Requests* nur aufrufen, wenn Sie Partner-Administrator sind. Als Partner-Administrator können Sie auch die Service-Anfragen, die für Ihren ausgewählten Mandanten erzeugt wurden, im Dashboard anzeigen. Sie können beim NetApp Support keine Service-Anfrage stellen, wenn Sie ein Mandantenadministrator sind.

Der Workflow befindet sich unter link:https://docs.netapp.com/us-en/keystone/sewebiug_service_request_process.html["Service-Request-Prozess"]

Geben Sie eine Serviceanfrage für:

* Backup-Wiederherstellung
* Disaster-Recovery-Failover
* Ein technisches Problem mit der NetApp Service Engine
* Nicht standardmäßige Volumes: Die Volumes, die in Ihr Flex Abonnement importiert werden, verwenden denselben Standard wie die vorhandenen Festplatten und Dateifreigaben auf der NetApp Service Engine. Nach dem Import werden diese Festplatten und File Shares mit dem Status `Non-Standard` kategorisiert. Sie stellen eine Service-Anfrage, um ihren Status auf einen Standard zu ändern.
* Alle anderen Probleme, die in dieser Liste nicht behandelt werden.


Die anderen Themen in diesem Abschnitt diskutieren:

* So richten Sie eine Serviceanfrage ein
* Verfolgen einer Service-Anfrage
* Der Service-Request-Prozess

