---
sidebar: sidebar 
permalink: sewebiug_view_shares.html 
keywords: netapp, keystone, view, shares, 
summary: Keystone Ansicht von Freigaben 
---
= Anzeigen von Dateifreigaben
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In der Liste *Shares* werden die dem ausgewählten Mandanten gehörenden Dateifreigaben angezeigt. Um die Liste anzuzeigen, wählen Sie im Menü *FILE SERVICES > Shares*.

Die Dateifreigaben, die bereits in Ihre vorhandene Umgebung integriert sind und zu den in Ihrer NetApp Service Engine konfigurierten Storage-VMs gehören, können auch auf diesem Bildschirm angezeigt und als Bestandteil Ihrer NetApp Keystone Flex Subscription (Flex Subscription)-Services gemanagt werden. Die außerhalb der NetApp Service Engine bereitgestellten Dateifreigaben werden regelmäßig importiert und auf dieser Seite mit entsprechenden Statuscodes aufgelistet.

Wenn die importierten Dateifreigaben in den akzeptablen Standards der NetApp Service Engine liegen, sind alle Parameter, die für die operative Freigabe erforderlich sind, verfügbar, sie werden mit dem Status als `Operational` importiert und können direkt über die NetApp Service Engine gemanagt werden. Einige Shares sind jedoch möglicherweise nicht im gleichen Standard wie die bestehenden Shares auf der NetApp Service Engine. Nach dem Import werden diese Dateifreigaben mit dem Status `imported` oder `Non-Standard` kategorisiert. Informationen zum Verständnis der Volume-Status und der Schritte, die für deren Betrieb erforderlich sind, finden Sie unter link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["Objektstatus"]

In der Freigabeliste werden einfache Informationen zu jeder Freigabe angezeigt. Weitere Informationen zur Verwendung der Funktionen einer Liste finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Listenansicht"].

* Freigabename
* Server, auf dem sich der Server befindet
* Freigabepfad
* CIFS Share-Pfad (wird zum Mounten der CIFS Share mit der DNS-Integration verwendet)
* Untermandant, zu dem sie gehört
* Bereich, in dem sie vorhanden ist
* Service-Level
* Betriebsstatus (Betrieb, Aktualisierung oder Kontakt zum Support)
* Erstellungsdatum

