---
sidebar: sidebar 
permalink: sewebiug_create_an_object_storage_group.html 
keywords: netapp, keystone, create, object, storage, group, 
summary: Keystone erstellt eine Objekt-Storage-Gruppe 
---
= Erstellen Sie eine Objekt-Storage-Gruppe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um eine neue Objekt-Speichergruppe zu erstellen.

.Schritte
. Sehen Sie sich die an link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["Benutzerliste"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und dass im Display Gruppen angezeigt werden (nicht Benutzer).
. Klicken Sie Auf *Gruppe Erstellen*.
. Geben Sie im Dialogfeld Gruppe erstellen den Gruppennamen ein.
. Wählen Sie die S3-Richtlinie aus der Liste aus.
. Klicken Sie Auf *Erstellen*. Dadurch wird ein Job erstellt, um die Gruppe mit den angegebenen Einstellungen zu erstellen.


Objekt-Storage-Gruppe erstellen wird als asynchroner Job ausgeführt. Sie können den Status des Jobs in der Liste Jobs überprüfen. Informationen zur Verfolgung von Jobs finden Sie unter link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Hier"].
