---
sidebar: sidebar 
permalink: sewebiug_working_with_object_storage_overview.html 
keywords: netapp, keystone, working, object, storage, overview, 
summary: Keystone Arbeiten mit Objekt-Storage – Übersicht 
---
= Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für Objekt-Storage ist ein Objekt-Storage-Service-Abonnement erforderlich. Wenn ein Objekt-Speicherdienst im Rahmen des Abonnements verfügbar ist, muss der Speicher initialisiert werden, bevor er verwendet werden kann.

Beim Objekt-Storage werden Objekte in S3 Buckets gespeichert. Der Zugriff auf die S3-Buckets wird über Berechtigungen gemanagt, die für Objekt-Storage-Gruppen festgelegt sind. Objektspeicherbenutzer werden einer oder mehreren Objektspeichergruppen Mitgliedschaft gewährt, was Berechtigungen aus der Gruppenmitgliedschaft vererbt.

Jeder Objekt-Storage-Benutzer verfügt über die zugehörigen S3-Schlüssel für den Zugriff auf den Objekt-Storage.


NOTE: Der Zugriff auf den Objekt-Storage erfolgt über einen S3-kompatiblen Browser.

In diesem Abschnitt wird das Management von Objekt-Storage beschrieben. Außerdem werden folgende Themen behandelt:

* Objektspeicher initialisieren.
* Erstellung von S3 Buckets:
+
S3-Buckets können nicht über das Webportal der NetApp Service Engine gelöscht und über einen S3-kompatiblen Browser gelöscht werden.

* Erstellen und Managen von Objekt-Storage-Gruppen
* Erstellen und managen Sie Objekt-Storage-Benutzer einschließlich Erstellen von S3-Schlüsseln.

