---
sidebar: sidebar 
permalink: sewebiug_managing_gcp_cvs.html 
keywords: netapp, keystone, managing CVS for GCP, gcp, Google Cloud Volume, CVS, Cloud Volumes Service 
summary: Managen von Cloud Volume-Abonnements auf der Google Cloud Platform 
---
= Management von Cloud Volumes Service für GCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Abonnements von Cloud Volumes Service für die Google Cloud Platform (GCP) sind mit bestimmten Untermandanten in Verbindung, die über einen Mandanten verfügen. Ein Untermandant ist für einen einzelnen Google Cloud-Service abonniert. Es ist möglich, Cloud-Services (Google Cloud Instanzen) für Ihre Mandanten und Untermandanten zu erstellen und zu managen sowie Storage auf Google Cloud basierend auf den Mandanten bereitzustellen. Die Cloud Volumes Service-Konten der Mandanten und Untermandanten sollten eingerichtet werden, bevor Sie Google Cloud-Instanzen über die NetApp Service Engine managen können. Weitere Informationen zu Cloud Volumes Service auf GCP finden Sie unter https://docs.netapp.com/us-en/occm/concept_cvs_gcp.html["Erfahren Sie mehr über Cloud Volumes Service für Google Cloud"].


NOTE: Die Cloud Volumes Service-Konten für die Mandanten und Untermandanten sollten bereits für GCP konfiguriert sein. Wenden Sie sich an den Support, um die Service-Account-Details zu erhalten. Zum Management von Google Cloud Volumes benötigen Sie Administratorzugriff.



== Management Ihrer Cloud-Services auf GCP

Sie können Ihre Cloud-Services auf Google Cloud verwalten, indem Sie im linken Navigationsbereich im Menü *CLOUD SERVICES* klicken. Auf der Seite Cloud Services werden alle Cloud-Services für alle Untermandanten eines ausgewählten Mandanten angezeigt. Sie können die Cloud-Services auf dieser Seite anzeigen, ändern und löschen. Sie können auch einen neuen Service hinzufügen, indem Sie diese Schritte ausführen.

.Bevor Sie beginnen
Dafür müssen Sie Folgendes gewährleisten:

* Der Untermieter ist für den Google Cloud-Service abonniert.
* Sie haben die JSON-Datei für das Servicekonto des Abonnenten und kennen die GCP-Projektnummer, die mit der Google Cloud Instanz verknüpft ist.
* Damit Cloud Volumes Service für GCP bereits von Ihrem Support-Team unter BlueXP konfiguriert ist. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/occm/task_setup_cvs_gcp.html["Einrichtung von Cloud Volumes Service für Google Cloud"].


.Schritte
. Wählen Sie im Menü * CLOUD SERVICES* aus.
. Klicken Sie auf *Erstellen* und dann auf *Google Cloud*.
. Wählen Sie auf der Seite Cloud-Service für Google Cloud erstellen den Untermandanten aus, für den Sie den Service erstellen möchten, und fügen Sie einen Namen und die GCP-Projektnummer hinzu.
. Laden Sie im Abschnitt Google Cloud Credentials die JSON-Datei mit den Zugangsdaten für das Servicekonto hoch.
. Fügen Sie ggf. dem Dienst Tags hinzu.
. Klicken Sie Auf *Erstellen*. Wenn diese erstellt ist, ändert sich der Servicestatus auf der Seite „Cloud Services“ in `Succeeded`.




== Management von Volumes auf GCP

Vor dem Managen von Cloud Volumes auf GCP sollte das Cloud Volumes Service-Konto für den Mandanten erstellt und das Konto für Cloud Volumes abonnieren. Wenden Sie sich an den Support, um sicherzustellen, dass diese Schritte abgeschlossen sind.

Im linken Navigationsbereich können Sie Volumes für einen Untermandanten auf GCP über *FILESERVICES > GCP Volumes* verwalten. Auf der Seite GCP Volumes werden die bestehenden Cloud Volumes aufgeführt, die auf GCP für den ausgewählten Submandanten und die entsprechende Region erstellt wurden. Sie können die vorhandenen Volumes auf dieser Seite anzeigen, ändern und löschen. Sie können auch ein neues Cloud-Volume bereitstellen. Gehen Sie dazu wie folgt vor.

.Schritte
. Wählen Sie im Menü * FILE SERVICES > GCP Volumes* aus.
. Klicken Sie Auf *Erstellen*. Die Seite GCP Volume erstellen wird angezeigt.
. Wählen Sie den Untermandanten aus, für den Sie das Volume erstellen möchten.
. Wählen Sie die Region und das Netzwerk aus. Die Liste wird basierend auf dem Cloud Volumes Service-Konto für den Untermandanten in GCP gefiltert.
. Fügen Sie einen Namen für das Volume hinzu.
. Wählen Sie den entsprechenden Service Level aus.
. Geben Sie den Dateipfad des Volumes als Erstellungstoken ein.
. Weisen Sie die Volume-Quote in Bytes zu.
. Fügen Sie bei Bedarf Tags für das Volume hinzu.
. Klicken Sie Auf *Erstellen*. Wenn diese erstellt ist, ändert sich der Status des Volumes in `Succeeded` auf der GCP-Volumes-Seite.


In dem folgenden Video erfahren Sie, wie ein Volume auf GCP mithilfe von Cloud Volumes Service und der NetApp Service Engine erstellt wird:

video::Crq5a1zi1Vg[youtube,width=750,height=400]