---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: NetApp Service Engine Partner, Service Provider-Funktionen 
---
= Rollen und Betriebsabläufe von Service-Providern und Kunden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Abhängig von Ihrer Funktion als Service-Provider oder Partner (austauschbar) oder als Kunde oder Mandant (austauschbar) Administrator werden die Ansichten und Funktionen im Webportal der NetApp Service Engine bestimmt.



== Aktivitäten, die Sie als Administrator des Service-Providers ausführen können

Als Service-Provider-Administrator in einer mandantenfähigen Umgebung können Sie über die Web-UI der NetApp Service Engine die Funktionen für Provisionierung, Berichterstellung, Abrechnung und Management von Kunden mit eigenen Abonnements übernehmen. Sie können folgende Funktionen ausführen:

* Sehen Sie sich den abonnierten und bereitgestellten Storage als Teil des Keystone Abonnementservice an.
+

NOTE: Als Service bieten Sie Ihren Kunden mehr Kapazität als durch den Kauf von NetApp (Überzeichnung). Mandantenabonnements können über den aktuellen Keystone Abonnementzeitraum hinausgehen. Bei der Abonnement-Erstellung und in Dashboards/Berichten wird jedoch eine Warnung angezeigt.

* Mandanten, Untermandanten, Änderungen und Löschung erstellen, anzeigen, ändern und löschen Und Benutzer.
* Anzeigen von Zonen und Regionen für Ihre Abonnements
* Managen und Hosten mehrerer Mandanten im Keystone Abonnementservice: Erstellen und managen Sie Mandantenabonnements und zeigen Sie Ihre eigenen Keystone Abonnementdetails an.
+

NOTE: Die Mandanten-Abonnements können auf Basis der entsprechenden Zonen und Keystone Keystone Abonnements erstellt werden. Die Erstellung erfolgt gemäß den Service-Leveln, die unter der abonnierten Kapazität Ihres Keystone Abonnements bereitgestellt werden.

* Erstellen von File Servern oder Block-Stores und Initialisieren von Block-, Datei- und Objekt-Storage, während Sie die Netzwerkanforderungen für die Bereitstellung jedes Storage-Typs für Ihre Mandanten kennen.
* Auch Subnetze für Mandanten erstellen und managen
* Hier können Sie sich File Shares, Festplatten und Buckets ansehen, die im Rahmen Ihres Keystone Abonnements erstellt wurden. Erstellen und managen Sie auch Objekt-Storage-Gruppen und Benutzer.
* Erstellen Sie Nutzungsberichte für Ihr Keystone Abonnement sowie für Mandanten-Abonnements und Nutzung für alle Mandanten, die Sie in den jeweiligen Abrechnungs- und Bewertungssystemen nutzen können.
* Rechnungen und Berichte für alle Mandanten und Kunden sowie nur für den bereitgestellten oder abonnierten Storage anzeigen
* Anzeige und Verwaltung von Service-Anfragen, die von Kunden innerhalb Ihres eigenen Service-Request-Tools (Partner/Service-Provider) gestellt werden (integriert mit OpsRamp/GSSC).




== Aktivitäten, die Sie als Kunden-/Mandantenadministrator durchführen können

Als Mandantenadministrator können Sie die Abonnementdetails Ihrer eigenen Mandantenfähigkeit anzeigen und administrative Aufgaben für Ihre Untermandanten ausführen. Sie können folgende Aktionen ausführen:

* Sehen Sie sich den Speicher an, der als Teil Ihres Mandanten-Abonnementservice abonniert und bereitgestellt wurde.
* Managen und bearbeiten Sie Untermandanten für Ihre Mandantenfähigkeit und optimieren Sie sie.
* Anzeigen Ihrer Zonen, Regionen, Untermandanten und Subnetze
* Zeigen Sie die von Service-Providern erstellten Dateiserver an.
* Erstellung von Dateifreigaben, Festplatten und Buckets und Zuweisen von Service Levels
* Zeigen Sie Berichte für Mandanten und Untermandanten von *Berichten > Kapazitätsauslastung* an, um die Verbrauchsdaten nur für den Storage anzuzeigen, der für Ihre Mandanten und Untermandanten abonniert oder bereitgestellt wurde.
* Zeigen Sie Berichte für Mandanten und Untermandanten von *Reports > Performance* an, um sich die Performance und die Einhaltung der Service-Compliance für die einzelnen abonnierten Services und Add-on-Services (Datensicherung und erweiterter Schutz) anzusehen.
+

NOTE: Für weitere Abonnements können Sie Ihr Service Request Tool verwenden.


