---
sidebar: sidebar 
permalink: sewebiug_add_a_user.html 
keywords: netapp, keystone, add, user, 
summary: Keystone Hinzufügen eines Benutzers 
---
= Fügen Sie einen Benutzer hinzu
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird beschrieben, wie ein Benutzer hinzugefügt wird.



=== Bevor Sie beginnen

Sie benötigen:

* Die Mandanten, denen der Benutzer Zugriff erhalten soll.
* Die Rolle, die der Benutzer in jeder einzelnen Mandanten erhält. Ein Benutzer kann nur eine Rolle innerhalb einer Mandanten verwenden.




=== Schritte

. Wählen Sie im Menü die Option *VERWALTUNG > Benutzer*.
. Klicken Sie Auf *Benutzer Erstellen*.
. Geben Sie im Dialogfeld Benutzer erstellen den Benutzernamen, die E-Mail-Adresse, den Vornamen, den Nachnamen, den Anzeigenamen, an. Und Kennwort für den Benutzer.
. Wählen Sie den primären Mandanten und die Rolle des Benutzers in dieser Mandanten aus.
+

NOTE: Sie können einem Benutzer basierend auf seiner Rolle Berechtigungen zuweisen, beispielsweise einem NetApp Administrator, einem NetApp Administrator mit reinen Lesezugriff, einem Partner-Administrator oder einem Mandantenadministrator. Sie können die Rollen verschiedener Benutzer in Ihrer Umgebung anzeigen und neu erstellten bzw. vorhandenen Benutzern Rollen zuweisen.

. Um weitere Mandanten hinzuzufügen, klicken Sie auf *Mandantenfähigkeit hinzufügen*, um neue Eingabefelder anzuzeigen und wählen Sie den Mieter und die Rolle des Benutzers in dieser Mandanten aus.
. Klicken Sie Auf *Erstellen*.

