---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_user.html 
keywords: netapp, keystone, modify, object, storage, user, 
summary: Keystone ändert einen Objekt-Storage-Benutzer 
---
= Ändern eines Objektspeicherbenutzers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um Details eines Objektspeicherbenutzers, z. B. des Benutzernamens und der Gruppe, der sie zugewiesen sind, zu ändern.

.Schritte
. Zeigen Sie den Objekt-Storage-Benutzer an link:sewebiug_view_the_object_storage_group_and_users.html["Zeigen Sie Objekt-Storage-Gruppen und Benutzer an"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und Sie auf die Registerkarte *Benutzer* geklickt haben.
. Suchen Sie den Benutzer in der Liste, und klicken Sie auf das Bearbeiten-Symbol für diesen Benutzer.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Aktionen zur Listenansicht"].

. Ändern Sie im Dialogfeld *Benutzer bearbeiten* die Objekt-Speichergruppe für den Benutzer.
. Klicken Sie Auf *Aktualisieren*. Dadurch wird ein Job zum Aktualisieren der Gruppe für den Benutzer erstellt. Informationen zur Verfolgung von Jobs finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Hier"].

