---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, snapshot 
summary: Erstellen Sie eine Dateifreigabe aus einem Snapshot 
---
= Erstellen Sie eine Dateifreigabe aus einem Snapshot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine neue Dateifreigabe aus einem vorhandenen Snapshot erstellen. Die neue Dateifreigabe, die aus dem Snapshot geklont wurde, hat dieselben Eigenschaften wie die Dateifreigabe, von der der Snapshot erstellt wird.

.Schritte
. Wählen Sie im linken Navigationsbereich *FILE SERVICES* aus und wählen Sie *Shares*.
. Klicken Sie auf *Create Share* und wählen Sie *Clone from Snapshot*. Wenn Sie alternativ den Share kennen, dessen Snapshot Sie zum Klonen verwenden möchten, können Sie die Dateifreigabe suchen und auf die Schaltfläche Kopieren daneben klicken. Der Share sollte sich in einem Betriebszustand befinden. Informationen zu Objektstatus finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["Objektstatus"]. Der Bildschirm *Create Share from Snapshot* wird mit allen Dateifreigaben für den Mieter angezeigt. Sie können Dateifreigaben nach Region, Zone und Untermandant filtern. Sie können jede beliebige Dateifreigabe auswählen, die sich im Betriebszustand befindet.
. Aktivieren Sie das Kontrollkästchen neben der gewünschten Dateifreigabe und klicken Sie auf *Weiter*. Die Snapshots für die Dateifreigabe werden angezeigt.
+

NOTE: Wenn für die ausgewählte Dateifreigabe einige Snapshots erstellt wurden, die in der SnapCenter-Umgebung außerhalb der NetApp Service Engine erstellt wurden, können Sie die Snapshots importieren und für Ihre Auswahl aufgelistet finden. Sie können diese importierten Snapshots auswählen und die neuen Dateifreigaben daraus klonen.

+
Sie können nach einem bestimmten Snapshot suchen oder den Zeitplantyp auswählen, um die Snapshots zu filtern.

. Aktivieren Sie das Kontrollkästchen neben dem Snapshot, von dem Sie klonen möchten, und klicken Sie auf *Weiter*. Der neue Dateifreigabe übernimmt die Eigenschaften des ausgewählten Snapshots.
. Fügen Sie *Name* und *Pfad teilen* hinzu. Aktualisieren Sie die anderen Einstellungen, wie z. B. die Zuweisung einer *Service Level*, und klicken Sie auf *Erstellen*. Wählen Sie den Service Level aus, der Ihren Anforderungen am besten entspricht.


.Nachdem Sie fertig sind
* Nur für CIFS-Freigaben: Um die Freigaben nach Hostnamen zur Verfügung zu stellen, sollte der Domänenadministrator die DNS-Datensätze mit dem CIFS-Servernamen und der IP-Adresse aktualisieren. Andernfalls ist der Zugriff auf die Freigabe nur über die IP-Adresse möglich. Beispiel:
+
** Verwenden Sie bei aktualisierten DNS-Datensätzen entweder den Hostnamen oder die IP, um auf die Freigabe zuzugreifen, z. B. file://hostname/share["\\hostname\Freigabe"^] Oder file://IP/share["\\IP\-Freigabe"^]
** Wenn keine DNS-Einträge aktualisiert werden, sollten Sie die IP-Adresse verwenden, um auf die Freigabe zuzugreifen, d. h. file://IP/share["\\IP\-Freigabe"^]


* *Freigabe erstellen* wird als asynchroner Job ausgeführt. Ihre Vorteile:
+
** Überprüfen Sie den Status des Jobs in der Jobliste. Informationen zur Verfolgung von Jobs finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Hier"].
** Überprüfen Sie nach Abschluss des Jobs den Status der Freigabe in der Liste *Shares*.



