---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_user.html 
keywords: netapp, keystone, modify, object, storage, user, 
summary: Keystone ändert einen Objekt-Storage-Benutzer 
---
= Ändern eines Objektspeicherbenutzers
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um Details eines Objektspeicherbenutzers, z. B. des Benutzernamens und der Gruppe, der sie zugewiesen sind, zu ändern.



=== Schritte

. Sehen Sie sich die an link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["Benutzerliste"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und auf der Anzeige Benutzer (nicht Gruppen) angezeigt werden.
. Suchen Sie den Benutzer in der Liste, und klicken Sie auf das Symbol Bearbeiten für die Gruppe.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Aktionen zur Listenansicht"].

. Im Dialogfeld Benutzer bearbeiten:
+
.. Geben Sie den Benutzernamen ein.
.. Wählen Sie die Objekt-Speichergruppe aus, der der Benutzer angehört.


. Klicken Sie Auf *Aktualisieren*. Dadurch wird ein Job zum Erstellen des Benutzers mit den angegebenen Einstellungen erstellt.

