---
sidebar: sidebar 
permalink: sewebiug_create_object_storage_user.html 
keywords: netapp, keystone, create, object, storage, user, 
summary: Keystone erstellt Benutzer von Objekt-Storage 
---
= Objektspeicherbenutzer Erstellen
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




=== Bevor Sie beginnen

Da ein Objektspeicherbenutzer einer Objektspeichergruppe angehört, muss die Objektspeichergruppe vorhanden sein, bevor Sie den Benutzer erstellen können.



=== Schritte

. Sehen Sie sich die an link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["Benutzerliste"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und auf der Anzeige Benutzer (keine Gruppen) angezeigt werden.
. Klicken Sie Auf *Benutzer Erstellen*.
. Im Dialogfeld Benutzer erstellen:
+
.. Geben Sie den Benutzernamen ein.
.. Wählen Sie die Gruppe aus, der das Mitglied angehört.


. Klicken Sie Auf *Erstellen*. Dadurch wird ein Job zum Erstellen des Benutzers mit den angegebenen Einstellungen erstellt.




=== Nachdem Sie fertig sind

Benutzer erstellen wird als asynchroner Job ausgeführt. Ihre Vorteile:

* Überprüfen Sie den Status des Jobs in der Jobliste.
* Überprüfen Sie nach Abschluss des Jobs den Status der Freigabe in der Benutzerliste.

