---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone erstellt einen S3-Schlüssel für einen Benutzer 
---
= Erstellen eines S3-Schlüssels für einen Benutzer
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um einen S3-Schlüssel für einen Benutzer zu erstellen.

Stellen Sie sicher, dass Sie den Schlüssel sofort nach der Erstellung erfassen. Es gibt keine Möglichkeit, Schlüsseldetails nach der Erstellung abzurufen.

.Schritte
. Sehen Sie sich die an link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["Benutzerliste"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und auf der Anzeige Benutzer (keine Gruppen) angezeigt werden.
. Suchen Sie den Benutzer in der Liste, und klicken Sie auf das Schlüsselsymbol für diese Gruppe.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Aktionen zur Listenansicht"].

. Im Dialogfeld S3-Schlüssel verwalten wird die Liste der Schlüssel für den Benutzer angezeigt.
. Wenn für den Benutzer keine Schlüssel vorhanden sind, klicken Sie auf *S3-Schlüssel erstellen*, um die Felder zum Erstellen eines Schlüssels anzuzeigen.
. Wenn der Schlüssel ablaufen soll, geben Sie das Ablaufdatum und die Ablaufzeit in UTC an. Andernfalls lassen Sie die Standardwerte für diese Felder.
. Klicken Sie zum Erstellen der Taste auf das Häkchen. Das Dialogfeld S3 Key Details wird angezeigt, in dem der Zugriffsschlüssel und der geheime Schlüssel angezeigt werden.
. Kopieren Sie den Zugriff und den geheimen Schlüssel, um den Benutzer über die Details zu informieren.
+
Stellen Sie sicher, dass Sie die wichtigsten Details erfassen, bevor Sie das Dialogfeld S3 Key Details schließen. Nach dem Schließen werden die Schlüsseldetails verdeckt und Sie können sie nicht mehr abrufen.

. Klicken Sie Auf *Schließen*.
. Klicken Sie erneut auf *Schließen*, um das Dialogfeld S3-Schlüssel verwalten zu schließen.

