---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_group.html 
keywords: netapp, keystone, modify, object, storage, group 
summary: Keystone ändert eine Objekt-Storage-Gruppe 
---
= Ändern einer Objektspeichergruppe
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um Details einer Objekt-Storage-Gruppe, z. B. des Gruppennamens und der S3-Richtlinie, zu ändern.

.Schritte
. Sehen Sie sich die an link:sewebiug_view_host_groups.html#view-host-groups["Gruppenliste"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und dass im Display Gruppen angezeigt werden (nicht Benutzer).
. Suchen Sie die Gruppe in der Liste, und klicken Sie auf das Symbol Bearbeiten für die Gruppe.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Aktionen zur Listenansicht"].

. Geben Sie im Dialogfeld Gruppe bearbeiten den Benutzernamen ein.
. Wählen Sie die S3-Richtlinie aus, die für die geänderte Gruppe gilt.
. Klicken Sie Auf *Erstellen*. Dadurch wird ein Job zum Ändern der Gruppe mit den angegebenen Einstellungen erstellt.

