---
sidebar: sidebar 
permalink: sewebiug_view_the_object_storage_group_and_users.html 
keywords: netapp, keystone, view, object, storage, group, users, 
summary: Keystone zeigt die Objekt-Storage-Gruppe und die Benutzer an 
---
= Zeigen Sie Objekt-Storage-Gruppen und Benutzer an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In der Liste Benutzerverwaltung werden die Benutzer und Gruppen des Objektspeichers für einen angegebenen Untermandanten angezeigt.

.Schritte
. Wählen Sie im Menü *OBJEKT-STORAGE > Benutzerverwaltung* aus.
. Verwenden Sie das Dropdown-Menü Untereinheit, um bei Bedarf einen anderen Untermandanten auszuwählen.
. Verwenden Sie die Registerkarten *Users* und *Groups*, um die Anzeige zwischen Benutzern und Gruppen umzuschalten.
+
** In der Liste Benutzer werden die für den ausgewählten Untermandanten definierten Objekt-Storage-Benutzer angezeigt. Für jeden Benutzer zeigt er seinen Namen und die Objektspeichergruppen an, zu denen sie gehören.
** In der Liste Gruppen werden die für den ausgewählten Untermandanten definierten Objektspeichergruppen angezeigt. Sie zeigt den Gruppennamen und die S3-Richtlinie an, die dieser Gruppe zugewiesen sind. Informationen zu Bucket-Gruppen und S3-Richtlinien finden Sie unter https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#access-policy-overview["Bucket- und Gruppenzugriffsrichtlinien"].
+
Weitere Informationen zur Verwendung der Funktionen einer Liste finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Aktionen zur Listenansicht"].




