---
sidebar: sidebar 
permalink: sewebiug_add_a_subscribed_service.html 
keywords: netapp, keystone, add, cloud, service, 
summary: Keystone ist als Cloud-Service erhältlich 
---
= Fügen Sie einen Cloud-Service hinzu
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird das Hinzufügen eines Cloud-Service beschrieben.

Die NetApp Service Engine unterstützt Azure NetApp Files.

Sie benötigen die Informationen zu den Cloud-Services, einschließlich der Zugangsdaten, um sich mit dem Service verbinden zu können. Die Informationen variieren je nach Typ des Cloud-Service.

.Schritte
. Wählen Sie im Menü * Cloud Services* aus.
. Klicken Sie Auf *Erstellen*.
. Wählen Sie auf der Seite „Cloud Service erstellen“ den Cloud-Servicetyp aus und geben Sie die relevanten Informationen für diesen Service-Typ an:
+
*Azure:*

+
.. Wählen Sie den Untermandanten aus.
.. Geben Sie einen Namen für die OCCM-Arbeitsumgebung ein, die für den Service erstellt werden soll.
.. Geben Sie die Azure Directory (Mandanten-)ID, die Azure Client-ID, Azure Client Secret und den Namen des Cloud-Service ein.


. Geben Sie ggf. Tags für den Dienst an.
. Klicken Sie Auf *Erstellen*.

