---
sidebar: sidebar 
permalink: sewebiug_delete_an_s3_key_for_a_user.html 
keywords: netapp, keystone, s3, key, user, 
summary: Keystone löscht einen S3-Schlüssel für einen Benutzer 
---
= Löschen Sie einen S3-Schlüssel für einen Benutzer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie diese Methode, um einen S3-Schlüssel für einen Benutzer zu löschen.

.Schritte
. Zeigen Sie den Objekt-Storage-Benutzer an link:sewebiug_view_the_object_storage_group_and_users.html["Zeigen Sie Objekt-Storage-Gruppen und Benutzer an"].
. Stellen Sie sicher, dass der richtige Untermandant ausgewählt ist und Sie auf die Registerkarte *Benutzer* geklickt haben.
. Suchen Sie den Benutzer in der Liste, und klicken Sie auf das Schlüsselsymbol für diese Gruppe.
+
Weitere Informationen zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Aktionen zur Listenansicht"].

. Das Dialogfeld *S3-Schlüssel verwalten* zeigt die Liste der Tasten für den Benutzer an.
. Suchen Sie in der Liste der Schlüssel den zu löschenden Schlüssel und klicken Sie auf das Symbol *Löschen*.
. Klicken Sie auf *Bestätigen*, um die Löschaktion zu bestätigen. Der Schlüssel wird aus der Liste der Benutzerschlüssel entfernt.
. Klicken Sie auf *Schließen*, um das Dialogfeld S3-Schlüssel verwalten zu schließen.

