---
sidebar: sidebar 
permalink: sewebiug_view_host_groups.html 
keywords: netapp, keystone, view, host, groups, 
summary: Keystone zeigt Host-Gruppen an 
---
= Arbeiten Sie mit Host-Gruppen
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hostgruppen sind definiert, um den Zugriff auf Festplatten zu bestimmen. Auf der Grundlage der Initiator-Nodes, die einer Host-Gruppe zugewiesen sind, wird der Zugriff dieser Host-Gruppe festgelegt.



== Zeigen Sie Host-Gruppen an

Um die Liste der Host-Gruppen anzuzeigen, wählen Sie im Menü * BLOCKSPEICHER > Host-Gruppen* aus.

In der Liste werden die definierten Hostgruppen angezeigt.

Auf dieser Seite können Sie eine neue Host-Gruppe erstellen, eine Host-Gruppe ändern und eine Host-Gruppe löschen.



= Erstellen Sie eine Host-Gruppe

Es gibt zwei Möglichkeiten, eine Host-Gruppe zu erstellen:

* Auf der folgenden Seite Host Groups beschrieben.
* Beim Erstellen einer neuen Festplatte. Verwenden Sie diese Methode, wenn Sie eine Hostgruppe in einem Blockspeicher erstellen müssen, der noch nicht initialisiert wurde. Weitere Informationen finden Sie unter link:sewebiug_create_a_new_disk.html#create-a-new-disk["Erstellen Sie ein neues Laufwerk"].
+
Es ist möglich, eine leere Host-Gruppe zu erstellen und als Platzhalter einer Festplatte zuzuordnen. Sie müssen die leere Host-Gruppe aktualisieren, um Initiatoren hinzufügen zu können, bevor Sie auf den Speicher zugreifen können.





=== Bevor Sie beginnen

Zum Erstellen der Host-Gruppe benötigen Sie Folgendes:

* Der Untermandant, die Region und die Zone, in der die Host-Gruppe erstellt werden soll.



NOTE: Wenn der Blockspeicher für eine Submandant/Zone-Kombination noch nicht initialisiert wurde, können Sie mit dieser Methode keine Host-Gruppe erstellen. Eine Alternative ist, dem zu folgen link:sewebiug_create_a_new_disk.html#create-a-new-disk["Erstellen Sie ein neues Laufwerk"] Prozess, mit dem Sie den Blockspeicher initialisieren und eine Host-Gruppe als Teil des Prozesses erstellen können.

* Ein Name für die Host-Gruppe
* Das Host-Gruppenprotokoll: ISCSI oder FCP
* Die Liste der hinzuzufügenden Initiatoren der Gruppe: WWPNs für FC-Hosts-Nodes oder IQNs für iSCSI-Host-Node-Namen.
* Ein Alias für jeden Initiator. Ein Alias ist ein Name, um den Initiator-Server oder einen individuellen Port/eine Schnittstelle auf dem Server zu identifizieren. Beispiel: Server 4.




=== Schritte

. link:sewebiug_view_host_groups.html#view-host-groups["Zeigen Sie die Host-Gruppen an"] Liste.
. Klicken Sie Auf *Hostgruppe Erstellen*.
. Auf der Seite Host-Gruppe erstellen:
+
.. Wählen Sie das Protokoll iSCSI oder FCP aus.
.. Wählen Sie den Untermandanten, die Region und die Zone und für die Host-Gruppe aus.


. Geben Sie einen Namen für die Host-Gruppe an.
. Wählen Sie das Betriebssystem: Das Betriebssystem der Festplatte aus.
. Fügen Sie die Initiatoren für die Gruppe hinzu. Geben Sie für jeden Initiator den Alias und den Initiator an.
. Fügen Sie bei Bedarf Tags (Schlüsselwert-Paare) zur Host-Gruppe im Abschnitt Tags hinzu.
. Klicken Sie Auf *Erstellen*. Dadurch wird die Host-Gruppe erstellt.




=== Nachdem Sie fertig sind

Nach der Erstellung der Host-Gruppe ist sie für die Zuordnung zu Festplatten verfügbar.



== Ändern Sie Host-Gruppen

Sie können eine Host-Gruppe zum Hinzufügen, Entfernen oder Ändern von Initiatoren ändern.

Durch das Ändern einer Host-Gruppe wird der Zugriff auf jede Festplatte geändert, die der Host-Gruppe zugeordnet ist.

Sie können den Alias eines Initiators nicht ändern. Um den Alias zu ändern, löschen Sie den Initiator aus der Gruppe, und erstellen Sie ihn dann erneut.



=== Schritte

. Sehen Sie sich die an link:sewebiug_view_host_groups.html#view-host-groups["Host-Gruppen"] Liste.
. Suchen Sie die Host-Gruppe in der Liste, und klicken Sie auf das Bearbeiten-Symbol für diese Host-Gruppe.
+
Um einen bestehenden Initiator zu ändern, suchen Sie den Initiator in der Liste, bearbeiten Sie den Initiatorwert und klicken Sie auf *Update*.

+
So fügen Sie einen Initiator hinzu:

+
.. Klicken Sie auf *Initiator hinzufügen*.
.. Geben Sie den Alias und Initiator an.
.. Klicken Sie Auf *Erstellen*.
+
Um einen Initiator aus der Host-Gruppe zu entfernen, suchen Sie den Initiator in der Liste und klicken Sie auf das Symbol Löschen.



. Klicken Sie Auf *Fertig*.




== Löschen Sie eine Hostgruppe

Sie können eine Host-Gruppe löschen, wenn der Host-Gruppe keine Laufwerke zugeordnet sind.



=== Schritte

. Sehen Sie sich die an link:sewebiug_view_host_groups.html#view-host-groups["Host-Gruppen"] Liste.
. Suchen Sie die Host-Gruppe in der Liste, und klicken Sie auf das Symbol Löschen für diese Host-Gruppe.
. Geben Sie im Dialogfeld Löschen bestätigen den Hostnamen ein, um zu bestätigen, dass Sie die Host-Gruppe löschen möchten.
. Klicken Sie Auf *Bestätigen*.

