---
sidebar: sidebar 
permalink: sewebiug_create_an_adhoc_snapshot_of_a_disk.html 
keywords: netapp, keystone, create, adhoc, snapshot, disk 
summary: Keystone erstellt einen Ad-hoc-Snapshot einer Festplatte 
---
= Erstellen Sie einen Ad-hoc-Snapshot einer Festplatte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird beschrieben, wie ein Ad-hoc-Snapshot einer Festplatte erstellt wird.

.Schritte
. Sehen Sie sich die an link:sewebiug_view_disks.html#view-disks["Festplattenliste"].
. Suchen Sie den Datenträger in der Liste, und klicken Sie auf das Snapshot-Symbol für diesen Datenträger. (Einzelheiten zum Arbeiten mit Elementen in Listen finden Sie unter link:sewebiug_netapp_service_engine_web_interface_overview#list-view["Aktionen zur Listenansicht"]).
. Geben Sie im Dialogfeld Snapshot erstellen einen Namen für Ihren Snapshot ein und klicken Sie auf *Erstellen*.


.Nachdem Sie fertig sind
Der Snapshot kann ein paar Minuten dauern, bis er verfügbar ist. Wenn verfügbar, können Sie eine weitere Festplatte durch Klonen dieses Snapshots erstellen. Weitere Informationen finden Sie unter link:sewebiug_create_a_disk_from_a_snapshot.html["Erstellen Sie eine Festplatte aus einem Snapshot"].
