---
sidebar: sidebar 
permalink: sewebiug_managing_azure_capacity_pools.html 
keywords: netapp, keystone, managing, azure, capacity, pools, 
summary: Keystone managt Azure-Kapazitätspools 
---
= Verwalten von Azure-Kapazitätspools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird das Management von Azure-Kapazitätspools beschrieben:


NOTE: Zum Managen von Azure-Kapazitätspools ist der Administratorzugriff des Kunden erforderlich.

In diesem Abschnitt wird die Ausführung der folgenden Aufgaben beschrieben:

* Zeigen Sie eine Liste der Azure-Kapazitätspools an
* Fügen Sie einen Azure-Kapazitätspool hinzu
* Ändern Sie die Details zum Azure Capacity Pool
* Löschen Sie einen Azure-Kapazitätspool




== Zeigen Sie eine Liste der Azure-Kapazitätspools an

In der Liste der Azure Kapazitätspools wird eine Liste der Kapazitätspools für einen angegebenen Untermandanten und Speicherort angezeigt. Um die Liste anzuzeigen, wählen Sie im Menü *FILE SERVICES > Azure Capacity Pools* aus.

In der Liste werden einfache Informationen zu den einzelnen Azure-Kapazitätspools angezeigt. Mit den Aktionssymbolen neben jedem Azure-Kapazitätspool können Sie den Azure-Kapazitätspool ändern oder löschen.



== Fügen Sie einen Azure-Kapazitätspool hinzu

In diesem Abschnitt wird das Hinzufügen eines Azure Capacity Pools beschrieben.

.Bevor Sie beginnen
Sie benötigen:

* Der Untermandant, zu dem die Kapazität gehört
* Das ANF-Konto
* Servicelevel
* Ein Name für den Kapazitäts-Pool
* Die Größe des Pools


.Schritte
. Wählen Sie aus dem Menü *FILE SERVICES > Azure Capacity Pools* aus.
. Klicken Sie Auf *Erstellen*.
. Geben Sie im Dialogfeld Azure Capacity Pool erstellen den Untermandanten, das ANF-Konto, das Service-Level, den Namen und die Größe an.
. Fügen Sie, falls erforderlich, Tags zum Kapazitäts-Pool hinzu.
. Klicken Sie Auf *Erstellen*. Wenn der Kapazitäts-Pool erstellt wird, ändert sich der Status in `Succeeded` (kann in der Liste Azure Capacity Pools angezeigt werden).




== Ändern Sie die Details zum Azure Capacity Pool

Verwenden Sie diese Methode, um die Details eines Azure-Kapazitätspools zu ändern. Sie können den Service-Level die Größe des Pools ändern und Tags hinzufügen oder entfernen.

.Schritte
. Wählen Sie aus dem Menü *FILE SERVICES > Azure Capacity Pools* aus.
. Suchen Sie in der Liste den Azure Capacity Pool und klicken Sie auf das Bearbeiten-Symbol.
. Nehmen Sie im Dialogfeld Azure-Kapazitätspool managen alle erforderlichen Änderungen vor.
. Klicken Sie Auf *Aktualisieren*.




== Löschen Sie einen Azure-Kapazitätspool

Verwenden Sie diese Methode, um einen Azure-Kapazitätspool zu löschen.

.Schritte
. Wählen Sie aus dem Menü *FILE SERVICES > Azure Capacity Pools* aus.
. Suchen Sie in der Liste den Azure Capacity Pool und klicken Sie auf das Löschsymbol.
. Geben Sie im Dialogfeld Löschen bestätigen den Namen des zu löschenden Azure-Kapazitätspools ein.
. Klicken Sie Auf *Bestätigen*.

