---
sidebar: sidebar 
permalink: sewebiug_alerts.html 
keywords: netapp, keystone, alert, create, custom alert 
summary: Erstellen und Managen von Warnmeldungen 
---
= Erstellen und Managen von Warnmeldungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Warnmeldungen sind Meldungen, die entweder automatisch ausgelöst oder manuell erstellt werden, um Informationen zu wichtigen Ereignissen in Ihrer Umgebung auszutauschen.

Wenn Sie Storage bereitstellen, werden in den folgenden Szenarien automatische Alarme ausgelöst:

* Das neue Laufwerk oder die neue Dateifreigabe drückt das Abonnement in Burst aus
* Die neue Festplatten- oder Dateifreigabe wird in einem neuen Abonnement bereitgestellt
* Die verbrauchte Kapazität innerhalb des Abonnements hat den Schwellenwert überschritten oder liegt nahe der zugesagt Kapazität


Über den Bildschirm *Alerts* können Sie die vom System erzeugten und vom Benutzer generierten Warnmeldungen in Ihrer Umgebung anzeigen.

Sie können auch benutzerdefinierte Warnmeldungen erstellen und anderen Benutzern anzeigen. Diese können bei Bedarf die Alarme für sich selbst und andere Benutzer innerhalb ihrer Mandanten anzeigen und abweisen.



== Erstellen einer Warnmeldung in der mandantenfähigen Umgebung

Als Partner-Administrator können Sie Alarme manuell erstellen und an einen einzelnen Mandanten oder alle Mandanten in Ihrer Umgebung senden.


NOTE: Sie können eine von Ihnen erstellte Warnmeldung verwerfen. Er wird jedoch nur für Mieter abgewiesen, die ihn noch nicht gesehen haben.

.Schritte
. Wählen Sie im Menü die Option *ADMINISTRATION* > *Alarme* aus.
. Klicken Sie auf *Warnung erstellen*.
. Wählen Sie auf dem Bildschirm * Alarm erstellen* den Status und den Mandanten aus, an den Sie die Warnung senden möchten, und fügen Sie die Nachricht hinzu.
+

NOTE: Wenn Sie die Warnung an alle Mandanten in Ihrer Umgebung senden möchten, wählen Sie „Alle“.

. Klicken Sie Auf *Erstellen*. Die neue Meldung wird erstellt.




== Erstellen einer Meldung in Ihrer Mandantenfähigkeit

Als Mandantenadministrator können Sie manuell Warnmeldungen erstellen und an alle Benutzer in Ihrer Umgebung senden.


NOTE: Sie können eine von Ihnen erstellte Warnmeldung verwerfen. Er wird jedoch nur für Benutzer abgewiesen, die ihn noch nicht gesehen haben.

.Schritte
. Wählen Sie im Menü die Option *ADMINISTRATION* > *Alarme* aus.
. Klicken Sie auf *Warnung erstellen*.
. Wählen Sie auf dem Bildschirm *Alarm erstellen* den Status aus und fügen Sie die Nachricht hinzu.
. Klicken Sie Auf *Erstellen*. Die neue Meldung wird erstellt.

