---
sidebar: sidebar 
permalink: sewebiug_working_with_block_storage_overview.html 
keywords: netapp, keystone, working, block, storage, overview, 
summary: Keystone Arbeiten mit Block Storage Übersicht 
---
= Überblick
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Block-Storage-Systemen wird die Daten-Storage-Systeme mit einer eindeutigen Kennung in einzelne Komponenten unterteilt. Bei der NetApp Service Engine werden der Block-Datenspeicher als Block-Store und die einzelnen Elemente als Festplatten bezeichnet.

Blockspeicher gehören zu einem Untermandanten und werden innerhalb einer Zone (ein Blockspeicher pro Zone pro Untermandant) angegeben. Ein Blockspeicher verfügt über Netzwerkattribute (z. B. IP-Adresse und VLAN-ID), die für den Zugriff auf Festplatten über das iSCSI- oder FC-Protokoll verwendet werden. Disaster-Recovery-DP kann auf einem Blockspeicher aktiviert werden. Weitere Informationen finden Sie unter link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery.html["Disaster Recovery"].

Blockspeicher müssen initialisiert werden, bevor sie verwendet werden können. Wenn Block-Speicher verfügbar ist und nicht initialisiert wurde, kann er initialisiert werden, bevor die erste Festplatte im Blockspeicher im Rahmen des Prozesses „Create Disk“ erstellt wird.

Festplatten werden in Blockspeichern erstellt. Festplatten verfügen über viele konfigurierbare Attribute Kapazität und zugehöriger Service-Level. DP-Optionen wie link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#snapshots["Snapshots"] Und link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery["Disaster Recovery"] Kann für eine Festplatte aktiviert werden.

Der Zugriff auf Festplatten wird über Host-Gruppen gesteuert. Host-Gruppen bestehen aus Initiator-Node-Namen. Durch Zuordnung einer oder mehrerer Host-Gruppen zu einer Festplatte können Sie festlegen, welche Initiatoren Zugriff auf die Festplatte haben.

Host-Gruppen:

* Sind protokollspezifisch. Sie können entweder sein:
+
** FC-Protokoll-Host-Gruppen: Diese bestehen aus Initiatoren, die FC World Wide Port Names (WWPNs) sind. Beispiel: `20:56:00:a0:98:5c:0d:da`).
** ISCSI-Protokoll-Host-Gruppen: Diese bestehen aus Initiatoren, die iSCSI-qualifizierte Namen (IQNs) sind. Beispiel: `iqn.1998-01.com.vmware:esx2`.


* Besteht aus Alias-/Initiator-Paaren. Ein Alias ermöglicht eine einfache Möglichkeit, den Initiator zu identifizieren. Beispiel: `esxserver1`.
* Kann ohne Initiatoren erstellt werden. Leere Host-Gruppen können Festplatten als Platzhalter zugeordnet werden, müssen aber vollständig definiert sein, um den Zugriff auf die Festplatte zu ermöglichen. Mithilfe von Hostgruppen können folgende Aufgaben ausgeführt werden:
* Zuordnen mehrerer Festplatten zu demselben Satz von Initiatoren
* Der Satz der Initiatoren über mehrere Festplatten hinweg wird aktualisiert.


Dieser Abschnitt enthält Informationen zu:

* Arbeiten mit Host-Gruppen:
+
** Zeigen Sie Host-Gruppen an
** Erstellen Sie eine Host-Gruppe
** Hostgruppeninitiatoren ändern
** Löschen Sie eine Host-Gruppe


* Arbeiten mit Festplatten:
+
** Zeigen Sie Festplatten an
** Erstellen Sie ein neues Laufwerk
** Erstellen Sie eine Festplatte aus einem Snapshot
** Ändern Sie eine Festplatte
** Löschen Sie eine Festplatte
** Erstellen Sie einen Ad-hoc-Snapshot einer Festplatte



