---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Keystone – Managen von Azure Volumes 
---
= Verwalten von Azure Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Abschnitt wird das Verwalten von Azure Volumes beschrieben.


NOTE: Zum Verwalten von Azure Volumes ist der Administrator des Kunden erforderlich.

In diesem Abschnitt wird die Ausführung der folgenden Aufgaben beschrieben:

* Liste von Azure Volumes anzeigen
* Fügen Sie ein Azure Volume hinzu.
* Ändern Sie die Details zu Azure Volumes.
* Löschen Sie ein Azure Volume.




== Liste von Azure Volumes anzeigen

In der Liste der Azure Volumes wird eine Liste der Azure Volumes Pools für einen bestimmten Untermandanten und Speicherort angezeigt. Um die Liste anzuzeigen, wählen Sie im Menü *FILE SERVICES > Azure Volumes* aus.

In der Liste werden einfache Informationen zu jedem Azure-Volume angezeigt. Über die Aktionssymbole neben den einzelnen Azure Volumes können Sie das Azure Volume ändern oder löschen.



== Fügen Sie ein Azure Volume hinzu

In diesem Abschnitt wird das Hinzufügen eines Azure-Volume beschrieben.

.Bevor Sie beginnen
Sie benötigen:

* Der Submandant, zu dem das Azure Volume gehört
* Das ANF-Konto
* Virtuelles Azure Netzwerk (vnet) und Subnetz
* Der Kapazitäts-Pool für das Volume
* Ein Name für das Volume
* Dateipfad
* Die Quote (Größe) des Volumens


.Schritte
. Wählen Sie im Menü *FILE SERVICES > Azure Volumes* aus.
. Klicken Sie Auf *Erstellen*.
. Geben Sie im Dialogfeld Azure-Volume erstellen den Untermandanten, das ANF-Konto, das vnet, das Subnetz, Der Kapazitäts-Pool, der Name des Volume, der Dateipfad und das Kontingent. Stellen Sie sicher, dass Sie einen eindeutigen Dateipfad für eine erfolgreiche Volume-Erstellung eingeben.
. Fügen Sie bei Bedarf Tags zum Volume hinzu.
. Klicken Sie Auf *Erstellen*. Wenn ein Azure Volume erstellt wird, ändert sich der Status des Volume in `Succeeded` (kann in der Liste Azure Volumes angezeigt werden).




== Ändern Sie die Details zu Azure Volumes

Verwenden Sie diese Methode, um die Details eines Azure Volumes zu ändern. Sie können den Dateipfad und das Kontingent ändern und Tags hinzufügen oder entfernen.

.Schritte
. Wählen Sie im Menü *FILE SERVICES > Azure Volumes* aus.
. Suchen Sie in der Liste das Azure Volume und klicken Sie auf das Bearbeiten-Symbol.
. Nehmen Sie im Dialogfeld Azure-Volume managen die erforderlichen Änderungen vor. Wenn Sie den Dateipfad oder das Kontingent ändern, stellen Sie sicher, dass der Dateipfad eindeutig ist und dass das Kontingent nicht das verfügbare Kontingent im Pool überschreitet.
. Klicken Sie Auf *Aktualisieren*.




== Löschen Sie ein Azure Volume

Verwenden Sie diese Methode zum Löschen eines Azure Volumes.

.Schritte
. Wählen Sie im Menü *FILE SERVICES > Azure Volumes* aus.
. Suchen Sie in der Liste das Azure Volume und klicken Sie auf das Löschsymbol.
. Geben Sie im Dialogfeld Löschen bestätigen den Namen des zu löschenden Azure-Volumes ein.
. Klicken Sie Auf *Bestätigen*.

